services:
  rullst:
    build:
      context: ..
      dockerfile: benchmark/rullst/Dockerfile
    ports:
      - "8000:3000"

  axum:
    build:
      context: axum
    ports:
      - "8001:3000"

  actix:
    build:
      context: actix
    ports:
      - "8002:3000"

  loco:
    build:
      context: loco
    ports:
      - "8003:3000"

  rocket:
    build:
      context: rocket
    ports:
      - "8004:8000"

  leptos:
    build:
      context: leptos
    ports:
      - "8005:3000"

  gin:
    build:
      context: gin
    ports:
      - "8006:3000"

  fiber:
    build:
      context: fiber
    ports:
      - "8007:3000"

  django:
    build:
      context: django
    ports:
      - "8008:8000"

  laravel:
    build:
      context: laravel
    ports:
      - "8009:8000"

  nextjs:
    build:
      context: nextjs
    ports:
      - "8010:3000"

  nestjs:
    build:
      context: nestjs
    ports:
      - "8011:3000"

  zap:
    build:
      context: zap
    ports:
      - "8012:3000"

  springboot:
    build:
      context: springboot
    ports:
      - "8013:8080"

  bombardier:
    build:
      context: bombardier

