// src/generators/foundry/config.rs — Foundry.toml template, parsing, and validation.

use colored::*;

pub fn generate_foundry_toml_template(project_name: &str) -> String {
    format!(
        r#"# ┌──────────────────────────────────────────────────────────────┐
# │           Rullst Foundry - Deployment Manifest               │
# │  Generated by `cargo rullst foundry:init`                    │
# │  Edit this file and run `cargo rullst foundry:deploy`        │
# └──────────────────────────────────────────────────────────────┘

[app]
# The name of your application (used for container and systemd service naming)
name = "{project_name}"
# The public domain that will serve your app (Caddy will get SSL automatically)
domain = "yourdomain.com"
# The internal port your Rullst server binds to
port = 3000

[deploy]
# Cloud provider: "hetzner" | "aws" | "gcp" | "azure" | "oci" | "digitalocean"
provider = "hetzner"

[server]
# Public IP or hostname of the target server
host = "1.2.3.4"
# SSH login user (typically root for fresh VPS, or a sudo user for managed VMs)
user = "root"
# Path to your SSH private key (leave empty to use SSH agent)
ssh_key = "~/.ssh/id_rsa"
# SSH port (default: 22)
ssh_port = 22

[build]
# Build profile: "release" | "debug"
profile = "release"
# Target triple (leave empty to use the local default)
# For cross-compilation from macOS/Windows to Linux: "x86_64-unknown-linux-musl"
target = ""

[database]
# Database type: "sqlite" | "postgres" | "mysql"
type = "sqlite"
# SQLite: path relative to the deployed binary  |  Postgres/MySQL: full connection URL
url = "sqlite:///app/data/db.sqlite"

[caddy]
# Enable automatic HTTPS via Caddy (strongly recommended for production)
auto_https = true
# Optional: add extra Caddyfile directives (e.g., rate_limit, header, etc.)
extra_directives = ""

[env]
# Environment variables injected into the container at runtime.
# Add your application secrets here (they will NOT be committed if you gitignore Foundry.toml).
APP_ENV = "production"
APP_KEY = "CHANGE_ME_TO_A_SECURE_RANDOM_KEY"
DATABASE_URL = "sqlite:///app/data/db.sqlite"
# STRIPE_SECRET_KEY = ""
# AWS_ACCESS_KEY_ID = ""
"#,
        project_name = project_name
    )
}

pub struct FoundryConfig {
    pub app_name: String,
    pub domain: String,
    pub port: String,
    pub host: String,
    pub user: String,
    pub ssh_key: String,
    pub ssh_port: String,
    pub provider: String,
    pub db_type: String,
    pub profile: String,
    pub target_triple: String,
    pub auto_https: String,
    pub env_vars: Vec<(String, String)>,
}

pub fn parse_foundry_config(content: &str) -> FoundryConfig {
    let get_value = |key: &str| -> String {
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with(key) && trimmed.contains('=') {
                return trimmed
                    .split_once('=')
                    .map(|x| x.1)
                    .unwrap_or("")
                    .trim()
                    .trim_matches('"')
                    .to_string();
            }
        }
        String::new()
    };

    let mut env_vars = Vec::new();
    let mut in_env = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[env]" {
            in_env = true;
            continue;
        }
        if trimmed.starts_with('[') && trimmed != "[env]" {
            in_env = false;
        }
        if in_env && trimmed.contains('=') && !trimmed.starts_with('#') {
            let mut parts = trimmed.splitn(2, '=');
            if let (Some(k), Some(v)) = (parts.next(), parts.next()) {
                env_vars.push((k.trim().to_string(), v.trim().trim_matches('"').to_string()));
            }
        }
    }

    FoundryConfig {
        app_name: get_value("name"),
        domain: get_value("domain"),
        port: get_value("port"),
        host: get_value("host"),
        user: get_value("user"),
        ssh_key: get_value("ssh_key"),
        ssh_port: get_value("ssh_port"),
        provider: get_value("provider"),
        db_type: get_value("type"),
        profile: get_value("profile"),
        target_triple: get_value("target"),
        auto_https: get_value("auto_https"),
        env_vars,
    }
}

pub fn validate_foundry_config(cfg: &FoundryConfig) {
    if cfg.app_name.is_empty()
        || !cfg
            .app_name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        println!("{}", "❌ Error: Invalid app name in Foundry.toml. Only alphanumeric, dashes and underscores are allowed.".red().bold());
        std::process::exit(1);
    }
    if !cfg.domain.is_empty()
        && !cfg
            .domain
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-')
    {
        println!("{}", "❌ Error: Invalid domain in Foundry.toml. Only alphanumeric, dots and dashes are allowed.".red().bold());
        std::process::exit(1);
    }
    if cfg.ssh_key.starts_with('-') {
        println!(
            "{}",
            "❌ Error: Invalid SSH key path in Foundry.toml. Path cannot start with a dash."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
    if cfg.user.is_empty()
        || !cfg
            .user
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        println!("{}", "❌ Error: Invalid SSH user in Foundry.toml. Only alphanumeric, dashes and underscores are allowed.".red().bold());
        std::process::exit(1);
    }
    if cfg.host.is_empty()
        || !cfg
            .host
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == ':')
    {
        println!("{}", "❌ Error: Invalid SSH host in Foundry.toml. Only alphanumeric, dots, colons and dashes are allowed.".red().bold());
        std::process::exit(1);
    }
    if (!cfg.ssh_port.is_empty() && !cfg.ssh_port.chars().all(|c| c.is_ascii_digit()))
        || (!cfg.port.is_empty() && !cfg.port.chars().all(|c| c.is_ascii_digit()))
    {
        println!(
            "{}",
            "❌ Error: Invalid port in Foundry.toml. Only digits are allowed."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
    for (k, v) in &cfg.env_vars {
        if !k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            || v.contains('\n')
            || v.contains('\r')
        {
            println!(
                "{}",
                "❌ Error: Invalid environment variable in Foundry.toml. Keys must be alphanumeric/underscores and values cannot contain newlines."
                    .red()
                    .bold()
            );
            std::process::exit(1);
        }
    }
}
