// src/generators/foundry/config.rs — Foundry.toml template, parsing, and validation.

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum FoundryConfigError {
    #[error("Foundry.toml is not valid TOML: {0}")]
    Parse(String),
    #[error("invalid Foundry configuration: {0}")]
    Invalid(String),
}

pub fn generate_foundry_toml_template(project_name: &str) -> String {
    format!(
        r#"# ┌──────────────────────────────────────────────────────────────┐
# │           Rullst Foundry - Deployment Manifest               │
# │  Generated by `cargo rullst foundry:init`                    │
# │  Edit this file and run `cargo rullst foundry:deploy`        │
# └──────────────────────────────────────────────────────────────┘

[app]
# The name of your application (used for binary and systemd service naming)
name = "{project_name}"
# The public domain that will serve your app (Caddy may manage HTTPS after DNS and network validation)
domain = "yourdomain.com"
# The internal port your Rullst server binds to
port = 3000

[deploy]
# Cloud provider: "hetzner" | "aws" | "gcp" | "azure" | "oci" | "digitalocean"
provider = "hetzner"

[server]
# Public IP or hostname of the target server
host = "1.2.3.4"
# SSH login user (root, or a user with passwordless non-interactive sudo)
user = "root"
# Path to your SSH private key (leave empty to use SSH agent)
ssh_key = "~/.ssh/id_rsa"
# SSH port (default: 22)
ssh_port = 22

[build]
# Build profile: "release" | "debug"
profile = "release"
# Target triple (leave empty to use the local default)
# For cross-compilation from macOS/Windows to Linux: "x86_64-unknown-linux-musl"
target = ""

[database]
# Database type: "sqlite" | "postgres" | "mysql"
type = "sqlite"
# SQLite: path relative to the deployed binary  |  Postgres/MySQL: full connection URL
url = "sqlite:///opt/rullst/{project_name}/data/db.sqlite"

[caddy]
# Enable automatic HTTPS via Caddy (strongly recommended for production)
auto_https = true
[env]
# Environment variables loaded by the systemd service at runtime.
# Add your application secrets here (they will NOT be committed if you gitignore Foundry.toml).
RULLST_ENV = "production"
APP_KEY = "CHANGE_ME_TO_A_SECURE_RANDOM_KEY"
DATABASE_URL = "sqlite:///opt/rullst/{project_name}/data/db.sqlite"
# STRIPE_SECRET_KEY = ""
# AWS_ACCESS_KEY_ID = ""
"#,
        project_name = project_name
    )
}

pub struct FoundryConfig {
    pub app_name: String,
    pub domain: String,
    pub port: String,
    pub host: String,
    pub user: String,
    pub ssh_key: String,
    pub ssh_port: String,
    pub provider: String,
    pub db_type: String,
    pub profile: String,
    pub target_triple: String,
    pub auto_https: String,
    pub env_vars: Vec<(String, String)>,
}

pub fn parse_foundry_config(content: &str) -> Result<FoundryConfig, FoundryConfigError> {
    let document = toml::from_str::<toml::Value>(content)
        .map_err(|error| FoundryConfigError::Parse(error.to_string()))?;
    let value = |section: &str, key: &str| {
        document
            .get(section)
            .and_then(|table| table.get(key))
            .map(toml_scalar_to_string)
            .transpose()
            .map(|value| value.unwrap_or_default())
    };
    let env_vars = document
        .get("env")
        .and_then(toml::Value::as_table)
        .map(|table| {
            table
                .iter()
                .map(|(key, value)| Ok((key.clone(), toml_scalar_to_string(value)?)))
                .collect::<Result<Vec<_>, FoundryConfigError>>()
        })
        .transpose()?
        .unwrap_or_default();

    Ok(FoundryConfig {
        app_name: value("app", "name")?,
        domain: value("app", "domain")?,
        port: value("app", "port")?,
        host: value("server", "host")?,
        user: value("server", "user")?,
        ssh_key: value("server", "ssh_key")?,
        ssh_port: value("server", "ssh_port")?,
        provider: value("deploy", "provider")?,
        db_type: value("database", "type")?,
        profile: value("build", "profile")?,
        target_triple: value("build", "target")?,
        auto_https: value("caddy", "auto_https")?,
        env_vars,
    })
}

fn toml_scalar_to_string(value: &toml::Value) -> Result<String, FoundryConfigError> {
    match value {
        toml::Value::String(value) => Ok(value.clone()),
        toml::Value::Integer(value) => Ok(value.to_string()),
        toml::Value::Float(value) => Ok(value.to_string()),
        toml::Value::Boolean(value) => Ok(value.to_string()),
        _ => Err(FoundryConfigError::Invalid(
            "configuration values must be TOML scalars".to_string(),
        )),
    }
}

fn valid_domain(domain: &str) -> bool {
    !domain.is_empty()
        && domain.len() <= 253
        && domain.split('.').all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && !label.starts_with('-')
                && !label.ends_with('-')
                && label
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
        })
}

fn valid_port(port: &str) -> bool {
    port.parse::<u16>().is_ok_and(|port| port > 0)
}

pub fn validate_foundry_config(cfg: &FoundryConfig) -> Result<(), FoundryConfigError> {
    if cfg.app_name.is_empty()
        || cfg.app_name.len() > 64
        || !cfg
            .app_name
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphanumeric())
        || !cfg
            .app_name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Err(FoundryConfigError::Invalid(
            "app.name must start with an ASCII alphanumeric character and contain at most 64 alphanumeric, dash, or underscore characters".to_string(),
        ));
    }
    if !matches!(cfg.auto_https.as_str(), "true" | "false" | "") {
        return Err(FoundryConfigError::Invalid(
            "caddy.auto_https must be true or false".to_string(),
        ));
    }
    if !valid_domain(&cfg.domain) {
        return Err(FoundryConfigError::Invalid(
            "app.domain must be a valid DNS hostname or IPv4 address".to_string(),
        ));
    }
    if cfg.ssh_key.starts_with('-') || cfg.ssh_key.chars().any(char::is_control) {
        return Err(FoundryConfigError::Invalid(
            "server.ssh_key cannot start with a dash or contain control characters".to_string(),
        ));
    }
    if cfg.user.is_empty()
        || cfg.user.len() > 64
        || !cfg
            .user
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Err(FoundryConfigError::Invalid(
            "server.user must contain only ASCII alphanumeric, dash, or underscore characters"
                .to_string(),
        ));
    }
    if !valid_domain(&cfg.host) {
        return Err(FoundryConfigError::Invalid(
            "server.host must be a DNS hostname or IPv4 address; IPv6 SCP targets are not supported"
                .to_string(),
        ));
    }
    if (!cfg.ssh_port.is_empty() && !valid_port(&cfg.ssh_port))
        || (!cfg.port.is_empty() && !valid_port(&cfg.port))
    {
        return Err(FoundryConfigError::Invalid(
            "application and SSH ports must be integers from 1 through 65535".to_string(),
        ));
    }
    if cfg.provider.is_empty()
        || cfg.provider.len() > 64
        || !cfg
            .provider
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err(FoundryConfigError::Invalid(
            "deploy.provider must be a bounded ASCII identifier".to_string(),
        ));
    }
    if !matches!(cfg.db_type.as_str(), "sqlite" | "postgres" | "mysql") {
        return Err(FoundryConfigError::Invalid(
            "database.type must be sqlite, postgres, or mysql".to_string(),
        ));
    }
    if !matches!(cfg.profile.as_str(), "" | "debug" | "release") {
        return Err(FoundryConfigError::Invalid(
            "build.profile must be debug or release".to_string(),
        ));
    }
    if cfg.target_triple.len() > 128
        || (!cfg.target_triple.is_empty()
            && (cfg.target_triple.starts_with('-')
                || !cfg.target_triple.bytes().all(|byte| {
                    byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')
                })))
    {
        return Err(FoundryConfigError::Invalid(
            "build.target contains unsupported characters".to_string(),
        ));
    }
    if cfg.env_vars.len() > 256 {
        return Err(FoundryConfigError::Invalid(
            "env may contain at most 256 entries".to_string(),
        ));
    }
    for (k, v) in &cfg.env_vars {
        if k.is_empty()
            || k.len() > 128
            || !k
                .bytes()
                .next()
                .is_some_and(|byte| byte.is_ascii_alphabetic() || byte == b'_')
            || !k
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
            || v.len() > 16_384
            || v.contains("CHANGE_ME")
            || v.contains("REPLACE_WITH")
            || v.chars()
                .any(|character| matches!(character, '\n' | '\r' | '\0'))
        {
            return Err(FoundryConfigError::Invalid(
                "environment keys must be shell identifiers of at most 128 bytes; values must be bounded, single-line, NUL-free, and must not retain generated secret placeholders".to_string(),
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_uses_the_canonical_environment_name() {
        let generated = generate_foundry_toml_template("demo");
        let parsed = parse_foundry_config(&generated).expect("template should parse");
        assert!(matches!(
            validate_foundry_config(&parsed),
            Err(FoundryConfigError::Invalid(_))
        ));
        assert!(
            parsed
                .env_vars
                .contains(&("RULLST_ENV".to_string(), "production".to_string()))
        );
        assert!(!parsed.env_vars.iter().any(|(name, _)| name == "APP_ENV"));
    }

    fn usable_template() -> String {
        generate_foundry_toml_template("demo")
            .replace("CHANGE_ME_TO_A_SECURE_RANDOM_KEY", "local-test-fixture")
    }

    #[test]
    fn deployment_hosts_accept_exact_dns_length_boundaries() {
        let longest = format!(
            "{}.{}.{}.{}",
            "a".repeat(63),
            "b".repeat(63),
            "c".repeat(63),
            "d".repeat(61),
        );
        assert_eq!(longest.len(), 253);
        for domain in ["a", "A-b.example", "127.0.0.1", &"a".repeat(63), &longest] {
            let mut config = parse_foundry_config(&usable_template()).unwrap();
            config.domain = domain.to_owned();
            config.host = domain.to_owned();
            validate_foundry_config(&config).unwrap();
        }
    }

    #[test]
    fn deployment_rejects_invalid_domain_or_ssh_host_independently() {
        let too_long = format!(
            "{}.{}.{}.{}",
            "a".repeat(63),
            "b".repeat(63),
            "c".repeat(63),
            "d".repeat(62),
        );
        assert_eq!(too_long.len(), 254);
        for domain in [
            "",
            ".example",
            "example.",
            "a..example",
            "-a.example",
            "a-.example",
            "a_b.example",
            "é.example",
            "a b.example",
            "a\n.example",
            "a\0.example",
            "https://example.com",
            "example.com:443",
            "user@example.com",
            "[::1]",
            "example.com/path",
            "*.example",
            "a;id",
            "$(id)",
            "-oProxyCommand=id",
            &"a".repeat(64),
            &too_long,
        ] {
            for field in ["app.domain", "server.host"] {
                let mut config = parse_foundry_config(&usable_template()).unwrap();
                match field {
                    "app.domain" => config.domain = domain.to_owned(),
                    _ => config.host = domain.to_owned(),
                }
                let error = validate_foundry_config(&config).unwrap_err();
                assert!(
                    matches!(error, FoundryConfigError::Invalid(ref message) if message.starts_with(field)),
                    "{field} accepted or misclassified {domain:?}: {error}",
                );
            }
        }
    }

    #[test]
    fn environment_preserves_toml_scalars_and_rejects_compound_values() {
        let content = format!(
            "{}\nRATIO = 1.25\nCOUNT = 3\nENABLED = false\n",
            usable_template()
        );
        let config = parse_foundry_config(&content).unwrap();
        validate_foundry_config(&config).unwrap();
        for (key, expected) in [("RATIO", "1.25"), ("COUNT", "3"), ("ENABLED", "false")] {
            assert!(
                config
                    .env_vars
                    .contains(&(key.to_owned(), expected.to_owned()))
            );
        }
        for value in ["[1, 2]", "{ nested = 1 }", "2026-09-20"] {
            assert!(matches!(
                parse_foundry_config(&format!("{}\nINVALID = {value}\n", usable_template())),
                Err(FoundryConfigError::Invalid(_)),
            ));
        }
    }

    #[test]
    fn parser_is_section_aware_and_validation_returns_typed_errors() {
        let content = generate_foundry_toml_template("demo").replace(
            "APP_KEY = \"CHANGE_ME_TO_A_SECURE_RANDOM_KEY\"",
            "APP_KEY = \"safe=value with spaces\"",
        );
        let parsed = parse_foundry_config(&content).expect("valid TOML");
        assert_eq!(parsed.app_name, "demo");
        assert!(validate_foundry_config(&parsed).is_ok());

        let invalid = content.replace("port = 3000", "port = 70000");
        let parsed = parse_foundry_config(&invalid).expect("valid TOML shape");
        assert!(matches!(
            validate_foundry_config(&parsed),
            Err(FoundryConfigError::Invalid(_))
        ));
        assert!(parse_foundry_config("[app\nname = 1").is_err());
    }
}
