[package]
name = "rullst-nexus-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"
rullst-nexus = { path = ".." }

[[bin]]
name = "fuzz_nexus_crud"
path = "fuzz_targets/fuzz_nexus_crud.rs"
test = false
doc = false
