[package]
name = "rullst-studio-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"
rullst-studio = { path = ".." }

[[bin]]
name = "fuzz_studio_db"
path = "fuzz_targets/fuzz_studio_db.rs"
test = false
doc = false
