[package]
name = "rullst-nexus"
version = "12.0.0"
edition = "2024"
license = "MIT"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(mutants)', 'cfg(kani)'] }


[features]
default = []
strict-sqlite = ["rullst-core/strict-sqlite", "rullst-orm/strict-sqlite"]
strict-postgres = ["rullst-core/strict-postgres", "rullst-orm/strict-postgres"]
strict-mysql = ["rullst-core/strict-mysql", "rullst-orm/strict-mysql"]

[dependencies]
rullst-core = { version = "12.0.0", path = "../rullst-core" }
rullst-orm = { version = "12.0.0", path = "../rullst-orm" }
rullst-auth = { version = "12.0.0", path = "../rullst-auth" }
rullst-security = { version = "12.0.0", path = "../rullst-security" }
rullst-ai = { version = "12.0.0", path = "../rullst-ai" }
axum = { version = "0.8.9" }
base64 = "0.22.1"
subtle = "2.6.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.44.0", features = ["full"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }

[package.metadata.cargo-machete]
ignored = ["async-trait", "rullst-core", "subtle", "serde", "axum", "serde_json", "tokio", "lettre", "opentelemetry", "opentelemetry-otlp", "opentelemetry_sdk", "redis", "rullst-connect", "rullst-macros", "toml", "tracing-opentelemetry", "urlencoding", "base64", "notify", "ring", "rullst-auth"]
