[default.extend-words]
componente = "componente"
componentes = "componentes"
Braket = "Braket"
inicial = "inicial"
atual = "atual"
Cliente = "Cliente"
Comando = "Comando"
cose = "cose"
COSE = "COSE"
Erro = "Erro"
erros = "erros"
caracteres = "caracteres"
CAF = "CAF"
Operacional = "Operacional"
Monitores = "Monitores"
oficial = "oficial"
