[workspace]
members = [
    "rullst",
    "rullst-macros",
    "cargo-rullst",
    "rullst-orm",
    "rullst-orm-macros",
    "rullst-connect",
    "examples/blog", "rullst-core", "rullst-auth", "rullst-mail", "rullst-ai", "rullst-nexus", "rullst-capital", "rullst-studio", "rullst-security", "rullst-iot",
]
exclude = [
    "benchmark/rullst",
    "benchmark/axum",
    "benchmark/actix",
    "benchmark/loco",

    "benchmark/leptos",
    "benchmark/poem",
    "benchmark/warp",
    "benchmark/dioxus",
]
resolver = "2"

# [patch.crates-io]
# rullst-orm = { path = "../rullst-orm/rullst-orm" }
# rullst-orm-macros = { path = "../rullst-orm/rullst-orm-macros" }

[workspace.metadata.cargo-machete]
ignored = ["async-trait", "rullst-core", "subtle", "serde", "axum", "serde_json", "tokio", "lettre", "opentelemetry", "opentelemetry-otlp", "opentelemetry_sdk", "redis", "rullst-connect", "rullst-macros", "toml", "tracing-opentelemetry", "urlencoding", "base64", "notify", "ring", "rullst-auth"]
