codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

ignore:
  - "examples/**/*"
  - "cargo-rullst/**/*"
  - "rullst-macros/**/*"
  - "rullst-orm-macros/**/*"
  - "benches/**/*"
  - "benchmark/**/*"
  - "target/**/*"
  - "docs/**/*"
  - "**/*_tests.rs"
  - "**/tests/**/*"
