// Generated by Rullst.
pub mod m20260601000000_create_posts_table;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_posts_table::MigrationImpl),
    ]
}
