// src/blueprints/blog.rs — Blog / Content System blueprint templates.

pub fn file_manifest(_project_name_safe: &str) -> Vec<(&'static str, String)> {
    let mut manifest = Vec::new();

    // 1. src/main.rs
    let main_rs = r##"use rullst::{routes, Server};

pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Run migrations on startup
    rullst::artisan!(crate::migrations::get_migrations());

    let router = routes![
        get("/") => controllers::blog_controller::index,
        get("/posts/:slug" => controllers::blog_controller::show),
    ];

    println!("🚀 Blog server starting on port 3000...");
    Server::new(router)
        .run(3000)
        .await?;

    Ok(())
}
"##
    .to_string();
    manifest.push(("src/main.rs", main_rs));

    // 2. Migration
    let migration = r##"use rullst_orm::schema::{Schema, Blueprint, Migration};
use rullst_orm::async_trait;

pub struct MigrationImpl;

#[async_trait]
impl Migration for MigrationImpl {
    fn name(&self) -> &'static str {
        "m20260601000000_create_posts_table"
    }

    async fn up(&self) -> Result<(), rullst_orm::sqlx::Error> {
        Schema::create("posts", |table| {
            table.id();
            table.string("title").not_null();
            table.string("slug").unique().not_null();
            table.text("content").not_null();
            table.timestamps();
        }).await?;

        // Seed initial blog posts
        let pool = rullst_orm::Orm::pool();
        rullst_orm::sqlx::query(
            "INSERT INTO posts (id, title, slug, content, created_at, updated_at) VALUES 
             (1, 'Announcing Rullst: The Ultimate Rust Framework', 'announcing-rullst', 'We are thrilled to announce Rullst, a new full-stack framework combining Axum, HTMX, and SQLite/Postgres for lightning-fast applications.', datetime('now'), datetime('now')),
             (2, 'The Power of WebAssembly Islands', 'power-of-wasm-islands', 'Wasm Islands give you the speed of server-side HTML combined with high-fidelity Wasm interactivity when needed.', datetime('now'), datetime('now'))"
        ).execute(pool).await?;

        Ok(())
    }

    async fn down(&self) -> Result<(), rullst_orm::sqlx::Error> {
        Schema::drop_if_exists("posts").await
    }
}
"##;
    manifest.push((
        "src/migrations/m20260601000000_create_posts_table.rs",
        migration.to_string(),
    ));

    let migrations_mod = r##"// Generated by Rullst.
pub mod m20260601000000_create_posts_table;

pub fn get_migrations() -> Vec<Box<dyn rullst_orm::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_posts_table::MigrationImpl),
    ]
}
"##;
    manifest.push(("src/migrations/mod.rs", migrations_mod.to_string()));

    // 3. Model
    let post_model = r##"use rullst_orm::{Orm, RullstModel, sqlx::{self, FromRow}};

#[derive(Debug, Clone, FromRow, rullst_orm::Orm)]
#[orm(table = "posts")]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub slug: String,
    pub content: String,
}
"##;
    manifest.push(("src/models/post.rs", post_model.to_string()));

    let models_mod = r##"pub mod post;
"##;
    manifest.push(("src/models/mod.rs", models_mod.to_string()));

    // 4. Controller
    let blog_controller = r##"use axum::{extract::Path, response::IntoResponse};
use rullst::response::Html;
use crate::models::post::Post;
use crate::pages::blog;

pub async fn index() -> impl IntoResponse {
    let posts = Post::all().await.unwrap_or_default();
    Html(blog::index_page(posts))
}

pub async fn show(Path(slug): Path<String>) -> impl IntoResponse {
    let posts = Post::all().await.unwrap_or_default();
    let post = posts.into_iter().find(|p| p.slug == slug).unwrap();
    Html(blog::detail_page(post))
}
"##;
    manifest.push((
        "src/controllers/blog_controller.rs",
        blog_controller.to_string(),
    ));

    let controllers_mod = r##"pub mod blog_controller;
"##;
    manifest.push(("src/controllers/mod.rs", controllers_mod.to_string()));

    // 5. Pages
    let blog_page = r##"use rullst::html;
use crate::models::post::Post;

pub fn index_page(posts: Vec<Post>) -> String {
    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <title>"Rullst Press Feed"</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <style>
                    "
                    * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Outfit', sans-serif; }
                    body { background: #030712; color: #f3f4f6; min-height: 100vh; padding: 4rem 2rem; display: flex; flex-direction: column; align-items: center; }
                    .container { max-width: 800px; width: 100%; }
                    header { text-align: center; margin-bottom: 5rem; }
                    h1 { font-size: 3.5rem; font-weight: 800; background: linear-gradient(135deg, #a78bfa, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
                    p.sub { color: #9ca3af; font-size: 1.20rem; margin-top: 0.5rem; }
                    .post-list { display: flex; flex-direction: column; gap: 2.5rem; }
                    .card { background: rgba(17, 24, 39, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 20px; padding: 2.5rem; transition: transform 0.2s, border-color 0.2s; }
                    .card:hover { transform: translateY(-3px); border-color: rgba(167, 139, 250, 0.4); }
                    .card h2 { font-size: 1.75rem; color: #ffffff; margin-bottom: 1rem; }
                    .card p { color: #9ca3af; font-size: 1rem; line-height: 1.7; margin-bottom: 1.5rem; }
                    .read-more { color: #a78bfa; text-decoration: none; font-weight: 600; font-size: 0.95rem; }
                    .read-more:hover { text-decoration: underline; }
                    "
                </style>
            </head>
            <body>
                <div class="container">
                    <header>
                        <h1>"RullstPress Feed"</h1>
                        <p class="sub">"Insights on hyper-performance fullstack development"</p>
                    </header>
                    <div class="post-list">
                        { posts.into_iter().map(|p| html! {
                            <div class="card">
                                <h2>{&p.title}</h2>
                                <p>{&p.content[..100]} "..."</p>
                                <a class="read-more" href={format!("/posts/{}", p.slug)}>"Read full post &rarr;"</a>
                            </div>
                        }).collect::<Vec<_>>().join("") }
                    </div>
                </div>
            </body>
        </html>
    }
}

pub fn detail_page(post: Post) -> String {
    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <title>{&post.title}</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <style>
                    "
                    * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Outfit', sans-serif; }
                    body { background: #030712; color: #f3f4f6; min-height: 100vh; padding: 4rem 2rem; display: flex; flex-direction: column; align-items: center; }
                    .container { max-width: 700px; width: 100%; }
                    .back-link { color: #a78bfa; text-decoration: none; font-weight: 600; margin-bottom: 2rem; display: inline-block; }
                    h1 { font-size: 3rem; font-weight: 800; color: #ffffff; margin-bottom: 2rem; line-height: 1.2; }
                    .content { font-size: 1.15rem; color: #d1d5db; line-height: 1.8; }
                    "
                </style>
            </head>
            <body>
                <div class="container">
                    <a class="back-link" href="/">&larr; " Back to Feed"</a>
                    <h1>{&post.title}</h1>
                    <div class="content">
                        {&post.content}
                    </div>
                </div>
            </body>
        </html>
    }
}
"##;
    manifest.push(("src/pages/blog.rs", blog_page.to_string()));

    let pages_mod = r##"pub mod blog;
"##;
    manifest.push(("src/pages/mod.rs", pages_mod.to_string()));

    manifest
}
