pub const FLY_TOML: &str = r#"# fly.toml app configuration file generated by Rullst Framework
app = "APP_NAME"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  RUST_LOG = "info,rullst=debug"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/ready"
    protocol = "http"
"#;

pub const RAILWAY_JSON: &str = r#"{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "Dockerfile"
  },
  "deploy": {
    "startCommand": "./APP_NAME",
    "healthcheckPath": "/health",
    "healthcheckTimeout": 10,
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 5
  }
}
"#;

pub const RENDER_YAML: &str = r#"services:
  - type: web
    name: APP_NAME
    env: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: RUST_LOG
        value: info,rullst=debug
"#;

/// Address the generated Caddy proxy holds on the compose `edge` network.
/// `deploy --platform vps` lists it in `Rullst.toml` `[security]
/// trusted_proxies`, so the app reads each client from `X-Forwarded-For`
/// instead of seeing every request come from Caddy.
pub const VPS_PROXY_ADDRESS: &str = "172.31.250.10";

pub const DOCKER_COMPOSE_PROD: &str = r#"version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=3000
      - RUST_LOG=info,rullst=debug
    expose:
      - "3000"
    networks:
      - edge

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      edge:
        # Rullst.toml [security] trusted_proxies trusts only this address to
        # report the client address. Change both together.
        ipv4_address: 172.31.250.10
    depends_on:
      - app

networks:
  edge:
    ipam:
      config:
        # Pinned so the proxy address is known. If it overlaps a network on
        # this host, choose another private /24 and update the address above.
        - subnet: 172.31.250.0/24

volumes:
  caddy_data:
  caddy_config:
"#;

/// Caddy (2.5+) replaces a client-supplied `X-Forwarded-For` with the address
/// it received the request from, which the app trusts from this proxy only.
pub const CADDYFILE: &str = r#"{$DOMAIN:localhost} {
    reverse_proxy app:3000
}
"#;
