// src/blueprints/erp.rs — ERP Pocket blueprint templates.

pub fn file_manifest(project_name_safe: &str, hot_reload: bool) -> Vec<(&'static str, String)> {
    let mut manifest = Vec::new();

    if hot_reload {
        let lib_rs = r##"use rullst::{routes, Router};

pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[unsafe(no_mangle)]
pub extern "C" fn rullst_router_init() -> *mut Router {
    let nexus = rullst::nexus::Nexus::new()
        .with_brand("ERP Admin")
        .register::<models::product::Product>()
        .register::<models::order::Order>()
        .build();

    let router = routes![
        get("/" => controllers::erp_controller::index),
        post("/products" => controllers::erp_controller::store_product),
        post("/products/{id}/add-stock" => controllers::erp_controller::add_stock),
        post("/orders" => controllers::erp_controller::store_order),
    ].nest_axum("/nexus", nexus);
    Box::into_raw(Box::new(router))
}
"##
        .to_string();
        manifest.push(("src/lib.rs", lib_rs));

        let main_rs = format!(
            r##"pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[rullst::runtime::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {{
    rullst::artisan!(crate::migrations::get_migrations());
    rullst::runtime::spawn(async {{ let _ = rullst::studio::run_studio("").await; }});
    println!("📊 Rullst Studio running on http://127.0.0.1:5555");
    println!("🚀 ERP Pocket server starting on port 3000...");
    let is_hot = std::env::var("HOT_RELOAD").is_ok();

    let server = if is_hot {{
        let lib_path = if cfg!(target_os = "windows") {{
            format!("target/debug/{{}}", "{project_name_safe}")
        }} else {{
            format!("target/debug/lib{{}}", "{project_name_safe}")
        }};
        rullst::Server::new_hot(&lib_path)
    }} else {{
        let router_ptr = {project_name_safe}::rullst_router_init();
        let router = unsafe {{ *Box::from_raw(router_ptr) }};
        rullst::Server::new(router)
    }};

    server.run(3000).await?;

    Ok(())
}}
"##,
            project_name_safe = project_name_safe
        );
        manifest.push(("src/main.rs", main_rs));
    } else {
        let main_rs = r##"use rullst::{routes, Server};

pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[rullst::runtime::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Run migrations on startup
    rullst::artisan!(crate::migrations::get_migrations());

    let nexus = rullst::nexus::Nexus::new()
        .with_brand("ERP Admin")
        .register::<models::product::Product>()
        .register::<models::order::Order>()
        .build();

    let router = routes![
        get("/" => controllers::erp_controller::index),
        post("/products" => controllers::erp_controller::store_product),
        post("/products/{id}/add-stock" => controllers::erp_controller::add_stock),
        post("/orders" => controllers::erp_controller::store_order),
    ].nest_axum("/nexus", nexus);

    rullst::runtime::spawn(async { let _ = rullst::studio::run_studio("").await; });
    println!("📊 Rullst Studio running on http://127.0.0.1:5555");
    println!("🚀 ERP Pocket server starting on port 3000...");
    Server::new(router)
        .run(3000)
        .await?;

    Ok(())
}
"##
        .to_string();
        manifest.push(("src/main.rs", main_rs));
    }

    // 2. Migrations mod.rs
    let migrations_mod = r##"// Generated by Rullst.
pub mod m20260601000000_create_erp_tables;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_erp_tables::MigrationImpl),
    ]
}
"##;
    manifest.push(("src/migrations/mod.rs", migrations_mod.to_string()));

    // 3. Migration Implementation
    let migration_impl = r##"use rullst::db::schema::{Schema, Migration};
use rullst::db::async_trait;

pub struct MigrationImpl;

#[async_trait]
impl Migration for MigrationImpl {
    fn name(&self) -> &'static str {
        "m20260601000000_create_erp_tables"
    }

    async fn up(&self) -> Result<(), rullst_orm::error::RullstError> {
        // Create products table
        Schema::create("products", |table| {
            table.id();
            table.string("name").not_null();
            table.string("sku").not_null();
            table.float("price").not_null();
            table.integer("stock").not_null();
            table.timestamps();
        }).await?;

        // Create orders table
        Schema::create("orders", |table| {
            table.id();
            table.string("customer_name").not_null();
            table.integer("product_id").not_null();
            table.integer("quantity").not_null();
            table.float("total_price").not_null();
            table.string("status").not_null();
            table.timestamps();
        }).await?;

        // Seed initial products and orders
        let pool = rullst::db::Orm::pool();
        
        rullst::db::sqlx::query(
            "INSERT INTO products (id, name, sku, price, stock, created_at, updated_at) VALUES 
             (1, 'Café Arábica Especial', 'CAF-001', 34.90, 18, datetime('now'), datetime('now')),
             (2, 'Caneca Cerâmica Rullst', 'CAN-002', 19.90, 4, datetime('now'), datetime('now')),
             (3, 'Prensa Francesa', 'PRE-003', 89.00, 12, datetime('now'), datetime('now'))"
        ).execute(pool).await?;

        rullst::db::sqlx::query(
            "INSERT INTO orders (id, customer_name, product_id, quantity, total_price, status, created_at, updated_at) VALUES 
             (1, 'Carlos Silva', 1, 2, 69.80, 'Pago', datetime('now'), datetime('now')),
             (2, 'Mariana Souza', 2, 1, 19.90, 'Pendente', datetime('now'), datetime('now'))"
        ).execute(pool).await?;

        Ok(())
    }

    async fn down(&self) -> Result<(), rullst_orm::error::RullstError> {
        Schema::drop_if_exists("orders").await?;
        Schema::drop_if_exists("products").await?;
        Ok(())
    }
}
"##;
    manifest.push((
        "src/migrations/m20260601000000_create_erp_tables.rs",
        migration_impl.to_string(),
    ));

    // 4. Models mod.rs
    let models_mod = r##"pub mod product;
pub mod order;
"##;
    manifest.push(("src/models/mod.rs", models_mod.to_string()));

    // 5. Product Model
    let product_model = r##"use rullst::db::{Orm, FromRow};
use rullst::nexus::{NexusModel, FieldMeta, FieldKind};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "products")]
pub struct Product {
    pub id: i32,
    pub name: String,
    pub sku: String,
    pub price: f64,
    pub stock: i32,
}

impl NexusModel for Product {
    fn nexus_table() -> &'static str { "products" }
    fn nexus_label() -> &'static str { "Products" }
    fn nexus_icon() -> &'static str { "📦" }
    fn nexus_fields() -> Vec<FieldMeta> {
        vec![
            FieldMeta { name: "id", label: "ID", kind: FieldKind::Number, hidden: true, readonly: true },
            FieldMeta { name: "name", label: "Name", kind: FieldKind::Text, hidden: false, readonly: false },
            FieldMeta { name: "sku", label: "SKU", kind: FieldKind::Text, hidden: false, readonly: false },
            FieldMeta { name: "price", label: "Price", kind: FieldKind::Number, hidden: false, readonly: false },
            FieldMeta { name: "stock", label: "Stock", kind: FieldKind::Number, hidden: false, readonly: false },
        ]
    }
}
"##;
    manifest.push(("src/models/product.rs", product_model.to_string()));

    // 6. Order Model
    let order_model = r##"use rullst::db::{Orm, FromRow};
use rullst::nexus::{NexusModel, FieldMeta, FieldKind};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "orders")]
pub struct Order {
    pub id: i32,
    pub customer_name: String,
    pub product_id: i32,
    pub quantity: i32,
    pub total_price: f64,
    pub status: String,
}

impl NexusModel for Order {
    fn nexus_table() -> &'static str { "orders" }
    fn nexus_label() -> &'static str { "Orders" }
    fn nexus_icon() -> &'static str { "🛒" }
    fn nexus_fields() -> Vec<FieldMeta> {
        vec![
            FieldMeta { name: "id", label: "ID", kind: FieldKind::Number, hidden: true, readonly: true },
            FieldMeta { name: "customer_name", label: "Customer Name", kind: FieldKind::Text, hidden: false, readonly: false },
            FieldMeta { name: "product_id", label: "Product ID", kind: FieldKind::Number, hidden: false, readonly: false },
            FieldMeta { name: "quantity", label: "Quantity", kind: FieldKind::Number, hidden: false, readonly: false },
            FieldMeta { name: "total_price", label: "Total Price", kind: FieldKind::Number, hidden: false, readonly: false },
            FieldMeta { name: "status", label: "Status", kind: FieldKind::Text, hidden: false, readonly: false },
        ]
    }
}
"##;
    manifest.push(("src/models/order.rs", order_model.to_string()));

    // 7. Controllers mod.rs
    let controllers_mod = r##"pub mod erp_controller;
"##;
    manifest.push(("src/controllers/mod.rs", controllers_mod.to_string()));

    // 8. ERP Controller
    let erp_controller = r##"use rullst::server::{
    Path,
    IntoResponse, Redirect,
    Form
};
use rullst::response::Html;
use crate::models::product::Product;
use crate::models::order::Order;
use crate::pages::erp;
use serde::Deserialize;

pub async fn index() -> impl IntoResponse {
    let products = Product::all().await.unwrap_or_default();
    let orders = Order::all().await.unwrap_or_default();
    Html(erp::dashboard_page(products, orders))
}

#[derive(Deserialize)]
pub struct CreateProductPayload {
    pub name: String,
    pub sku: String,
    pub price: f64,
    pub stock: i32,
}

pub async fn store_product(Form(payload): Form<CreateProductPayload>) -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();
    let _ = rullst::db::sqlx::query(
        "INSERT INTO products (name, sku, price, stock, created_at, updated_at) VALUES ($1, $2, $3, $4, datetime('now'), datetime('now'))"
    )
    .bind(payload.name)
    .bind(payload.sku)
    .bind(payload.price)
    .bind(payload.stock)
    .execute(pool)
    .await;

    Redirect::to("/")
}

pub async fn add_stock(Path(id): Path<i32>) -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();
    
    // Increment stock
    let _ = rullst::db::sqlx::query(
        "UPDATE products SET stock = stock + 1, updated_at = datetime('now') WHERE id = $1"
    )
    .bind(id)
    .execute(pool)
    .await;

    // Get current stock
    let row: (i32,) = rullst::db::sqlx::query_as("SELECT stock FROM products WHERE id = $1")
        .bind(id)
        .fetch_one(pool)
        .await
        .unwrap_or((0,));

    let stock = row.0;
    
    // Render only the updated stock badge with HTMX
    let badge_color = if stock <= 5 { "text-rose-400 bg-rose-950/40" } else { "text-emerald-400 bg-emerald-950/40" };
    Html(format!(
        r#"<span id="stock-badge-{}" class="px-2.5 py-1 text-xs font-semibold rounded-full {}">{} Un.</span>"#,
        id, badge_color, stock
    ))
}

#[derive(Deserialize)]
pub struct CreateOrderPayload {
    pub customer_name: String,
    pub product_id: i32,
    pub quantity: i32,
}

pub async fn store_order(Form(payload): Form<CreateOrderPayload>) -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();

    // Get product price and stock
    let product_row: Result<(f64, i32), _> = rullst::db::sqlx::query_as(
        "SELECT price, stock FROM products WHERE id = $1"
    )
    .bind(payload.product_id)
    .fetch_one(pool)
    .await;

    if let Ok((price, stock)) = product_row {
        if stock >= payload.quantity {
            // Deduct stock and save order in sequential steps
            let _ = rullst::db::sqlx::query(
                "UPDATE products SET stock = stock - $1, updated_at = datetime('now') WHERE id = $2"
            )
            .bind(payload.quantity)
            .bind(payload.product_id)
            .execute(pool)
            .await;

            let total_price = price * (payload.quantity as f64);

            let _ = rullst::db::sqlx::query(
                "INSERT INTO orders (customer_name, product_id, quantity, total_price, status, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, datetime('now'), datetime('now'))"
            )
            .bind(payload.customer_name)
            .bind(payload.product_id)
            .bind(payload.quantity)
            .bind(total_price)
            .bind("Pago")
            .execute(pool)
            .await;
        }
    }

    // Redirect to main page to refresh dashboard state
    Redirect::to("/")
}
"##;
    manifest.push((
        "src/controllers/erp_controller.rs",
        erp_controller.to_string(),
    ));

    // 9. Pages mod.rs
    let pages_mod = r##"pub mod erp;
"##;
    manifest.push(("src/pages/mod.rs", pages_mod.to_string()));

    // 10. ERP Page View
    let erp_page = r##"use rullst::html;
use crate::models::product::Product;
use crate::models::order::Order;

pub fn dashboard_page(products: Vec<Product>, orders: Vec<Order>) -> String {
    // Calculadoras
    let total_sales: f64 = orders.iter()
        .filter(|o| o.status == "Pago")
        .map(|o| o.total_price)
        .sum();

    let low_stock_alerts = products.iter()
        .filter(|p| p.stock <= 5)
        .count();

    let total_orders = orders.len();

    html! {
        <html lang="pt-BR" class="dark">
            <head>
            <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAKyklEQVR4nK1XaXBUVRo9977X3ekl6U7SSWhICJiwCwiDQIJDgIjAoIJhGnDUkkFEUKcUgXFjDBGZ0gFRcUOHURHUkQgiI2oQZZNtgASyErJ1EiBL70mvb7tT3TQUEZeqKb8/79at9+4571vO913gJ4xZwbE88HkAvz8PfGQdfRaCMoDgNzTSAxggsQ32Sx8xgCIPFKlgGApGiqLv/+I3P2f8j8Cjh7DFyHfYMfj5MuQ+kYtAcjMa/ECV34RzW19CM7kRAg5C6UHKCg6dIMWpYNZiKFfO+jUjV8Cj6+3QVGzGttJGFJi1gN4AnExUYeXkOOBIN8QARCWEVllGjSKj1M+jtNOI8hFfwgbyI0KFoBgGMrcYgNWK4rnF8s8TsIIjxZAbZ2LDN8ewrMyFsAyQuYNBTlCCCSsHIN/YSlmHxJEgD3gY4FSiT9GrhMUQGsSwXBqWcMwj4PRZ4Nzc0/D2IMQYIRE40tMz5Irr2etI/u4tNB2vhS7TBAgCqI4S6PoxNAyLx7IcEeFOERqTrEBPGbQqyN1hwnzgeCFylApwS4CXIdBN2yAp1c4k7Jw0LNM2YHSiUDL5zL5YrMm1JHhYQVEMGV8jO9yB+JQ+kO+KB21toSwkMhIQgOqybgW1AFpBy9R6auaDCNIwti98FxkWneJ2tLFFh1cyJREIxVOamq5YYCAW3QBV/rOC/ckDhjELlznTLpQeKZ9/EG3OwkLQoqLLIeOLIzEC4KiFpASAVg6EDqRQVSuEEaAzQEAlyjk6Cbal38F0SxfDXt2E6kbGnpsMNqhxPTuZuxaF+1+kA1KTiL5/OjNuWavcwo7RpAkMC/sHxq71yov+Oib9MJ/j//jA6sXTV68GUFTUMwQNN8BY20Ea9/mZccr0ROSk51KpokZ5pcbGDQ8r5XW5S47euih/yYQDK2T3zVYmGM18Wus6IOgEzP1Rl7kcyZ46Mal9P/9Jr/V+10NPPjxfKvNJd3Ndvd6TDyV9ZamjSXymbAtNd8+3l2A7OMyFHE3C7QA3F5AP6LHGFsIqFyAlZfellxwe2FyhsG30o7P2rn+5pqLh/YYbX1+oRhogaOH2puGMkqRyqoloTvRgNPxIiJx3bPbXTbnHW9ci7ch86L7iqFFOzLbobrhYH4z3+6R3sMy7FIXgUQQpqgNWQImKy2A831qBvjOzcY9ysYW5vCBsygLVvKW37VzZuNs3sORDtRdc2C/JK3K/wOZmIASIUVe+ARjm5WOpiacvjjj6cr//jP7L5oyE+zC1MgB7y2dw+XiFtgiEBFn/WOkr1ythISgpguK9n3yXUIUpZy+acWH5K5j56SMIXBDhCAY8fWWMe/h9Nru39uIUwoIqSihTwGSIBsEZl7Z7SSHvzOLk7ZwWBGaTvHHa26rHdj/MVOagJLsVHjr6lbI1dDsiwlUM+aoSxiyi9cw3ROtDc0CxJadfSj27xdxS6XXbLaiqTIrfumBOVk7q3qUTJZ2Qr0n00DheQwkTIRiCmGR64PanX5OmbLyXf8mswjMqoQuZTaUe0m7mZE+dVnHzBKnkTBSp8/LP8z3ge4MgD5zKyGlg4Oik6rKOLw9jRcoIMt6SDq/OHOxjbPKfHDtyoilezmx12ut37V1/fyGA4ViQ8v2p4elcwfm7BsTXyxvO9+ae0vJ8YM22fy1mzLUBIRIPleJHL25z1PMxKac9VOkhiOQgpHBDoCnoVc56U7BnxgBugkliCfIJaEyHJaH7o459AwZOyTqR4eo/ZMKMnH8fZLmPbjlXCD84jVvNCxSmDYC3QSKB6hahU6O49OgmFjDODj0pQEnYFgv9ZR1ArLsRQGmfghG6NNwSbJbLAzrUBMKkoKFFJk4B69ITiNnpYIeUv3l5v78m3Nh+hNm6u35Xb2z/prRjB8Zn/FEelb6wsrGp+vgXgPRaRuIM32l7xdE+mAoj4dgA7SXs6N4b++mrfYO/1gOuEPRiCKaKKjxICRX7ZihVdf3uGlTQfPgFkuw0iCl4HEV8o+rDMwLvspGWRg9fG9qvBBJqxZwRCzTmpJv2vL2EHOr9+ZwVa5SqG/QF2asN+aerg1TZQgirlQmJ9IQeTYvGSiG6OfQojmV8jr9bAjg5sB/pdeosxhjGz+sw99aPTAbLUlk0N7PCVZQSqpIaKuVBY/ICj0wtRnJouGbnkcVCZfPbK5Z83PHIJY9J4zsvNrS/UP8FP8HwXMIkE0w3azNNa5M/Mq0xZV7tCbgmB6JTUCGoowCPyUMwveIc4sfFwdDdbrdhxjxAn4yswdp8UlSkJFLdqZkjnuLc3VxI4Ib/Yd64D1qG9b5XXVpVwmmC9jemqu7UiuAGhVtFm7ct5HXX+ryOo/a17h8cyz27PJdifZj1CEGkJ8wlUN7tD2LRIn5miiJyBphav3sz6bnRX26dMTHrjnGNT+c4d/V9MHn2IOuCTZ2rUjTuP+/gc6WMhFv/OdO8JcPrs/OgaiXUdjBJ6L7QkKzK2OrSXlxBddwkno/Ti895FrHL3fCq8VcWVbEJ5lwjduSOwTrOwDivBu4s5/n9t87PfjX4XvU/ckK3rDC8vPsd330Yon/L9CKZMGp3Ypb/iS7jpuCxuHWCgWklX0e3moTVowymuD5+eqmNnQsPYvFklKDh1FE8AunalkyvEFgdIzAkAf4uLzwNbtAAQ7i3iSsIWvg9Ts8lR7t5MPG1pBGu74PL/IMGduzdV/aM23ahyXnaF5ArNUnuWuEmsVzjCK+jd/q2uR6X/husN8TRmng/caUZNOaxO7LWz3o/0xQFj+UA6SHFAKEA22PBid+nY6zGEB0zABtBp5ttWvXo9pYJmfzdR4TMnbdVfzun15vPhqtN/AcbZyee8CYI41JS1OWCjvVmOqW/Ko4fRBQyLT41Lk0fr1NUajVJSjPSbCnt2KGS6ntcGtWF0w+dFnsQ2A/wkwFphw7rp47CciJC0CWBC1UCJym4rhQc36yhYVZwk10/ON1S391CKfEbBLVglJlsEpmcIMlK1K8c4cBJPOQgYcGggoAgoasrKFmyjKr+SYbpB2ZUlVi3W7keOmCPFYcjgI/Pu7A8kwPXTkE/9ABmE5Er2uj4Py1V46RHgG5EClzkHHx2Gb52CV0dInydEgt6ZVn0yExxSYBPJgjKDGHlcqGHIDen+1TNIxMM0cSvKr5yDegRhqgqfmrErol9MKtDIuLGDsYv1AFNbVA+7cuxaTkyPhkxkHRnh0ndDy6EHPLlebBbVuBTGEKMQiEcoRSE48AiJ3IETE1A0ng7y9aMxKuO9uub0eVkjObCKi8ek7RkYp6OGScaibzFQ7g5KYx2OsGkk4SUd9qI7wxhqBJkIjJAJjx4NWUqFaCJZBKNzM51DKQWDDZIzAEjRKbmv8WrjrZY/rHrCBQBSrUVXPFnaL7d0u/+OjGwO6erg/ICE+7uAtFmpaK9tQ2CnqPEyzgmanmmi4sUlADKnQJjeyHjB/hQiabODvy0RcGvq4JrbbvVys3d8Zk8+4kHZhlq6zfpu7y96qEB19KCrs4OHJ9mAXUq3YrMHYXE9iCglKD80vnrgCJTd6z3R20SFMQm4l8kEDErwBUD8pJ1y1NtFRfvaSs7MU6sadLXDNXZ6FDzQblTOYbvL1zsAZgHLnpnLI6C/F/3RfQgYbVyv/JK5KIaCWWP2eK3NlJYWMjn5eXxEa9EAX8j0P8Bv4YQA2m92wMAAAAASUVORK5CYII=" />
                <meta charset="UTF-8" />
                <title>"Rullst ERP Pocket — Painel de Estoque"</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <script src="https://unpkg.com/htmx.org@1.9.10"></script>
                <script src="https://cdn.tailwindcss.com"></script>
                <style>
                    "
                    body { font-family: 'Outfit', sans-serif; background-color: #050811; }
                    .glass { background: rgba(10, 18, 36, 0.6); backdrop-filter: blur(16px); border: 1px solid rgba(255, 255, 255, 0.05); }
                    .glass-accent { border: 1px solid rgba(167, 139, 250, 0.2); }
                    "
                </style>
            </head>
            <body class="text-slate-100 min-height-screen pb-12">
                <div class="max-w-6xl mx-auto px-4 pt-8">
                    
                    // --- Header ---
                    <header class="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 mb-10 pb-6 border-b border-slate-800/40">
                        <div>
                            <span class="px-3 py-1 text-xs font-semibold text-orange-400 bg-orange-950/40 rounded-full border border-orange-800/40">"ERP Pocket"</span>
                            <h1 class="text-3xl font-extrabold tracking-tight mt-2 bg-gradient-to-r from-emerald-400 via-teal-300 to-orange-400 bg-clip-text text-transparent">"Rullst ERP & Stock Portal"</h1>
                            <p class="text-sm text-slate-400 mt-1">"Gerenciamento ágil de inventário e vendas em tempo de execução."</p>
                        </div>
                        <div class="flex gap-3">
                            <a href="/nexus" class="glass px-4 py-2 text-sm font-semibold rounded-lg hover:border-orange-500/50 hover:bg-slate-900/40 transition-all">"⚙️ Nexus CMS"</a>
                            <a href="http://localhost:5555" target="_blank" class="glass px-4 py-2 text-sm font-semibold rounded-lg hover:border-orange-500/50 hover:bg-slate-900/40 transition-all">"📊 Rullst Studio"</a>
                        </div>
                    </header>

                    // --- KPI Cards ---
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Faturamento Total"</span>
                            <span class="text-3xl font-bold mt-2 text-emerald-400">"R$ "{format!("{:.2}", total_sales)}</span>
                            <span class="text-xs text-emerald-500/80 mt-1">"&uarr; Receitas confirmadas"</span>
                        </div>
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Pedidos Realizados"</span>
                            <span class="text-3xl font-bold mt-2 text-orange-400">{format!("{}", total_orders)}</span>
                            <span class="text-xs text-orange-400/80 mt-1">"Fluxo de vendas ativo"</span>
                        </div>
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Alertas de Estoque Crítico"</span>
                            <span class="text-3xl font-bold mt-2 text-rose-400">{format!("{}", low_stock_alerts)}</span>
                            <span class="text-xs text-rose-400/80 mt-1">"Itens com estoque &le; 5 un."</span>
                        </div>
                    </div>

                    // --- Main Panels ---
                    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        
                        // --- Coluna Esquerda: Produtos & Reabastecimento ---
                        <div class="lg:col-span-2 flex flex-col gap-8">
                            <div class="glass p-6 rounded-2xl">
                                <h2 class="text-xl font-bold mb-4 text-slate-200">"Estoque de Produtos"</h2>
                                <div class="overflow-x-auto">
                                    <table class="w-full text-left border-collapse">
                                        <thead>
                                            <tr class="border-b border-slate-800 text-xs font-semibold text-slate-400 uppercase">
                                                <th class="py-3 px-4">"Produto"</th>
                                                <th class="py-3 px-4">"SKU"</th>
                                                <th class="py-3 px-4">"Preço"</th>
                                                <th class="py-3 px-4">"Estoque"</th>
                                                <th class="py-3 px-4 text-right">"Ações"</th>
                                            </tr>
                                        </thead>
                                        <tbody class="divide-y divide-slate-800/40 text-sm">
                                            { rullst::html::RawHtml::new(products.iter().map(|p| {
                                                let badge_color = if p.stock <= 5 { "text-rose-400 bg-rose-950/40" } else { "text-emerald-400 bg-emerald-950/40" };
                                                html! {
                                                    <tr>
                                                        <td class="py-3.5 px-4 font-medium text-white">{&p.name}</td>
                                                        <td class="py-3.5 px-4 text-slate-400 font-mono">{&p.sku}</td>
                                                        <td class="py-3.5 px-4 text-slate-300">"R$ "{format!("{:.2}", p.price)}</td>
                                                        <td class="py-3.5 px-4">
                                                            <span id={format!("stock-badge-{}", p.id)} class={format!("px-2.5 py-1 text-xs font-semibold rounded-full {}", badge_color)}>
                                                                {format!("{}", p.stock)} " Un."
                                                            </span>
                                                        </td>
                                                        <td class="py-3.5 px-4 text-right">
                                                            <button 
                                                                hx-post={format!("/products/{}/add-stock", p.id)}
                                                                hx-target={format!("#stock-badge-{}", p.id)}
                                                                hx-swap="outerHTML"
                                                                class="px-2.5 py-1 text-xs font-bold text-orange-400 border border-orange-500/20 hover:border-orange-400 bg-orange-950/20 rounded-md transition-all active:scale-95"
                                                            >
                                                                "+1 Estoque"
                                                            </button>
                                                        </td>
                                                    </tr>
                                                }
                                            }).collect::<Vec<_>>().join("")) }
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            // --- Pedidos Recentes ---
                            <div class="glass p-6 rounded-2xl">
                                <h2 class="text-xl font-bold mb-4 text-slate-200">"Pedidos Recentes"</h2>
                                <div class="overflow-x-auto">
                                    <table class="w-full text-left border-collapse">
                                        <thead>
                                            <tr class="border-b border-slate-800 text-xs font-semibold text-slate-400 uppercase">
                                                <th class="py-3 px-4">"ID"</th>
                                                <th class="py-3 px-4">"Cliente"</th>
                                                <th class="py-3 px-4">"Qtd / Prod ID"</th>
                                                <th class="py-3 px-4">"Total"</th>
                                                <th class="py-3 px-4">"Status"</th>
                                            </tr>
                                        </thead>
                                        <tbody class="divide-y divide-slate-800/40 text-sm">
                                            { rullst::html::RawHtml::new(orders.iter().map(|o| html! {
                                                <tr>
                                                    <td class="py-3.5 px-4 text-slate-400 font-mono">"#{}"{format!("{}", o.id)}</td>
                                                    <td class="py-3.5 px-4 font-medium text-white">{&o.customer_name}</td>
                                                    <td class="py-3.5 px-4 text-slate-400">{format!("{} un. (Ref: Product #{})", o.quantity, o.product_id)}</td>
                                                    <td class="py-3.5 px-4 text-emerald-400 font-medium">"R$ "{format!("{:.2}", o.total_price)}</td>
                                                    <td class="py-3.5 px-4">
                                                        <span class="px-2 py-0.5 text-xs font-semibold rounded bg-emerald-950/60 text-emerald-400 border border-emerald-900/60">
                                                            {&o.status}
                                                        </span>
                                                    </td>
                                                </tr>
                                            }).collect::<Vec<_>>().join("")) }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        // --- Coluna Direita: Cadastro & Operações ---
                        <div class="flex flex-col gap-8">
                            
                            // --- Nova Venda / Pedido ---
                            <div class="glass p-6 rounded-2xl border border-indigo-900/20">
                                <h3 class="text-lg font-bold mb-4 text-indigo-400">"Registrar Nova Venda"</h3>
                                <form action="/orders" method="POST" class="space-y-4">
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Nome do Cliente"</label>
                                        <input type="text" name="customer_name" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500 text-slate-200" placeholder="Ex: João Silva" />
                                    </div>
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Selecionar Produto"</label>
                                        <select name="product_id" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500 text-slate-200">
                                            // Usamos os produtos mapeados
                                            // Nota: no formulário passamos apenas a lista simples para seleção
                                            { rullst::html::RawHtml::new(products.iter().map(|p| {
                                                let disabled_flag = if p.stock <= 0 { " (Sem Estoque)" } else { "" };
                                                html! {
                                                    <option value={format!("{}", p.id)}>{&p.name} " - R$ "{format!("{:.2}", p.price)}{disabled_flag}</option>
                                                }
                                            }).collect::<Vec<_>>().join("")) }
                                        </select>
                                    </div>
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Quantidade"</label>
                                        <input type="number" name="quantity" min="1" value="1" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500 text-slate-200" />
                                    </div>
                                    <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-2 rounded-lg text-sm transition-all active:scale-98">
                                        "Finalizar Pedido"
                                    </button>
                                </form>
                            </div>

                            // --- Novo Produto ---
                            <div class="glass p-6 rounded-2xl">
                                <h3 class="text-lg font-bold mb-4 text-slate-200">"Cadastrar Produto"</h3>
                                <form action="/products" method="POST" class="space-y-4">
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Nome do Produto"</label>
                                        <input type="text" name="name" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500 text-slate-200" placeholder="Ex: Filtro Hario V60" />
                                    </div>
                                    <div class="grid grid-cols-2 gap-4">
                                        <div>
                                            <label class="block text-xs text-slate-400 font-medium mb-1">"SKU"</label>
                                            <input type="text" name="sku" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500 text-slate-200" placeholder="HAR-100" />
                                        </div>
                                        <div>
                                            <label class="block text-xs text-slate-400 font-medium mb-1">"Preço Unitário"</label>
                                            <input type="number" step="0.01" name="price" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500 text-slate-200" placeholder="49.90" />
                                        </div>
                                    </div>
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Estoque Inicial"</label>
                                        <input type="number" name="stock" required="true" class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500 text-slate-200" placeholder="10" />
                                    </div>
                                    <button type="submit" class="w-full bg-purple-600 hover:bg-purple-500 text-white font-bold py-2 rounded-lg text-sm transition-all active:scale-98">
                                        "Salvar Produto"
                                    </button>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </body>
        </html>
    }
}
"##;
    manifest.push(("src/pages/erp.rs", erp_page.to_string()));

    manifest
}
