// src/blueprints/lms.rs — LMS Course Platform blueprint templates.

pub fn file_manifest(_project_name_safe: &str) -> Vec<(&'static str, String)> {
    let mut manifest = Vec::new();

    // 1. main.rs
    let main_rs = r##"use rullst::{routes, Server};

pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[rullst::runtime::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Run migrations on startup
    rullst::artisan!(crate::migrations::get_migrations());

    let router = routes![
        get("/" => controllers::lms_controller::index),
        get("/courses/:id" => controllers::lms_controller::show_course),
        get("/lessons/:id/play" => controllers::lms_controller::play_lesson),
    ];

    println!("🚀 LMS server starting on port 3000...");
    Server::new(router)
        .run(3000)
        .await?;

    Ok(())
}
"##
    .to_string();
    manifest.push(("src/main.rs", main_rs));

    // 2. Migration
    let migration = r##"use rullst::db::schema::{Schema, Blueprint, Migration};
use rullst::db::async_trait;

pub struct MigrationImpl;

#[async_trait]
impl Migration for MigrationImpl {
    fn name(&self) -> &'static str {
        "m20260601000000_create_lms_tables"
    }

    async fn up(&self) -> Result<(), rullst_orm::error::RullstError> {
        // Create courses table
        Schema::create("courses", |table| {
            table.id();
            table.string("title").not_null();
            table.string("description").not_null();
            table.string("thumbnail").not_null();
            table.timestamps();
        }).await?;

        // Create lessons table
        Schema::create("lessons", |table| {
            table.id();
            table.integer("course_id").not_null();
            table.string("title").not_null();
            table.string("video_url").not_null();
            table.integer("duration").not_null(); // in minutes
            table.timestamps();
        }).await?;

        // Seed initial data
        let pool = rullst::db::Orm::pool();

        // Seed Courses
        rullst::db::sqlx::query(
            "INSERT INTO courses (id, title, description, thumbnail, created_at, updated_at) VALUES 
             (1, 'Rust Advanced Systems Programming', 'Master threads, concurrency, async, and high-performance design.', 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=300', datetime('now'), datetime('now')),
             (2, 'Zero to Hero: Web Apps with Rullst', 'Build clean, high-performance web applications using Rust.', 'https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=300')"
        ).execute(pool).await?;

        // Seed Lessons
        rullst::db::sqlx::query(
            "INSERT INTO lessons (id, course_id, title, video_url, duration, created_at, updated_at) VALUES 
             (1, 1, 'Introduction to Memory Safety', 'https://www.w3schools.com/html/mov_bbb.mp4', 15, datetime('now'), datetime('now')),
             (2, 1, 'Deep Dive into Smart Pointers', 'https://media.w3.org/2010/05/sintel/trailer.mp4', 25, datetime('now'), datetime('now')),
             (3, 2, 'Setting up your first Rullst Project', 'https://www.w3schools.com/html/mov_bbb.mp4', 10, datetime('now'), datetime('now')),
             (4, 2, 'Building Interactive UIs with HTMX', 'https://media.w3.org/2010/05/sintel/trailer.mp4', 20, datetime('now'), datetime('now'))"
        ).execute(pool).await?;

        Ok(())
    }

    async fn down(&self) -> Result<(), rullst_orm::error::RullstError> {
        Schema::drop_if_exists("lessons").await?;
        Schema::drop_if_exists("courses").await?;
        Ok(())
    }
}
"##;
    manifest.push((
        "src/migrations/m20260601000000_create_lms_tables.rs",
        migration.to_string(),
    ));

    let migrations_mod = r##"// Generated by Rullst.
pub mod m20260601000000_create_lms_tables;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_lms_tables::MigrationImpl),
    ]
}
"##;
    manifest.push(("src/migrations/mod.rs", migrations_mod.to_string()));

    // 3. Models
    let course_model = r##"use rullst::db::{Orm, RullstModel, FromRow, sqlx};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "courses")]
pub struct Course {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub thumbnail: String,
}
"##;
    manifest.push(("src/models/course.rs", course_model.to_string()));

    let lesson_model = r##"use rullst::db::{Orm, RullstModel, FromRow, sqlx};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "lessons")]
pub struct Lesson {
    pub id: i32,
    pub course_id: i32,
    pub title: String,
    pub video_url: String,
    pub duration: i32,
}
"##;
    manifest.push(("src/models/lesson.rs", lesson_model.to_string()));

    let models_mod = r##"pub mod course;
pub mod lesson;
"##;
    manifest.push(("src/models/mod.rs", models_mod.to_string()));

    // 4. Controller
    let lms_controller = r##"use rullst::server::{Path, IntoResponse};
use rullst::response::Html;
use crate::models::course::Course;
use crate::models::lesson::Lesson;
use crate::pages::lms;

pub async fn index() -> impl IntoResponse {
    let courses = Course::all().await.unwrap_or_default();
    Html(lms::index_page(courses))
}

pub async fn show_course(Path(id): Path<i32>) -> impl IntoResponse {
    let course = Course::find(id).await.unwrap();
    let all_lessons = Lesson::all().await.unwrap_or_default();
    let course_lessons: Vec<Lesson> = all_lessons.into_iter().filter(|l| l.course_id == id).collect();
    
    Html(lms::course_detail_page(course, course_lessons))
}

pub async fn play_lesson(Path(id): Path<i32>) -> impl IntoResponse {
    let lesson = Lesson::find(id).await.unwrap();
    Html(lms::video_player_snippet(&lesson.title, &lesson.video_url))
}
"##;
    manifest.push((
        "src/controllers/lms_controller.rs",
        lms_controller.to_string(),
    ));

    let controllers_mod = r##"pub mod lms_controller;
"##;
    manifest.push(("src/controllers/mod.rs", controllers_mod.to_string()));

    // 5. Pages
    let lms_page = r##"use rullst::html;
use crate::models::course::Course;
use crate::models::lesson::Lesson;

pub fn index_page(courses: Vec<Course>) -> String {
    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <title>"Rullst Academy - Courses"</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <script src="https://unpkg.com/htmx.org@1.9.10"></script>
                <style>
                    "
                    * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Outfit', sans-serif; }
                    body { background: #080b11; color: #f1f5f9; min-height: 100vh; padding: 3rem 1.5rem; }
                    .container { max-width: 1000px; margin: 0 auto; }
                    header { text-align: center; margin-bottom: 4rem; }
                    h1 { font-size: 3rem; background: linear-gradient(135deg, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight: 800; }
                    p.sub { color: #64748b; font-size: 1.15rem; margin-top: 0.5rem; }
                    .courses-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2.5rem; }
                    .card { background: #111827; border: 1px solid #1f2937; border-radius: 1.25rem; overflow: hidden; transition: transform 0.3s, border-color 0.3s; display: flex; flex-direction: column; }
                    .card:hover { transform: translateY(-5px); border-color: #6366f1; }
                    .card-img { height: 180px; width: 100%; object-fit: cover; }
                    .card-body { padding: 2rem; flex: 1; display: flex; flex-direction: column; }
                    .card h3 { font-size: 1.4rem; margin-bottom: 0.75rem; color: #ffffff; }
                    .card p { color: #94a3b8; font-size: 0.95rem; line-height: 1.6; margin-bottom: 1.5rem; flex: 1; }
                    .btn { display: inline-block; text-align: center; background: linear-gradient(135deg, #6366f1, #4f46e5); color: #ffffff; text-decoration: none; padding: 0.8rem; border-radius: 0.75rem; font-weight: 600; transition: opacity 0.2s; }
                    .btn:hover { opacity: 0.9; }
                    "
                </style>
            </head>
            <body>
                <div class="container">
                    <header>
                        <h1>"Rullst LMS Academy"</h1>
                        <p class="sub">"Explore high-fidelity systems engineering with Rust"</p>
                    </header>
                    <div class="courses-grid">
                        { courses.into_iter().map(|c| html! {
                            <div class="card">
                                <img class="card-img" src={&c.thumbnail} alt={&c.title} />
                                <div class="card-body">
                                    <h3>{&c.title}</h3>
                                    <p>{&c.description}</p>
                                    <a class="btn" href={format!("/courses/{}", c.id)}>"Start Learning"</a>
                                </div>
                            </div>
                        }).collect::<Vec<_>>().join("") }
                    </div>
                </div>
            </body>
        </html>
    }
}

pub fn course_detail_page(course: Course, lessons: Vec<Lesson>) -> String {
    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <title>{&course.title}</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <script src="https://unpkg.com/htmx.org@1.9.10"></script>
                <style>
                    "
                    * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Outfit', sans-serif; }
                    body { background: #080b11; color: #f1f5f9; min-height: 100vh; display: flex; }
                    .sidebar { width: 350px; background: #0f172a; border-right: 1px solid #1e293b; display: flex; flex-direction: column; }
                    .sidebar-header { padding: 2rem; border-bottom: 1px solid #1e293b; }
                    .sidebar-header h2 { font-size: 1.25rem; font-weight: 700; color: #ffffff; }
                    .lessons-list { list-style: none; overflow-y: auto; flex: 1; }
                    .lesson-item { padding: 1.5rem 2rem; border-bottom: 1px solid #1e293b; cursor: pointer; transition: background-color 0.2s; }
                    .lesson-item:hover { background-color: #1e293b; }
                    .lesson-item.active { background-color: #312e81; }
                    .lesson-item h4 { font-size: 0.95rem; font-weight: 600; color: #ffffff; margin-bottom: 0.25rem; }
                    .lesson-item span { font-size: 0.8rem; color: #94a3b8; }
                    .main-content { flex: 1; display: flex; flex-direction: column; background: #090d16; }
                    .video-wrapper { flex: 1; display: flex; align-items: center; justify-content: center; padding: 3rem; }
                    .video-container { width: 100%; max-width: 800px; background: #111827; border: 1px solid #1f2937; border-radius: 1.5rem; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5); }
                    .player { width: 100%; aspect-ratio: 16/9; background: #000; display: block; }
                    .info-bar { padding: 2rem; background: #0f172a; border-top: 1px solid #1e293b; }
                    .info-bar h3 { font-size: 1.5rem; color: #ffffff; margin-bottom: 0.5rem; }
                    .back-btn { margin-bottom: 1rem; display: inline-block; color: #38bdf8; text-decoration: none; font-size: 0.9rem; font-weight: 600; }
                    "
                </style>
            </head>
            <body>
                <div class="sidebar">
                    <div class="sidebar-header">
                        <a class="back-btn" href="/">"&larr; Back to Academy"</a>
                        <h2>{&course.title}</h2>
                    </div>
                    <ul class="lessons-list">
                        { lessons.iter().map(|l| html! {
                            <li class="lesson-item" hx-get={format!("/lessons/{}/play", l.id)} hx-target="#video-panel" hx-swap="innerHTML">
                                <h4>{&l.title}</h4>
                                <span>{{l.duration.to_string()}}" mins"</span>
                            </li>
                        }).collect::<Vec<_>>().join("") }
                    </ul>
                </div>
                <div class="main-content">
                    <div class="video-wrapper" id="video-panel">
                        { if let Some(first_lesson) = lessons.first() {
                            video_player_snippet(&first_lesson.title, &first_lesson.video_url)
                        } else {
                            html! { <div style="color: #64748b;">"No lessons available"</div> }
                        } }
                    </div>
                </div>
            </body>
        </html>
    }
}

pub fn video_player_snippet(title: &str, video_url: &str) -> String {
    html! {
        <div class="video-container">
            <video class="player" controls="controls" autoplay="autoplay" src={video_url}></video>
            <div class="info-bar">
                <h3>{title}</h3>
                <p style="color: #94a3b8; font-size: 0.9rem;">"Now playing from Rullst Cloud CDN."</p>
            </div>
        </div>
    }
}
"##;
    manifest.push(("src/pages/lms.rs", lms_page.to_string()));

    let pages_mod = r##"pub mod lms;
"##;
    manifest.push(("src/pages/mod.rs", pages_mod.to_string()));

    manifest
}
