// src/blueprints/uptime.rs — Uptime Monitoring Service blueprint templates.

pub fn file_manifest(_project_name_safe: &str) -> Vec<(&'static str, String)> {
    let mut manifest = Vec::new();

    // 1. src/main.rs
    let main_rs = r##"use rullst::{routes, Server};
use std::time::Duration;

pub mod migrations;
pub mod models;
pub mod controllers;
pub mod pages;

#[rullst::runtime::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Run migrations on startup
    rullst::artisan!(crate::migrations::get_migrations());

    // Spawn Uptime Ping background worker
    rullst::runtime::spawn(async {
        println!("📡 Uptime Monitor Background Worker iniciado.");
        loop {
            let _ = controllers::uptime_controller::ping_monitors().await;
            rullst::runtime::time::sleep(Duration::from_secs(60)).await;
        }
    });

    let router = routes![
        get("/") => controllers::uptime_controller::index,
        post("/monitors" => controllers::uptime_controller::store_monitor),
        post("/monitors/:id/toggle" => controllers::uptime_controller::toggle_monitor),
    ];

    println!("🚀 Uptime Monitoring server starting on port 3000...");
    Server::new(router)
        .run(3000)
        .await?;

    Ok(())
}
"##;
    manifest.push(("src/main.rs", main_rs.to_string()));

    // 2. Migrations mod.rs
    let migrations_mod = r##"// Generated by Rullst.
pub mod m20260601000000_create_uptime_tables;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_uptime_tables::MigrationImpl),
    ]
}
"##;
    manifest.push(("src/migrations/mod.rs", migrations_mod.to_string()));

    // 3. Migration Implementation
    let migration_impl = r##"use rullst::db::schema::{Schema, Blueprint, Migration};
use rullst::db::async_trait;

pub struct MigrationImpl;

#[async_trait]
impl Migration for MigrationImpl {
    fn name(&self) -> &'static str {
        "m20260601000000_create_uptime_tables"
    }

    async fn up(&self) -> Result<(), rullst::db::sqlx::Error> {
        // Create monitors table
        Schema::create("monitors", |table| {
            table.id();
            table.string("name").not_null();
            table.string("url").not_null();
            table.integer("is_active").not_null(); // 1 = true, 0 = false
            table.timestamps();
        }).await?;

        // Create heartbeats table
        Schema::create("heartbeats", |table| {
            table.id();
            table.integer("monitor_id").not_null();
            table.integer("status_code").not_null();
            table.integer("response_time_ms").not_null();
            table.integer("is_up").not_null(); // 1 = true, 0 = false
            table.string("error_message");
            table.timestamps();
        }).await?;

        // Seed initial monitors
        let pool = rullst::db::Orm::pool();
        
        rullst::db::sqlx::query(
            "INSERT INTO monitors (id, name, url, is_active, created_at, updated_at) VALUES 
             (1, 'Google Core', 'https://www.google.com', 1, datetime('now'), datetime('now')),
             (2, 'GitHub API', 'https://api.github.com', 1, datetime('now'), datetime('now')),
             (3, 'Serviço Inválido Demo', 'https://invalid-service-testing-rullst.com', 1, datetime('now'), datetime('now'))"
        ).execute(pool).await?;

        // Seed historical heartbeats for visualization
        // Google: 20 successful pings
        for i in 1..=20 {
            rullst::db::sqlx::query(
                "INSERT INTO heartbeats (monitor_id, status_code, response_time_ms, is_up, error_message, created_at, updated_at) 
                 VALUES (1, 200, ?, 1, '', datetime('now', ?), datetime('now', ?))"
            )
            .bind(40 + (i % 15)) // response time
            .bind(format!("-{} minutes", 20 - i))
            .bind(format!("-{} minutes", 20 - i))
            .execute(pool)
            .await?;
        }

        // GitHub: 20 successful pings
        for i in 1..=20 {
            rullst::db::sqlx::query(
                "INSERT INTO heartbeats (monitor_id, status_code, response_time_ms, is_up, error_message, created_at, updated_at) 
                 VALUES (2, 200, ?, 1, '', datetime('now', ?), datetime('now', ?))"
            )
            .bind(90 + (i % 30)) // response time
            .bind(format!("-{} minutes", 20 - i))
            .bind(format!("-{} minutes", 20 - i))
            .execute(pool)
            .await?;
        }

        // Invalid service: 20 failing heartbeats
        for i in 1..=20 {
            rullst::db::sqlx::query(
                "INSERT INTO heartbeats (monitor_id, status_code, response_time_ms, is_up, error_message, created_at, updated_at) 
                 VALUES (3, 0, 0, 0, 'DNS Resolution Failed', datetime('now', ?), datetime('now', ?))"
            )
            .bind(format!("-{} minutes", 20 - i))
            .bind(format!("-{} minutes", 20 - i))
            .execute(pool)
            .await?;
        }

        Ok(())
    }

    async fn down(&self) -> Result<(), rullst::db::sqlx::Error> {
        Schema::drop_if_exists("heartbeats").await?;
        Schema::drop_if_exists("monitors").await?;
        Ok(())
    }
}
"##;
    manifest.push((
        "src/migrations/m20260601000000_create_uptime_tables.rs",
        migration_impl.to_string(),
    ));

    // 4. Models mod.rs
    let models_mod = r##"pub mod monitor;
pub mod heartbeat;
"##;
    manifest.push(("src/models/mod.rs", models_mod.to_string()));

    // 5. Monitor Model
    let monitor_model = r##"use rullst::db::{Orm, RullstModel, FromRow, sqlx};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "monitors")]
pub struct Monitor {
    pub id: i32,
    pub name: String,
    pub url: String,
    pub is_active: i32, // 1 = true, 0 = false
}
"##;
    manifest.push(("src/models/monitor.rs", monitor_model.to_string()));

    // 6. Heartbeat Model
    let heartbeat_model = r##"use rullst::db::{Orm, RullstModel, FromRow, sqlx};

#[derive(Debug, Clone, FromRow, Orm)]
#[orm(table = "heartbeats")]
pub struct Heartbeat {
    pub id: i32,
    pub monitor_id: i32,
    pub status_code: i32,
    pub response_time_ms: i32,
    pub is_up: i32, // 1 = true, 0 = false
    pub error_message: Option<String>,
}
"##;
    manifest.push(("src/models/heartbeat.rs", heartbeat_model.to_string()));

    // 7. Controllers mod.rs
    let controllers_mod = r##"pub mod uptime_controller;
"##;
    manifest.push(("src/controllers/mod.rs", controllers_mod.to_string()));

    // 8. Uptime Controller
    let uptime_controller = r##"use rullst::server::{
    Path,
    IntoResponse, Redirect,
    Form
};
use rullst::response::Html;
use crate::models::monitor::Monitor;
use crate::models::heartbeat::Heartbeat;
use crate::pages::uptime;
use serde::Deserialize;
use std::time::Instant;

pub async fn index() -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();
    
    // Get all monitors
    let monitors = Monitor::all().await.unwrap_or_default();
    
    // Package monitors with their last 20 heartbeats
    let mut monitors_with_history = Vec::new();
    for monitor in monitors {
        let history: Vec<Heartbeat> = rullst::db::sqlx::query_as(
            "SELECT * FROM heartbeats WHERE monitor_id = $1 ORDER BY id DESC LIMIT 20"
        )
        .bind(monitor.id)
        .fetch_all(pool)
        .await
        .unwrap_or_default();
        
        // Reverse so chronological order is left-to-right
        let mut history = history;
        history.reverse();
        
        monitors_with_history.push((monitor, history));
    }

    Html(uptime::dashboard_page(monitors_with_history))
}

#[derive(Deserialize)]
pub struct CreateMonitorPayload {
    pub name: String,
    pub url: String,
}

pub async fn store_monitor(Form(payload): Form<CreateMonitorPayload>) -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();
    let _ = rullst::db::sqlx::query(
        "INSERT INTO monitors (name, url, is_active, created_at, updated_at) VALUES ($1, $2, 1, datetime('now'), datetime('now'))"
    )
    .bind(payload.name)
    .bind(payload.url)
    .execute(pool)
    .await;

    Redirect::to("/")
}

pub async fn toggle_monitor(Path(id): Path<i32>) -> impl IntoResponse {
    let pool = rullst::db::Orm::pool();
    
    // Get active state
    let state: (i32,) = rullst::db::sqlx::query_as("SELECT is_active FROM monitors WHERE id = $1")
        .bind(id)
        .fetch_one(pool)
        .await
        .unwrap_or((1,));

    let new_state = if state.0 == 1 { 0 } else { 1 };

    let _ = rullst::db::sqlx::query(
        "UPDATE monitors SET is_active = $1, updated_at = datetime('now') WHERE id = $2"
    )
    .bind(new_state)
    .bind(id)
    .execute(pool)
    .await;

    Redirect::to("/")
}

// Background Ping Job execution
pub async fn ping_monitors() -> Result<(), Box<dyn std::error::Error>> {
    let pool = rullst::db::Orm::pool();
    
    // Get active monitors
    let active_monitors: Vec<Monitor> = rullst::db::sqlx::query_as(
        "SELECT * FROM monitors WHERE is_active = 1"
    )
    .fetch_all(pool)
    .await?;

    // Create a non-reusable client to prevent session caching issues
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .danger_accept_invalid_certs(true)
        .build()
        .unwrap_or_default();

    for monitor in active_monitors {
        let start = Instant::now();
        let res = client.get(&monitor.url).send().await;
        let duration = start.elapsed().as_millis() as i32;

        let (status_code, is_up, error_msg) = match res {
            Ok(response) => {
                let code = response.status().as_u16() as i32;
                let up = if code >= 200 && code < 400 { 1 } else { 0 };
                (code, up, "".to_string())
            }
            Err(e) => {
                (0, 0, e.to_string())
            }
        };

        // Write heartbeat log
        let _ = rullst::db::sqlx::query(
            "INSERT INTO heartbeats (monitor_id, status_code, response_time_ms, is_up, error_message, created_at, updated_at) 
             VALUES ($1, $2, $3, $4, $5, datetime('now'), datetime('now'))"
        )
        .bind(monitor.id)
        .bind(status_code)
        .bind(duration)
        .bind(is_up)
        .bind(error_msg)
        .execute(pool)
        .await;

        println!("📡 Checked '{}' ({}): {} | {}ms", monitor.name, monitor.url, status_code, duration);
    }

    Ok(())
}
"##;
    manifest.push((
        "src/controllers/uptime_controller.rs",
        uptime_controller.to_string(),
    ));

    // 9. Pages mod.rs
    let pages_mod = r##"pub mod uptime;
"##;
    manifest.push(("src/pages/mod.rs", pages_mod.to_string()));

    // 10. Uptime Page View
    let uptime_page = r##"use rullst::html;
use crate::models::monitor::Monitor;
use crate::models::heartbeat::Heartbeat;

pub fn dashboard_page(monitors: Vec<(Monitor, Vec<Heartbeat>)>) -> String {
    // Calculators
    let mut total_checks = 0;
    let mut total_success = 0;
    let mut total_resp_time: u64 = 0;
    let mut active_monitors_count = 0;

    for (_, history) in &monitors {
        for hb in history {
            total_checks += 1;
            if hb.is_up == 1 {
                total_success += 1;
                total_resp_time += hb.response_time_ms as u64;
            }
        }
    }

    for (m, _) in &monitors {
        if m.is_active == 1 {
            active_monitors_count += 1;
        }
    }

    let global_uptime = if total_checks > 0 {
        (total_success as f64 / total_checks as f64) * 100.0
    } else {
        100.0
    };

    let avg_resp_time = if total_success > 0 {
        total_resp_time / total_success
    } else {
        0
    };

    html! {
        <html lang="pt-BR" class="dark">
            <head>
                <meta charset="UTF-8" />
                <title>"Rullst Radar — Painel de Monitoramento"</title>
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
                <script src="https://unpkg.com/htmx.org@1.9.10"></script>
                <script src="https://cdn.tailwindcss.com"></script>
                <style>
                    "
                    body { font-family: 'Outfit', sans-serif; background-color: #03060f; }
                    .glass { background: rgba(8, 14, 28, 0.7); backdrop-filter: blur(16px); border: 1px solid rgba(255, 255, 255, 0.05); }
                    .pulse { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.7); animation: pulse 2s infinite; }
                    @keyframes pulse {
                        0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.7); }
                        70% { transform: scale(1); box-shadow: 0 0 0 8px rgba(16, 185, 129, 0); }
                        100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0); }
                    }
                    "
                </style>
            </head>
            <body class="text-slate-100 min-height-screen pb-12">
                <div class="max-w-5xl mx-auto px-4 pt-8">
                    
                    // --- Header ---
                    <header class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-10 pb-6 border-b border-slate-800/40">
                        <div class="flex items-center gap-4">
                            <div class="w-3.5 h-3.5 rounded-full bg-emerald-500 pulse"></div>
                            <div>
                                <h1 class="text-3xl font-extrabold tracking-tight bg-gradient-to-r from-emerald-400 via-teal-300 to-indigo-400 bg-clip-text text-transparent">"Rullst Uptime Radar"</h1>
                                <p class="text-sm text-slate-400 mt-1">"Monitoramento contínuo de APIs e sites em tempo real."</p>
                            </div>
                        </div>
                        <span class="px-3.5 py-1 text-xs font-semibold text-emerald-400 bg-emerald-950/40 rounded-full border border-emerald-800/40">"Sistema Operacional"</span>
                    </header>

                    // --- KPI Cards ---
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Uptime Global (Últimas 20 pings)"</span>
                            <span class="text-3xl font-bold mt-2 text-emerald-400">{format!("{:.2}%", global_uptime)}</span>
                            <span class="text-xs text-emerald-500/80 mt-1">"Disponibilidade total da rede"</span>
                        </div>
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Tempo de Resposta Médio"</span>
                            <span class="text-3xl font-bold mt-2 text-sky-400">{format!("{} ms", avg_resp_time)}</span>
                            <span class="text-xs text-sky-400/80 mt-1">"Latência de resposta HTTP"</span>
                        </div>
                        <div class="glass p-6 rounded-2xl flex flex-col justify-between">
                            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">"Monitores Ativos"</span>
                            <span class="text-3xl font-bold mt-2 text-indigo-400">{format!("{} / {}", active_monitors_count, monitors.len())}</span>
                            <span class="text-xs text-indigo-400/80 mt-1">"Alvos ativos de varredura"</span>
                        </div>
                    </div>

                    // --- List & Form ---
                    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        
                        // --- Monitores ---
                        <div class="lg:col-span-2 space-y-6">
                            <h2 class="text-xl font-bold text-slate-200">"Monitores Registrados"</h2>
                            
                            { monitors.into_iter().map(|(monitor, history)| {
                                let is_active = monitor.is_active == 1;
                                let last_hb = history.last();
                                let is_currently_up = last_hb.map(|h| h.is_up == 1).unwrap_or(false);
                                
                                // Calculate individual uptime
                                let checks = history.len();
                                let success = history.iter().filter(|h| h.is_up == 1).count();
                                let uptime_pct = if checks > 0 { (success as f64 / checks as f64) * 100.0 } else { 100.0 };
                                
                                let card_border = if !is_active {
                                    "border-slate-800/40 opacity-60"
                                } else if is_currently_up {
                                    "border-emerald-500/20"
                                } else {
                                    "border-rose-500/20"
                                };

                                let toggle_text = if is_active { "Pausar" } else { "Ativar" };

                                html! {
                                    <div class={format!("glass p-6 rounded-2xl border transition-all duration-300 hover:border-slate-700/80 {}", card_border)}>
                                        <div class="flex items-start justify-between gap-4">
                                            <div>
                                                <h3 class="text-lg font-bold text-white">{&monitor.name}</h3>
                                                <a href={&monitor.url} target="_blank" class="text-xs text-slate-400 font-mono hover:text-emerald-400 transition-colors">{&monitor.url}</a>
                                            </div>
                                            
                                            // --- Status Badge ---
                                            <div class="flex items-center gap-2">
                                                { if !is_active {
                                                    html! { <span class="px-2 py-0.5 text-xs font-semibold rounded bg-slate-900 text-slate-400 border border-slate-800">"Inativo"</span> }
                                                } else if is_currently_up {
                                                    html! { <span class="px-2 py-0.5 text-xs font-semibold rounded bg-emerald-950/40 text-emerald-400 border border-emerald-800/40">"Online"</span> }
                                                } else {
                                                    html! { <span class="px-2 py-0.5 text-xs font-semibold rounded bg-rose-950/40 text-rose-400 border border-rose-800/40">"Offline"</span> }
                                                } }
                                            </div>
                                        </div>

                                        // --- Uptime Metrics ---
                                        <div class="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-6 pt-4 border-t border-slate-800/40 text-sm">
                                            <div>
                                                <span class="text-xs text-slate-400 block">"Uptime"</span>
                                                <span class="font-bold text-slate-200">{format!("{:.2}%", uptime_pct)}</span>
                                            </div>
                                            <div>
                                                <span class="text-xs text-slate-400 block">"Latência Recente"</span>
                                                <span class="font-bold text-slate-200">{format!("{} ms", last_hb.map(|h| h.response_time_ms).unwrap_or(0))}</span>
                                            </div>
                                            <div class="col-span-2 sm:col-span-1 text-right">
                                                <form action={format!("/monitors/{}/toggle", monitor.id)} method="POST">
                                                    <button type="submit" class="px-3 py-1 text-xs font-semibold rounded border border-slate-700/80 hover:border-indigo-400 bg-slate-900/40 text-slate-300 hover:text-indigo-400 transition-all">
                                                        {toggle_text}
                                                    </button>
                                                </form>
                                            </div>
                                        </div>

                                        // --- Visual History Blocks ---
                                        <div class="mt-5">
                                            <span class="text-xs text-slate-400 block mb-2">"Histórico de Batimentos (Esquerda &rarr; Direita)"</span>
                                            <div class="flex gap-1.5 overflow-x-auto py-1">
                                                { if history.is_empty() {
                                                    html! { <span class="text-xs text-slate-500">"Aguardando primeira verificação..."</span> }
                                                } else {
                                                    history.iter().map(|hb| {
                                                        let block_color = if hb.is_up == 1 {
                                                            "bg-emerald-500 hover:bg-emerald-400"
                                                        } else {
                                                            "bg-rose-500 hover:bg-rose-400"
                                                        };
                                                        let title = if hb.is_up == 1 {
                                                            format!("Uptime: {}ms (Código {})", hb.response_time_ms, hb.status_code)
                                                        } else {
                                                            format!("Offline: {}", hb.error_message.clone().unwrap_or_default())
                                                        };
                                                        html! {
                                                            <div 
                                                                title={title}
                                                                class={format!("w-5 h-8 rounded-sm transition-all duration-150 hover:scale-110 cursor-pointer {}", block_color)}
                                                            ></div>
                                                        }
                                                    }).collect::<Vec<_>>().join("")
                                                } }
                                            </div>
                                        </div>

                                    </div>
                                }
                            }).collect::<Vec<_>>().join("") }

                        </div>

                        // --- Lateral Form ---
                        <div>
                            <div class="glass p-6 rounded-2xl sticky top-8">
                                <h3 class="text-lg font-bold mb-4 text-slate-200">"Novo Monitor"</h3>
                                <p class="text-xs text-slate-400 mb-4">"Adicione uma URL HTTP ou HTTPS para monitoramento de latência e disponibilidade a cada 60 segundos."</p>
                                
                                <form action="/monitors" method="POST" class="space-y-4">
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Nome do Serviço"</label>
                                        <input type="text" name="name" required=true class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-emerald-500 text-slate-200" placeholder="Ex: Meu Blog" />
                                    </div>
                                    <div>
                                        <label class="block text-xs text-slate-400 font-medium mb-1">"Endereço URL"</label>
                                        <input type="url" name="url" required=true class="w-full bg-slate-900/60 border border-slate-800 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-emerald-500 text-slate-200" placeholder="https://meusite.com" />
                                    </div>
                                    <button type="submit" class="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-2 rounded-lg text-sm transition-all active:scale-98">
                                        "Adicionar Monitor"
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </body>
        </html>
    }
}
"##;
    manifest.push(("src/pages/uptime.rs", uptime_page.to_string()));

    manifest
}
