// Generated by Rullst.
pub mod m20260601000000_create_users_table;
pub mod m20260601000002_create_subscriptions_table;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_users_table::MigrationImpl),
        Box::new(m20260601000002_create_subscriptions_table::MigrationImpl),
    ]
}
