//! The GitHub-readable Markdown report: one table per section.

use std::fmt::Write as _;

use super::catalog::{
    ASVS_NAME, ASVS_SOURCE, ASVS_VERSION, MAPPING_NOTE, NOTICE, PERSONAL_DATA, WCAG_VERSION,
    describe, level1_coverage, not_evaluated,
};
use super::model::{Check, Group, Report};

/// A table cell: no pipe, line break or raw HTML can change the table.
pub(super) fn cell(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}

fn references(check: &Check) -> String {
    let mut parts: Vec<String> = check.spec.asvs.iter().map(describe).collect();
    if let Some(chapter) = check.spec.chapter {
        parts.push(format!("chapter {chapter}"));
    }
    parts.extend(
        check
            .spec
            .wcag
            .iter()
            .map(|criterion| format!("WCAG {criterion}")),
    );
    parts.join("; ")
}

fn checks_table(out: &mut String, report: &Report, group: Group) {
    let _ = writeln!(out, "## {}\n", group.title());
    out.push_str("| Check | Result | Evidence | Mapping | Fix | Docs |\n");
    out.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");
    for check in report
        .checks
        .iter()
        .filter(|check| check.spec.group == group)
    {
        let _ = writeln!(
            out,
            "| {} | **{}** | {} | {} | {} | [guide]({}) |",
            cell(check.spec.title),
            check.status.label(),
            cell(&check.detail),
            cell(&references(check)),
            cell(check.spec.fix),
            check.spec.docs(),
        );
    }
    let findings: Vec<_> = report
        .checks
        .iter()
        .filter(|check| check.spec.group == group)
        .flat_map(|check| check.findings.iter().map(move |finding| (check, finding)))
        .collect();
    if findings.is_empty() {
        out.push('\n');
        return;
    }
    let _ = writeln!(out, "\n### {} findings\n", group.title());
    out.push_str("| Check | Location | Finding | Preview |\n");
    out.push_str("| :--- | :--- | :--- | :--- |\n");
    for (check, finding) in findings {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            cell(check.spec.title),
            cell(&finding.location()),
            cell(&finding.message),
            cell(finding.preview.as_deref().unwrap_or("")),
        );
    }
    out.push('\n');
}

pub(crate) fn render(report: &Report) -> String {
    let mut out = String::new();
    let (mapped, total) = level1_coverage(report);
    out.push_str("# Rullst Security Report\n\n");
    let _ = writeln!(out, "> {NOTICE}\n");
    let _ = writeln!(out, "- Generated at: {}", report.generated_at);
    let _ = writeln!(
        out,
        "- Generated by: cargo-rullst {} (`cargo rullst audit --report`)",
        env!("CARGO_PKG_VERSION")
    );
    let _ = writeln!(
        out,
        "- Standard: {ASVS_NAME} {ASVS_VERSION}, Level 1 mapping ([source]({ASVS_SOURCE}))"
    );
    let _ = writeln!(
        out,
        "- Level 1 requirements related to a check: {mapped} of {total}; the rest are listed as NOT EVALUATED"
    );
    let _ = writeln!(out, "- Accessibility criteria: {WCAG_VERSION}");
    let _ = writeln!(
        out,
        "- Exit status: {}\n",
        if report.fails() {
            "non-zero (a check reported FINDINGS or ERROR)"
        } else {
            "zero (no check reported FINDINGS or ERROR)"
        }
    );
    let _ = writeln!(out, "{MAPPING_NOTE}\n");
    checks_table(&mut out, report, Group::Security);

    let personal = &report.personal_data;
    out.push_str("## Personal-data inventory\n\n");
    let _ = writeln!(
        out,
        "**{}** — {} ([guide]({}))\n",
        personal.status.label(),
        cell(&personal.detail),
        PERSONAL_DATA.docs()
    );
    if !personal.fields.is_empty() {
        out.push_str("| Model | Field | Location | Classification | Encrypted |\n");
        out.push_str("| :--- | :--- | :--- | :--- | :--- |\n");
        for field in &personal.fields {
            let _ = writeln!(
                out,
                "| {} | {} | {} | {} | {} |",
                cell(&field.model),
                cell(&field.field),
                cell(&format!("{}:{}", field.file, field.line)),
                cell(&field.classification),
                if field.encrypted { "yes" } else { "no" },
            );
        }
        out.push('\n');
    }

    checks_table(&mut out, report, Group::Accessibility);

    out.push_str("## ASVS 5.0.0 Level 1 requirements NOT EVALUATED\n\n");
    out.push_str("A static source scan cannot evaluate these requirements; they need design review, dynamic testing or deployment evidence.\n\n");
    out.push_str("| Chapter | Status | Requirements |\n");
    out.push_str("| :--- | :--- | :--- |\n");
    for chapter in not_evaluated(report) {
        let _ = writeln!(
            out,
            "| {} {} | **NOT EVALUATED** | {} |",
            chapter.chapter,
            cell(chapter.name),
            if chapter.whole_chapter {
                format!("all Level 1 ({})", chapter.requirements.join(", "))
            } else {
                chapter.requirements.join(", ")
            },
        );
    }
    out.push_str(
        "\nV16 Security Logging and Error Handling and V17 WebRTC have no Level 1 requirements.\n",
    );
    out
}
