[package]
name = "rullst-capital-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"
rullst-capital = { path = ".." }
chrono = { version = "0.4.45", features = ["clock", "serde"] }

[[bin]]
name = "fuzz_invoice"
path = "fuzz_targets/fuzz_invoice.rs"
test = false
doc = false
