//! Bounded server-rendered catalog generated by the complete and foundation LMS profiles.

use crate::blueprints::common;

pub fn get_files(frontend_engine: &str) -> Vec<(&'static str, String)> {
    let page = format!(
        "{}{}{}",
        common::frontend_page_imports(frontend_engine),
        CATALOG_PAGE,
        super::lms_player::PLAYER_PAGE,
    );
    vec![
        (
            "src/controllers/lms_controller.rs",
            CATALOG_CONTROLLER.to_string(),
        ),
        ("src/pages/lms.rs", page),
    ]
}

const CATALOG_CONTROLLER: &str = r##"use crate::models::category::Category;
use crate::models::course::Course;
use crate::models::lesson::Lesson;
use crate::pages::lms;
use rullst::response::Html;
use rullst::server::{Extension, IntoResponse, Path, Query, Response, StatusCode};
use serde::Deserialize;

const MAX_CATALOG_QUERY_CHARS: usize = 100;
const MAX_CATALOG_RESULTS: usize = 100;
const MAX_COURSE_LESSONS: usize = 500;

#[derive(Debug, Default, Deserialize)]
pub struct CatalogQuery {
    pub q: Option<String>,
    pub category: Option<i32>,
}

#[derive(Debug)]
pub enum CatalogError {
    InvalidQuery,
    Database(rullst_orm::Error),
}

impl From<rullst_orm::Error> for CatalogError {
    fn from(error: rullst_orm::Error) -> Self {
        Self::Database(error)
    }
}

pub fn normalize_catalog_query(
    query: &CatalogQuery,
) -> Result<(String, Option<i32>), CatalogError> {
    let normalized = query.q.as_deref().unwrap_or_default().trim();
    if normalized.chars().count() > MAX_CATALOG_QUERY_CHARS
        || normalized.chars().any(char::is_control)
        || query.category.is_some_and(|category| category <= 0)
    {
        return Err(CatalogError::InvalidQuery);
    }
    Ok((normalized.to_owned(), query.category))
}

pub async fn search_courses(
    query: &CatalogQuery,
) -> Result<(String, Option<i32>, Vec<Course>), CatalogError> {
    let (normalized, category) = normalize_catalog_query(query)?;
    let mut builder = Course::query();
    if let Some(category_id) = category {
        builder = builder.where_eq("category_id", category_id);
    }
    if !normalized.is_empty() {
        builder = builder.where_like("title", format!("%{normalized}%"));
    }
    let courses = builder
        .order_by("title")
        .limit(MAX_CATALOG_RESULTS)
        .get()
        .await?;
    Ok((normalized, category, courses))
}

fn error_response(error: CatalogError) -> Response {
    match error {
        CatalogError::InvalidQuery => (
            StatusCode::UNPROCESSABLE_ENTITY,
            "Catalog query must contain at most 100 visible characters and a positive category",
        )
            .into_response(),
        CatalogError::Database(error) => {
            eprintln!("LMS catalog query failed: {error}");
            (
                StatusCode::SERVICE_UNAVAILABLE,
                "Catalog temporarily unavailable",
            )
                .into_response()
        }
    }
}

pub async fn index(
    Query(query): Query<CatalogQuery>,
    csp_nonce: Option<Extension<rullst::security::CspNonce>>,
) -> Response {
    let categories = match Category::query()
        .order_by("name")
        .limit(MAX_CATALOG_RESULTS)
        .get()
        .await
    {
        Ok(categories) => categories,
        Err(error) => return error_response(error.into()),
    };
    let (normalized, category, courses) = match search_courses(&query).await {
        Ok(result) => result,
        Err(error) => return error_response(error),
    };
    let nonce = csp_nonce
        .as_ref()
        .map(|Extension(value)| value.as_str())
        .unwrap_or_default();
    Html(lms::index_page(
        categories,
        courses,
        &normalized,
        category,
        nonce,
    ))
    .into_response()
}

pub async fn show_course(
    Path(id): Path<i32>,
    csrf: Option<Extension<rullst::security::CsrfToken>>,
    csp_nonce: Option<Extension<rullst::security::CspNonce>>,
) -> Response {
    if id <= 0 {
        return (StatusCode::BAD_REQUEST, "Course id must be positive").into_response();
    }
    let course = match Course::find(id).await {
        Ok(Some(course)) => course,
        Ok(None) => return (StatusCode::NOT_FOUND, "Course not found").into_response(),
        Err(error) => return error_response(error.into()),
    };
    let lessons = match Lesson::query()
        .where_eq("course_id", id)
        .order_by("id")
        .limit(MAX_COURSE_LESSONS)
        .get()
        .await
    {
        Ok(lessons) => lessons,
        Err(error) => return error_response(error.into()),
    };
    let csrf_token = csrf
        .as_ref()
        .map(|Extension(token)| token.as_str())
        .unwrap_or_default();
    let nonce = csp_nonce
        .as_ref()
        .map(|Extension(value)| value.as_str())
        .unwrap_or_default();
    Html(lms::course_detail_page(
        course,
        lessons,
        csrf_token,
        nonce,
    ))
    .into_response()
}

#[cfg(test)]
mod tests {
    use super::{CatalogError, CatalogQuery, normalize_catalog_query};

    #[test]
    fn catalog_query_is_bounded_and_category_is_positive() {
        let valid = normalize_catalog_query(&CatalogQuery {
            q: Some("  Rust systems  ".to_string()),
            category: Some(2),
        });
        assert!(matches!(
            valid,
            Ok((query, Some(2))) if query == "Rust systems"
        ));
        assert!(matches!(
            normalize_catalog_query(&CatalogQuery {
                q: Some("x".repeat(101)),
                category: None,
            }),
            Err(CatalogError::InvalidQuery)
        ));
        assert!(matches!(
            normalize_catalog_query(&CatalogQuery {
                q: None,
                category: Some(0),
            }),
            Err(CatalogError::InvalidQuery)
        ));
    }
}
"##;

const CATALOG_PAGE: &str = r##"use crate::models::category::Category;
use crate::models::course::Course;
use crate::models::lesson::Lesson;

pub fn index_page(
    categories: Vec<Category>,
    courses: Vec<Course>,
    query: &str,
    selected_category: Option<i32>,
    csp_nonce: &str,
) -> String {
    let category_input = selected_category.map_or_else(String::new, |category| {
        html! {
            <input type="hidden" name="category" value={category.to_string()} />
        }
    });
    let category_links = categories
        .iter()
        .map(|category| {
            let class = if selected_category == Some(category.id) {
                "chip current"
            } else {
                "chip"
            };
            html! {
                <a class={class} href={format!("/?category={}", category.id)}>{&category.name}</a>
            }
        })
        .collect::<Vec<_>>()
        .join("");
    let course_cards = if courses.is_empty() {
        html! {
            <div class="empty" role="status">
                <h2>"No courses found"</h2>
                <p>"Try another title or clear the active category."</p>
                <a class="button secondary" href="/">"Clear filters"</a>
            </div>
        }
    } else {
        courses
            .iter()
            .map(|course| html! {
                <article class="card">
                    <div class="course-mark" aria-hidden="true">"Course"</div>
                    <div class="card-body">
                        <h2>{&course.title}</h2>
                        <p>{&course.description}</p>
                        <a class="button" href={format!("/courses/{}", course.id)}>"View course"</a>
                    </div>
                </article>
            })
            .collect::<Vec<_>>()
            .join("")
    };
    let summary = match (query.is_empty(), selected_category) {
        (true, None) => format!("{} courses available", courses.len()),
        (false, None) => format!("{} results for “{}”", courses.len(), query),
        (true, Some(_)) => format!("{} courses in the selected category", courses.len()),
        (false, Some(_)) => format!("{} filtered results for “{}”", courses.len(), query),
    };

    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>"Rullst Academy — Course catalog"</title>
                <style nonce={csp_nonce}>
                    "
                    * { box-sizing: border-box; }
                    body { margin: 0; background: #080b11; color: #f8fafc; min-height: 100vh; padding: 2rem 1rem 4rem; font: 16px system-ui, sans-serif; }
                    a { color: inherit; }
                    a:focus-visible, button:focus-visible, input:focus-visible { outline: 3px solid #fbbf24; outline-offset: 3px; }
                    .container { max-width: 70rem; margin: 0 auto; }
                    .skip { position: absolute; left: -9999px; top: .5rem; padding: .75rem; background: #f8fafc; color: #111827; z-index: 5; }
                    .skip:focus { left: .5rem; }
                    header { display: flex; gap: 2rem; justify-content: space-between; align-items: flex-start; margin-bottom: 2rem; }
                    h1 { margin: 0; font-size: clamp(2rem, 7vw, 3.5rem); color: #6ee7b7; }
                    .sub, .summary { color: #cbd5e1; line-height: 1.6; }
                    .actions { display: flex; gap: .75rem; flex-wrap: wrap; }
                    .button { display: inline-block; border: 1px solid #34d399; border-radius: .65rem; background: #047857; color: #fff; padding: .75rem 1rem; text-align: center; text-decoration: none; font-weight: 700; }
                    .button:hover { background: #065f46; }
                    .secondary { border-color: #64748b; background: #1e293b; }
                    .search { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: .75rem; margin: 1.5rem 0; }
                    .search label { grid-column: 1 / -1; font-weight: 700; }
                    .search input { min-width: 0; border: 1px solid #64748b; border-radius: .65rem; background: #111827; color: #fff; padding: .8rem 1rem; font: inherit; }
                    .search button { border: 1px solid #34d399; border-radius: .65rem; background: #047857; color: #fff; padding: .8rem 1rem; font: inherit; font-weight: 700; cursor: pointer; }
                    .chips { display: flex; gap: .6rem; flex-wrap: wrap; margin: 1rem 0 2rem; }
                    .chip { border: 1px solid #64748b; border-radius: 999px; padding: .55rem .85rem; color: #e2e8f0; text-decoration: none; }
                    .chip.current { border-color: #34d399; background: #064e3b; color: #fff; }
                    .courses-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 18rem), 1fr)); gap: 1.25rem; }
                    .card { display: flex; flex-direction: column; overflow: hidden; border: 1px solid #334155; border-radius: 1rem; background: #111827; }
                    .course-mark { padding: 2rem; background: #0f3d35; color: #a7f3d0; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; }
                    .card-body { display: flex; flex: 1; flex-direction: column; padding: 1.5rem; }
                    .card h2 { margin: 0 0 .75rem; font-size: 1.35rem; }
                    .card p { flex: 1; margin: 0 0 1.25rem; color: #cbd5e1; line-height: 1.6; }
                    .empty { grid-column: 1 / -1; border: 1px dashed #64748b; border-radius: 1rem; padding: 2rem; text-align: center; }
                    @media (max-width: 48rem) { header { flex-direction: column; } .search { grid-template-columns: 1fr; } }
                    @media (prefers-reduced-motion: reduce) { * { scroll-behavior: auto !important; } }
                    "
                </style>
            </head>
            <body>
                <a class="skip" href="#catalog-results">"Skip to course results"</a>
                <div class="container">
                    <header>
                        <div>
                            <h1>"Rullst Academy"</h1>
                            <p class="sub">"A server-rendered starter catalog with bounded search."</p>
                        </div>
                        <nav class="actions" aria-label="Developer tools">
                            <a class="button secondary" href="/nexus">"Nexus CMS"</a>
                            <a class="button secondary" href="http://127.0.0.1:5555" target="_blank" rel="noopener noreferrer">"Local Studio"</a>
                        </nav>
                    </header>
                    <main id="catalog-results">
                        <form class="search" method="get" action="/" role="search">
                            <label for="catalog-query">"Search course titles"</label>
                            <input id="catalog-query" type="search" name="q" value={query} maxlength="100" autocomplete="off" />
                            {rullst::html::RawHtml(category_input)}
                            <button type="submit">"Search"</button>
                        </form>
                        <nav class="chips" aria-label="Course categories">
                            <a class={if selected_category.is_none() { "chip current" } else { "chip" }} href="/">"All courses"</a>
                            {rullst::html::RawHtml(category_links)}
                        </nav>
                        <p class="summary" aria-live="polite">{summary}</p>
                        <div class="courses-grid">
                            {rullst::html::RawHtml(course_cards)}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    }
}

pub fn course_detail_page(
    course: Course,
    lessons: Vec<Lesson>,
    csrf_token: &str,
    csp_nonce: &str,
) -> String {
    let lesson_items = if lessons.is_empty() {
        html! {
            <li class="empty-lesson">"No published lessons are available yet."</li>
        }
    } else {
        lessons
            .iter()
            .map(|lesson| html! {
                <li>
                    <a class="lesson" href={format!("/lessons/{}/play", lesson.id)}>
                        <span>{&lesson.title}</span>
                        <small>{lesson.duration.to_string()}" minutes"</small>
                    </a>
                </li>
            })
            .collect::<Vec<_>>()
            .join("")
    };
    html! {
        <html lang="en" class="dark">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>{&course.title}</title>
                <style nonce={csp_nonce}>
                    "
                    * { box-sizing: border-box; }
                    body { margin: 0; background: #080b11; color: #f8fafc; min-height: 100vh; font: 16px system-ui, sans-serif; }
                    a:focus-visible, button:focus-visible { outline: 3px solid #fbbf24; outline-offset: 3px; }
                    .layout { display: grid; grid-template-columns: minmax(18rem, 24rem) 1fr; min-height: 100vh; }
                    aside { border-right: 1px solid #334155; background: #0f172a; padding: 2rem; }
                    main { display: grid; place-items: center; padding: 2rem; }
                    h1 { line-height: 1.2; }
                    .back { color: #fdba74; font-weight: 700; }
                    .description { color: #cbd5e1; line-height: 1.6; }
                    form { margin: 1.5rem 0; }
                    button { width: 100%; border: 1px solid #34d399; border-radius: .6rem; background: #047857; color: #fff; padding: .8rem; font: inherit; font-weight: 800; cursor: pointer; }
                    ul { padding: 0; list-style: none; }
                    li { border-top: 1px solid #334155; }
                    .lesson { display: flex; gap: .75rem; justify-content: space-between; padding: 1rem 0; color: #f8fafc; text-decoration: none; }
                    .lesson:hover { color: #6ee7b7; }
                    small, .notice, .empty-lesson { color: #cbd5e1; }
                    .notice { max-width: 40rem; border: 1px solid #334155; border-radius: 1rem; background: #111827; padding: 2rem; line-height: 1.7; }
                    @media (max-width: 48rem) { .layout { grid-template-columns: 1fr; } aside { border-right: 0; border-bottom: 1px solid #334155; } }
                    "
                </style>
            </head>
            <body>
                <div class="layout">
                    <aside>
                        <a class="back" href="/">"← Back to catalog"</a>
                        <h1>{&course.title}</h1>
                        <p class="description">{&course.description}</p>
                        <form method="post" action={format!("/courses/{}/enroll", course.id)}>
                            <input type="hidden" name="_token" value={csrf_token} />
                            <button type="submit">"Enroll or resume"</button>
                        </form>
                        <h2>"Lessons"</h2>
                        <ul>{rullst::html::RawHtml(lesson_items)}</ul>
                    </aside>
                    <main>
                        <section class="notice">
                            <h2>"Protected lesson area"</h2>
                            <p>"Register and enroll before opening a lesson. The server derives identity from the session and verifies entitlement before returning media metadata."</p>
                            <p>"Production media, captions and transcripts must be supplied by the host application; the scaffold fixtures are development-only."</p>
                        </section>
                    </main>
                </div>
            </body>
        </html>
    }
}

"##;

#[cfg(test)]
mod tests {
    use super::{CATALOG_CONTROLLER, CATALOG_PAGE};

    #[test]
    fn generated_catalog_is_bounded_parameterized_and_nonce_compatible() {
        assert!(CATALOG_CONTROLLER.contains(".where_like(\"title\","));
        assert!(CATALOG_CONTROLLER.contains(".where_eq(\"category_id\","));
        assert!(CATALOG_CONTROLLER.contains(".limit(MAX_CATALOG_RESULTS)"));
        assert!(CATALOG_CONTROLLER.contains("Option<Extension<rullst::security::CspNonce>>"));
        assert!(CATALOG_PAGE.contains("<style nonce={csp_nonce}>"));
        assert!(!CATALOG_PAGE.contains("style="));
        assert!(!CATALOG_PAGE.contains("https://"));
        assert!(!CATALOG_PAGE.contains("<script"));
        assert!(!CATALOG_PAGE.contains("hx-"));
    }

    #[test]
    fn generated_catalog_has_keyboard_and_accessibility_landmarks() {
        for marker in [
            "Skip to course results",
            ":focus-visible",
            "prefers-reduced-motion",
            "aria-live=\"polite\"",
            "role=\"search\"",
            "captions and transcripts",
        ] {
            assert!(CATALOG_PAGE.contains(marker), "missing marker: {marker}");
        }
    }
}
