//! Runtime behaviour of code generated by `#[island]`.

#![allow(clippy::unwrap_used, clippy::expect_used)]

/// A value whose `Serialize` implementation always fails.
struct Unserializable;

impl serde::Serialize for Unserializable {
    fn serialize<S: serde::Serializer>(&self, _serializer: S) -> Result<S::Ok, S::Error> {
        Err(serde::ser::Error::custom("deliberately unserializable"))
    }
}

#[crate::island]
fn wide_counter(start: u128) -> String {
    format!("<b>{start}</b>")
}

#[crate::island]
fn opaque_widget(value: Unserializable) -> String {
    let _ = value;
    "<i>static</i>".to_string()
}

#[test]
fn island_renders_without_hydration_props_instead_of_panicking() {
    assert_eq!(
        wide_counter(5),
        "<div data-island=\"wide_counter\" data-props=\"{&quot;start&quot;:5}\"><b>5</b></div>"
    );
    let wide = u128::from(u64::MAX) + 1;
    assert_eq!(
        wide_counter(wide),
        format!("<div data-island=\"wide_counter\" data-props=\"\"><b>{wide}</b></div>")
    );
    assert_eq!(
        opaque_widget(Unserializable),
        "<div data-island=\"opaque_widget\" data-props=\"\"><i>static</i></div>"
    );
}
