use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EvidenceStatus {
    NoFindings,
    NoFindingsOutsideExceptions(Vec<String>),
    Findings(usize),
    Generated(usize),
    Observed(usize),
    NotChecked(&'static str),
    Error(String),
}

impl EvidenceStatus {
    fn label(&self) -> &'static str {
        match self {
            Self::NoFindings => "NO FINDINGS",
            Self::NoFindingsOutsideExceptions(_) => "NO FINDINGS OUTSIDE EXCEPTIONS",
            Self::Findings(_) => "FINDINGS",
            Self::Generated(_) => "GENERATED",
            Self::Observed(_) => "OBSERVED",
            Self::NotChecked(_) => "NOT CHECKED",
            Self::Error(_) => "ERROR",
        }
    }

    fn detail(&self) -> String {
        match self {
            Self::NoFindings => "The named check ran and reported no findings.".to_string(),
            Self::NoFindingsOutsideExceptions(advisories) => format!(
                "The check completed with explicit governed exception(s): {}. These advisories remain findings and require separate review.",
                advisories.join(", ")
            ),
            Self::Findings(count) => format!("{count} finding(s) reported."),
            Self::Generated(count) => format!("Artifact generated with {count} component(s)."),
            Self::Observed(count) => format!("The bounded scan recorded {count} observation(s)."),
            Self::NotChecked(reason) => (*reason).to_string(),
            Self::Error(error) => format!("Check failed to complete: {error}"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ComplianceEvidence {
    pub secret_scan: EvidenceStatus,
    pub dependency_audit: EvidenceStatus,
    pub unsafe_scan: EvidenceStatus,
    pub idor_scan: EvidenceStatus,
    pub sbom: EvidenceStatus,
    pub network_scan: EvidenceStatus,
}

fn row(report: &mut String, check: &str, status: &EvidenceStatus) {
    report.push_str(&format!(
        "| {check} | **{}** | {} |\n",
        status.label(),
        status.detail().replace('|', "\\|").replace('\n', " ")
    ));
}

pub fn write_compliance_report(
    output: &Path,
    evidence: &ComplianceEvidence,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut report = String::new();
    report.push_str("# Rullst Security Evidence Report\n\n");
    report.push_str("> Generated by cargo rullst audit --compliance. This is a record of checks actually executed, not an OWASP, SOC 2, ISO 27001, FedRAMP, or regulatory certification.\n\n");
    report.push_str(&format!(
        "- Generated at: {}\n",
        chrono::Utc::now().to_rfc3339()
    ));
    report.push_str("- Scope: current project source tree and local Cargo metadata.\n\n");
    report.push_str("## Executed evidence\n\n");
    report.push_str("| Check | Result | Evidence boundary |\n");
    report.push_str("| :--- | :--- | :--- |\n");
    row(
        &mut report,
        "Local secret-strength heuristic",
        &evidence.secret_scan,
    );
    row(&mut report, "cargo audit", &evidence.dependency_audit);
    row(
        &mut report,
        "Project-source unsafe scan",
        &evidence.unsafe_scan,
    );
    row(
        &mut report,
        "Parameterized-route IDOR heuristic",
        &evidence.idor_scan,
    );
    row(&mut report, "CycloneDX SBOM generation", &evidence.sbom);
    row(
        &mut report,
        "Local network-surface scan",
        &evidence.network_scan,
    );

    report.push_str("\n## Controls not established by this command\n\n");
    report.push_str("| Control family | Status | Reason |\n");
    report.push_str("| :--- | :--- | :--- |\n");
    report.push_str("| OWASP Top 10 conformance | **NOT EVALUATED** | Requires application-specific design review, dynamic testing, and deployment evidence. |\n");
    report.push_str("| Cryptographic key management / vault | **NOT EVALUATED** | Source heuristics do not prove algorithms, key custody, rotation, or data recovery. |\n");
    report.push_str("| CSP / secure-header deployment | **NOT EVALUATED** | Requires response-level tests against the deployed application. |\n");
    report.push_str("| Authentication, MFA, and brute-force controls | **NOT EVALUATED** | Presence of framework modules does not prove route composition or policy. |\n");
    report.push_str("| TLS configuration | **NOT EVALUATED** | Requires inspection of the actual ingress and certificate configuration. |\n");
    report.push_str("| SOC 2 / ISO 27001 / FedRAMP readiness | **NOT EVALUATED** | Organizational controls and independent audit evidence are outside this static command. |\n\n");
    report.push_str("NO FINDINGS means only that the named bounded check completed without a finding. It is not a certification result.\n");
    report.push_str("NO FINDINGS OUTSIDE EXCEPTIONS means explicit advisory exceptions were supplied by the caller; those advisories remain unresolved and require separate governance.\n");

    fs::write(output, report)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn report_never_fabricates_compliance_passes() {
        let output =
            std::env::temp_dir().join(format!("rullst-compliance-{}.md", rand::random::<u64>()));
        let evidence = ComplianceEvidence {
            secret_scan: EvidenceStatus::NoFindings,
            dependency_audit: EvidenceStatus::NotChecked("cargo-audit unavailable"),
            unsafe_scan: EvidenceStatus::Findings(2),
            idor_scan: EvidenceStatus::NoFindings,
            sbom: EvidenceStatus::NotChecked("SBOM not requested"),
            network_scan: EvidenceStatus::NotChecked("network scan not requested"),
        };
        write_compliance_report(&output, &evidence).expect("evidence report");
        let report = fs::read_to_string(&output).expect("evidence contents");
        assert!(!report.contains("✅ PASS"));
        assert!(!report.contains("FedRAMP Ready"));
        assert!(!report.contains("Vault AES-256"));
        assert!(report.contains("NOT EVALUATED"));
        assert!(!report.contains("PASS"));
        fs::remove_file(output).expect("temporary report cleanup");
    }

    #[test]
    fn report_preserves_governed_advisory_exceptions() {
        let output = std::env::temp_dir().join(format!(
            "rullst-compliance-exceptions-{}.md",
            rand::random::<u64>()
        ));
        let evidence = ComplianceEvidence {
            secret_scan: EvidenceStatus::NoFindings,
            dependency_audit: EvidenceStatus::NoFindingsOutsideExceptions(vec![
                "RUSTSEC-2023-0071".to_string(),
            ]),
            unsafe_scan: EvidenceStatus::NoFindings,
            idor_scan: EvidenceStatus::NoFindings,
            sbom: EvidenceStatus::NotChecked("SBOM not requested"),
            network_scan: EvidenceStatus::NotChecked("network scan not requested"),
        };
        write_compliance_report(&output, &evidence).expect("evidence report");
        let report = fs::read_to_string(&output).expect("evidence contents");
        assert!(report.contains("NO FINDINGS OUTSIDE EXCEPTIONS"));
        assert!(report.contains("RUSTSEC-2023-0071"));
        assert!(report.contains("remain unresolved"));
        fs::remove_file(output).expect("temporary report cleanup");
    }
}
