use colored::*;
use std::fs;
use std::io;
use std::path::Path;

use crate::generators::output_guard::{reject_symlink, write_output};

/// First line of every generated `diagram.md`. Only a file that carries it,
/// or the unmarked single Mermaid block earlier releases wrote, is replaced.
const MARKER: &str = "<!-- Generated by `cargo rullst generate:diagram`; manual edits are replaced when it runs again. -->";
const LEGACY_PREFIX: &str = "```mermaid\nerDiagram\n";

struct ModelDef {
    name: String,
    fields: Vec<(String, String)>,
}

struct RelationDef {
    from: String,
    to: String,
    rel_type: String,
    label: String,
}

/// Writes `diagram.md` from the ORM models under `src/`.
///
/// An existing `diagram.md` is replaced only when this generator wrote it; a
/// hand-written file or a symlink is refused and left untouched.
pub fn generate_mermaid_diagram(
    base_path: Option<&Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    println!("{}", "📊 Generating Mermaid Diagram...".cyan());
    let base = base_path.unwrap_or_else(|| Path::new("."));

    let src_path = base.join("src");
    if !src_path.exists() {
        return Err(
            "No src/ directory found to scan for models. Are you in a Rullst project root?".into(),
        );
    }

    let mut models = Vec::new();
    let mut relations = Vec::new();

    fn scan_dir(dir: &Path, models: &mut Vec<ModelDef>, relations: &mut Vec<RelationDef>) {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    scan_dir(&path, models, relations);
                } else if path.extension().unwrap_or_default() == "rs"
                    && let Ok(content) = fs::read_to_string(&path)
                {
                    if !content.contains("Orm") {
                        continue;
                    }

                    if let Ok(syntax_tree) = syn::parse_file(&content) {
                        for item in syntax_tree.items {
                            if let syn::Item::Struct(s) = item {
                                let mut has_orm = false;
                                for attr in &s.attrs {
                                    let attr_str = quote::quote!(#attr).to_string();
                                    if attr_str.contains("Orm") {
                                        has_orm = true;
                                        break;
                                    }
                                }
                                if !has_orm {
                                    continue;
                                }

                                let model_name = s.ident.to_string();
                                let mut model_fields = Vec::new();

                                if let syn::Fields::Named(named_fields) = s.fields {
                                    for f in named_fields.named {
                                        if let Some(ident) = f.ident {
                                            let field_name = ident.to_string();
                                            let ty = &f.ty;
                                            let ty_str =
                                                quote::quote!(#ty).to_string().replace(" ", "");

                                            if ty_str.starts_with("HasMany<") {
                                                let target = ty_str
                                                    .trim_start_matches("HasMany<")
                                                    .trim_end_matches('>')
                                                    .to_string();
                                                relations.push(RelationDef {
                                                    from: model_name.clone(),
                                                    to: target,
                                                    rel_type: "||--o{".to_string(),
                                                    label: field_name,
                                                });
                                            } else if ty_str.starts_with("BelongsTo<") {
                                                let target = ty_str
                                                    .trim_start_matches("BelongsTo<")
                                                    .trim_end_matches('>')
                                                    .to_string();
                                                relations.push(RelationDef {
                                                    from: model_name.clone(),
                                                    to: target,
                                                    rel_type: "}o--||".to_string(),
                                                    label: field_name,
                                                });
                                            } else if ty_str.starts_with("HasOne<") {
                                                let target = ty_str
                                                    .trim_start_matches("HasOne<")
                                                    .trim_end_matches('>')
                                                    .to_string();
                                                relations.push(RelationDef {
                                                    from: model_name.clone(),
                                                    to: target,
                                                    rel_type: "||--o|".to_string(),
                                                    label: field_name,
                                                });
                                            } else if ty_str.starts_with("BelongsToMany<") {
                                                let target = ty_str
                                                    .trim_start_matches("BelongsToMany<")
                                                    .trim_end_matches('>')
                                                    .to_string();
                                                relations.push(RelationDef {
                                                    from: model_name.clone(),
                                                    to: target,
                                                    rel_type: "}o--o{".to_string(),
                                                    label: field_name,
                                                });
                                            } else {
                                                model_fields.push((ty_str, field_name));
                                            }
                                        }
                                    }
                                }
                                models.push(ModelDef {
                                    name: model_name,
                                    fields: model_fields,
                                });
                            }
                        }
                    }
                }
            }
        }
    }

    scan_dir(&src_path, &mut models, &mut relations);

    let mut diagram = format!("{MARKER}\n\n{LEGACY_PREFIX}");

    for m in models {
        diagram.push_str(&format!("    {} {{\n", m.name));
        for (ty, name) in m.fields {
            let clean_ty = ty.replace("<", "~").replace(">", "~"); // mermaid requires ~ instead of <>
            diagram.push_str(&format!("        {} {}\n", clean_ty, name));
        }
        diagram.push_str("    }\n");
    }

    for rel in relations {
        diagram.push_str(&format!(
            "    {} {} {} : \"{}\"\n",
            rel.from, rel.rel_type, rel.to, rel.label
        ));
    }
    diagram.push_str("```\n");

    let output_path = base.join("diagram.md");
    ensure_replaceable(&output_path)?;
    write_output(&output_path, diagram.as_bytes(), true)?;

    println!(
        "{}",
        "  ✅ Mermaid ER Diagram generated successfully at diagram.md".green()
    );

    Ok(())
}

/// Refreshes the diagram after a scaffold without ever failing the scaffold.
///
/// A missing `diagram.md` is created; a hand-written one is kept with a notice.
pub(crate) fn refresh_after_scaffold() {
    refresh_after_scaffold_in(Path::new("."));
}

fn refresh_after_scaffold_in(base: &Path) {
    if let Err(error) = generate_mermaid_diagram(Some(base)) {
        eprintln!("Scaffold completed, but diagram.md was not refreshed: {error}");
    }
}

/// Fails unless `path` is absent or a regular file this generator wrote.
fn ensure_replaceable(path: &Path) -> io::Result<()> {
    reject_symlink(path)?;
    let existing = match fs::read(path) {
        Ok(existing) => existing,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    if is_generated(&String::from_utf8_lossy(&existing)) {
        return Ok(());
    }
    Err(io::Error::new(
        io::ErrorKind::AlreadyExists,
        format!(
            "refusing to replace '{}': it was not generated by `cargo rullst generate:diagram`; move it aside to regenerate the diagram",
            path.display()
        ),
    ))
}

fn is_generated(existing: &str) -> bool {
    existing.starts_with(MARKER)
        // Earlier releases wrote exactly one unmarked Mermaid block.
        || (existing.starts_with(LEGACY_PREFIX)
            && existing.ends_with("\n```\n")
            && existing.matches("```").count() == 2)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> tempfile::TempDir {
        let directory = tempfile::tempdir().unwrap();
        fs::create_dir_all(directory.path().join("src/models")).unwrap();
        fs::write(
            directory.path().join("src/models/course.rs"),
            "#[derive(Orm)]\npub struct Course {\n    pub id: i64,\n}\n",
        )
        .unwrap();
        directory
    }

    #[test]
    fn scaffold_refresh_never_replaces_a_hand_written_diagram() {
        let project = project();
        let diagram = project.path().join("diagram.md");
        let architecture = "# Architecture\n\nHand-written notes.\n";
        fs::write(&diagram, architecture).unwrap();

        refresh_after_scaffold_in(project.path());
        assert_eq!(fs::read_to_string(&diagram).unwrap(), architecture);
        let refused = generate_mermaid_diagram(Some(project.path())).unwrap_err();
        assert!(refused.to_string().contains("move it aside"), "{refused}");
        assert_eq!(fs::read_to_string(&diagram).unwrap(), architecture);
    }

    #[test]
    fn generated_and_legacy_diagrams_are_refreshed_and_missing_ones_created() {
        let project = project();
        let diagram = project.path().join("diagram.md");

        refresh_after_scaffold_in(project.path());
        let created = fs::read_to_string(&diagram).unwrap();
        assert!(created.starts_with(MARKER));
        assert!(created.contains("Course {"));

        fs::write(&diagram, format!("{MARKER}\nstale\n")).unwrap();
        refresh_after_scaffold_in(project.path());
        assert_eq!(fs::read_to_string(&diagram).unwrap(), created);

        fs::write(&diagram, "```mermaid\nerDiagram\n    Old {\n    }\n```\n").unwrap();
        generate_mermaid_diagram(Some(project.path())).unwrap();
        assert_eq!(fs::read_to_string(&diagram).unwrap(), created);

        assert!(!is_generated(
            "```mermaid\nerDiagram\n```\n\nNotes kept below the block.\n```text\nx\n```\n"
        ));
    }

    #[cfg(unix)]
    #[test]
    fn diagram_is_never_written_through_a_symlink() {
        let project = project();
        let outside = tempfile::NamedTempFile::new().unwrap();
        fs::write(outside.path(), "outside").unwrap();
        std::os::unix::fs::symlink(outside.path(), project.path().join("diagram.md")).unwrap();

        assert!(generate_mermaid_diagram(Some(project.path())).is_err());
        refresh_after_scaffold_in(project.path());
        assert_eq!(fs::read_to_string(outside.path()).unwrap(), "outside");
    }
}
