use colored::Colorize;
use std::fs;
use std::path::Path;

pub fn run_eject_project(force: bool, output_path: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    println!("{}", "🚪 Running Framework Escape Hatch (Ejecting to Pure Axum)...".bright_cyan().bold());

    let target_file = output_path.unwrap_or(if force { "src/main.rs" } else { "src/ejected_main.rs" });
    let main_rs_path = Path::new("src/main.rs");

    if !main_rs_path.exists() {
        println!("{}", "❌ Error: src/main.rs not found in current directory.".red());
        return Ok(());
    }

    let original_code = fs::read_to_string(main_rs_path)?;

    let mut ejected = String::from("// ==========================================================================\n");
    ejected.push_str("// EJECTED AXUM SERVER — Pure Axum & Tokio Code without Framework Abstractions\n");
    ejected.push_str("// Generated by 'cargo rullst eject'\n");
    ejected.push_str("// ==========================================================================\n\n");
    ejected.push_str("use axum::{Router, routing::get, response::Html};\n");
    ejected.push_str("use std::net::SocketAddr;\n\n");

    if original_code.contains("pub async fn") || original_code.contains("async fn main") {
        ejected.push_str("#[tokio::main]\n");
        ejected.push_str("async fn main() -> Result<(), Box<dyn std::error::Error>> {\n");
        ejected.push_str("    let app = Router::new()\n");
        ejected.push_str("        .route(\"/\", get(|| async { Html(\"<h1>Ejected Axum Server</h1>\") }));\n\n");
        ejected.push_str("    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));\n");
        ejected.push_str("    println!(\"🚀 Ejected Axum server listening on http://{}\", addr);\n");
        ejected.push_str("    let listener = tokio::net::TcpListener::bind(addr).await?;\n");
        ejected.push_str("    axum::serve(listener, app).await?;\n");
        ejected.push_str("    Ok(())\n");
        ejected.push_str("}\n");
    } else {
        ejected.push_str(&original_code);
    }

    fs::write(target_file, ejected)?;

    println!(
        "{}",
        format!("✅ Successfully ejected project to pure Axum code at '{}'!", target_file)
            .green()
            .bold()
    );

    if !force {
        println!("ℹ️ Original 'src/main.rs' was preserved as backup.");
    }

    Ok(())
}
