// src/generators/foundry.rs — Cloud deployment and server provisioning.

use crate::generators::is_rullst_project;
use colored::*;
use std::fs;
use std::process::Command;

fn generate_foundry_toml_template(project_name: &str) -> String {
    format!(
        r#"# ┌──────────────────────────────────────────────────────────────┐
# │           Rullst Foundry - Deployment Manifest               │
# │  Generated by `cargo rullst foundry:init`                    │
# │  Edit this file and run `cargo rullst foundry:deploy`        │
# └──────────────────────────────────────────────────────────────┘

[app]
# The name of your application (used for container and systemd service naming)
name = "{project_name}"
# The public domain that will serve your app (Caddy will get SSL automatically)
domain = "yourdomain.com"
# The internal port your Rullst server binds to
port = 3000

[deploy]
# Cloud provider: "hetzner" | "aws" | "gcp" | "azure" | "oci" | "digitalocean"
provider = "hetzner"

[server]
# Public IP or hostname of the target server
host = "1.2.3.4"
# SSH login user (typically root for fresh VPS, or a sudo user for managed VMs)
user = "root"
# Path to your SSH private key (leave empty to use SSH agent)
ssh_key = "~/.ssh/id_rsa"
# SSH port (default: 22)
ssh_port = 22

[build]
# Build profile: "release" | "debug"
profile = "release"
# Target triple (leave empty to use the local default)
# For cross-compilation from macOS/Windows to Linux: "x86_64-unknown-linux-musl"
target = ""

[database]
# Database type: "sqlite" | "postgres" | "mysql"
type = "sqlite"
# SQLite: path relative to the deployed binary  |  Postgres/MySQL: full connection URL
url = "sqlite:///app/data/db.sqlite"

[caddy]
# Enable automatic HTTPS via Caddy (strongly recommended for production)
auto_https = true
# Optional: add extra Caddyfile directives (e.g., rate_limit, header, etc.)
extra_directives = ""

[env]
# Environment variables injected into the container at runtime.
# Add your application secrets here (they will NOT be committed if you gitignore Foundry.toml).
APP_ENV = "production"
APP_KEY = "CHANGE_ME_TO_A_SECURE_RANDOM_KEY"
DATABASE_URL = "sqlite:///app/data/db.sqlite"
# STRIPE_SECRET_KEY = ""
# AWS_ACCESS_KEY_ID = ""
"#,
        project_name = project_name
    )
}

fn add_foundry_to_gitignore() -> Result<(), Box<dyn std::error::Error>> {
    let gitignore_path = std::path::Path::new(".gitignore");
    if gitignore_path.exists() {
        let content = fs::read_to_string(gitignore_path).unwrap_or_default();
        if !content.contains("Foundry.toml") {
            let mut new_content = content;
            if !new_content.ends_with('\n') {
                new_content.push('\n');
            }
            new_content.push_str("# Rullst Foundry (contains server secrets)\nFoundry.toml\n");
            fs::write(gitignore_path, new_content)?;
            println!(
                "{}",
                "🔒 Automatically added Foundry.toml to .gitignore to protect your secrets."
                    .green()
            );
        }
    }
    Ok(())
}

fn ensure_is_rullst_project() {
    if !is_rullst_project() {
        println!(
            "{}{}",
            "❌ Error: This command must be executed in the root of a valid Rullst project."
                .red()
                .bold(),
            "\nMake sure the current folder contains a 'Cargo.toml' file with a 'rullst' dependency."
                .yellow()
        );
        std::process::exit(1);
    }
}

pub fn scaffold_foundry_config() -> Result<(), Box<dyn std::error::Error>> {
    ensure_is_rullst_project();

    let foundry_path = std::path::Path::new("Foundry.toml");
    if foundry_path.exists() {
        println!(
            "{}",
            "⚠️  Foundry.toml already exists. Delete it first to re-initialize."
                .yellow()
                .bold()
        );
        std::process::exit(0);
    }

    println!(
        "{}",
        "🏭 Initializing Rullst Foundry deployment manifest (Foundry.toml)..."
            .cyan()
            .bold()
    );

    let cargo_content = fs::read_to_string("Cargo.toml").unwrap_or_default();
    let project_name = cargo_content
        .lines()
        .find(|l| l.trim_start().starts_with("name"))
        .and_then(|l| l.split('=').nth(1))
        .map(|s| s.trim().trim_matches('"').to_string())
        .unwrap_or_else(|| "my-rullst-app".to_string());

    let foundry_toml = generate_foundry_toml_template(&project_name);
    fs::write(foundry_path, &foundry_toml)?;

    println!(
        "{}",
        "✅ Foundry.toml generated successfully!".green().bold()
    );
    println!("\n{}", "📋 Next steps:".bold());
    println!(
        "  1. Edit {} with your server IP, domain, and secrets.",
        "Foundry.toml".cyan()
    );
    println!(
        "  2. Add {} to your {} to keep secrets safe.",
        "Foundry.toml".cyan(),
        ".gitignore".yellow()
    );
    println!(
        "  3. Run {} to deploy to your cloud provider.\n",
        "cargo rullst foundry:deploy".magenta().bold()
    );

    add_foundry_to_gitignore()?;
    Ok(())
}

struct FoundryConfig {
    app_name: String,
    domain: String,
    port: String,
    host: String,
    user: String,
    ssh_key: String,
    ssh_port: String,
    provider: String,
    db_type: String,
    profile: String,
    target_triple: String,
    auto_https: String,
    env_vars: Vec<(String, String)>,
}

fn parse_foundry_config(content: &str) -> FoundryConfig {
    let get_value = |key: &str| -> String {
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with(key) && trimmed.contains('=') {
                return trimmed
                    .split_once('=')
                    .map(|x| x.1)
                    .unwrap_or("")
                    .trim()
                    .trim_matches('"')
                    .to_string();
            }
        }
        String::new()
    };

    let mut env_vars = Vec::new();
    let mut in_env = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[env]" {
            in_env = true;
            continue;
        }
        if trimmed.starts_with('[') && trimmed != "[env]" {
            in_env = false;
        }
        if in_env && trimmed.contains('=') && !trimmed.starts_with('#') {
            let mut parts = trimmed.splitn(2, '=');
            if let (Some(k), Some(v)) = (parts.next(), parts.next()) {
                env_vars.push((k.trim().to_string(), v.trim().trim_matches('"').to_string()));
            }
        }
    }

    FoundryConfig {
        app_name: get_value("name"),
        domain: get_value("domain"),
        port: get_value("port"),
        host: get_value("host"),
        user: get_value("user"),
        ssh_key: get_value("ssh_key"),
        ssh_port: get_value("ssh_port"),
        provider: get_value("provider"),
        db_type: get_value("type"),
        profile: get_value("profile"),
        target_triple: get_value("target"),
        auto_https: get_value("auto_https"),
        env_vars,
    }
}

fn validate_foundry_config(cfg: &FoundryConfig) {
    if cfg.app_name.is_empty()
        || !cfg
            .app_name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        println!("{}", "❌ Error: Invalid app name in Foundry.toml. Only alphanumeric, dashes and underscores are allowed.".red().bold());
        std::process::exit(1);
    }
    if !cfg.domain.is_empty()
        && !cfg
            .domain
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-')
    {
        println!("{}", "❌ Error: Invalid domain in Foundry.toml. Only alphanumeric, dots and dashes are allowed.".red().bold());
        std::process::exit(1);
    }
    if cfg.ssh_key.starts_with('-') {
        println!(
            "{}",
            "❌ Error: Invalid SSH key path in Foundry.toml. Path cannot start with a dash."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
    if cfg.user.is_empty()
        || !cfg
            .user
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        println!("{}", "❌ Error: Invalid SSH user in Foundry.toml. Only alphanumeric, dashes and underscores are allowed.".red().bold());
        std::process::exit(1);
    }
    if cfg.host.is_empty()
        || !cfg
            .host
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == ':')
    {
        println!("{}", "❌ Error: Invalid SSH host in Foundry.toml. Only alphanumeric, dots, colons and dashes are allowed.".red().bold());
        std::process::exit(1);
    }
    if (!cfg.ssh_port.is_empty() && !cfg.ssh_port.chars().all(|c| c.is_ascii_digit()))
        || (!cfg.port.is_empty() && !cfg.port.chars().all(|c| c.is_ascii_digit()))
    {
        println!(
            "{}",
            "❌ Error: Invalid port in Foundry.toml. Only digits are allowed."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
}

fn get_ssh_base_args(cfg: &FoundryConfig) -> Vec<String> {
    let mut args = Vec::new();
    let ssh_port_num = if cfg.ssh_port.is_empty() {
        "22"
    } else {
        &cfg.ssh_port
    };
    args.push("-p".to_string());
    args.push(ssh_port_num.to_string());

    let ssh_key_expanded = cfg.ssh_key.replace(
        "~",
        &std::env::var("HOME").unwrap_or_else(|_| std::env::var("USERPROFILE").unwrap_or_default()),
    );
    if !ssh_key_expanded.is_empty() {
        args.push("-i".to_string());
        args.push(ssh_key_expanded);
    }
    args.push("-o".to_string());
    args.push("StrictHostKeyChecking=accept-new".to_string());
    args.push(format!("{}@{}", cfg.user, cfg.host));
    args
}

fn run_ssh(cmd: &str, base_args: &[String]) -> Result<bool, Box<dyn std::error::Error>> {
    let mut full_args = base_args.to_vec();
    full_args.push(cmd.to_string());
    let status = Command::new("ssh").args(&full_args).status()?;
    Ok(status.success())
}

fn execute_build_step(cfg: &FoundryConfig) -> Result<String, Box<dyn std::error::Error>> {
    println!(
        "{}",
        "📦 [1/5] Building production binary...".bold().yellow()
    );
    let mut build_args = vec!["build".to_string()];
    if cfg.profile != "debug" {
        build_args.push("--release".to_string());
    }
    if !cfg.target_triple.is_empty() {
        build_args.push("--target".to_string());
        build_args.push(cfg.target_triple.clone());
    }

    if !Command::new("cargo").args(&build_args).status()?.success() {
        println!("{}", "❌ Build failed. Aborting deployment.".red().bold());
        std::process::exit(1);
    }
    println!("{}", "  ✅ Build successful.".green());

    let bin_subdir = if cfg.target_triple.is_empty() {
        if cfg.profile == "debug" {
            "debug".to_string()
        } else {
            "release".to_string()
        }
    } else {
        format!(
            "{}/{}",
            cfg.target_triple,
            if cfg.profile == "debug" {
                "debug"
            } else {
                "release"
            }
        )
    };

    let cargo_toml_content = fs::read_to_string("Cargo.toml").unwrap_or_default();
    let bin_name = cargo_toml_content
        .lines()
        .find(|l| l.trim_start().starts_with("name"))
        .and_then(|l| l.split('=').nth(1))
        .map(|s| s.trim().trim_matches('"').to_string())
        .unwrap_or_else(|| cfg.app_name.clone());

    Ok(format!("target/{}/{}", bin_subdir, bin_name))
}

fn execute_provision_step(ssh_args: &[String]) -> Result<(), Box<dyn std::error::Error>> {
    println!(
        "{}",
        "🖥️  [2/5] Provisioning server environment..."
            .bold()
            .yellow()
    );
    let provision_cmd = r#"set -e
apt-get update -qq
apt-get install -y -qq docker.io curl wget || yum install -y docker curl wget || true
systemctl enable docker --now || true
mkdir -p /app/data /app/bin /app/config
echo "✅ Server environment ready.""#
        .to_string();

    if !run_ssh(&provision_cmd, ssh_args)? {
        println!(
            "{}",
            "⚠️  Server provisioning had warnings (continuing anyway)...".yellow()
        );
    } else {
        println!("{}", "  ✅ Server provisioned.".green());
    }
    Ok(())
}

fn execute_upload_step(
    cfg: &FoundryConfig,
    local_bin: &str,
    _ssh_args: &[String],
) -> Result<(), Box<dyn std::error::Error>> {
    println!(
        "{}",
        "📤 [3/5] Uploading application binary...".bold().yellow()
    );
    let mut scp_args = Vec::new();
    let ssh_port_num = if cfg.ssh_port.is_empty() {
        "22"
    } else {
        &cfg.ssh_port
    };
    scp_args.push("-P".to_string());
    scp_args.push(ssh_port_num.to_string());

    let ssh_key_expanded = cfg.ssh_key.replace(
        "~",
        &std::env::var("HOME").unwrap_or_else(|_| std::env::var("USERPROFILE").unwrap_or_default()),
    );
    if !ssh_key_expanded.is_empty() {
        scp_args.push("-i".to_string());
        scp_args.push(ssh_key_expanded);
    }
    scp_args.push("-o".to_string());
    scp_args.push("StrictHostKeyChecking=accept-new".to_string());
    scp_args.push(local_bin.to_string());
    let bin_name = std::path::Path::new(local_bin)
        .file_name()
        .unwrap()
        .to_string_lossy();
    scp_args.push(format!("{}@{}:/app/bin/{}", cfg.user, cfg.host, bin_name));

    if !Command::new("scp").args(&scp_args).status()?.success() {
        println!(
            "{}",
            "❌ Failed to upload binary via SCP. Check SSH access and try again."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
    println!("{}", "  ✅ Binary uploaded to /app/bin/.".green());
    Ok(())
}

fn execute_configure_step(
    cfg: &FoundryConfig,
    bin_name: &str,
    ssh_args: &[String],
) -> Result<(), Box<dyn std::error::Error>> {
    println!(
        "{}",
        "⚙️  [4/5] Configuring services (env, Caddy, container)..."
            .bold()
            .yellow()
    );
    let app_port = if cfg.port.is_empty() {
        "3000"
    } else {
        &cfg.port
    };
    let caddy_site = if cfg.auto_https == "true" || cfg.auto_https.is_empty() {
        format!(
            r#"{domain} {{
    reverse_proxy localhost:{app_port}
    encode gzip zstd
    header {{
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Frame-Options DENY
        X-Content-Type-Options nosniff
        Referrer-Policy strict-origin-when-cross-origin
    }}
    log {{
        output file /var/log/caddy/{app_name}.log
    }}
}}"#,
            domain = cfg.domain,
            app_port = app_port,
            app_name = cfg.app_name
        )
    } else {
        format!(
            ":{app_port} {{\n    reverse_proxy localhost:{app_port}\n}}",
            app_port = app_port
        )
    };

    let env_lines = cfg
        .env_vars
        .iter()
        .map(|(k, v)| format!("{}={}", k, v))
        .collect::<Vec<_>>()
        .join("\n");
    let configure_cmd = format!(
        r#"set -e
cat > /app/config/.env << 'ENVEOF'
{env_lines}
ENVEOF
cat > /etc/caddy/Caddyfile << 'CADDYEOF'
{caddy_site}
CADDYEOF
if ! command -v caddy &> /dev/null; then
    curl -fsSL https://caddyserver.com/install.sh | bash -s -- --
fi
chmod +x /app/bin/{bin_name}
docker rm -f rullst_{app_name} 2>/dev/null || true
pkill -f "/app/bin/{bin_name}" 2>/dev/null || true
cat > /etc/systemd/system/rullst_{app_name}.service << 'SVCEOF'
[Unit]
Description=Rullst App: {app_name}
After=network.target

[Service]
Type=simple
ExecStart=/app/bin/{bin_name}
WorkingDirectory=/app/data
EnvironmentFile=/app/config/.env
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable rullst_{app_name}
systemctl restart rullst_{app_name}
systemctl enable caddy 2>/dev/null || true
systemctl reload caddy 2>/dev/null || systemctl restart caddy 2>/dev/null || caddy reload 2>/dev/null || true
echo "✅ Services configured and started."
"#,
        env_lines = env_lines,
        caddy_site = caddy_site,
        bin_name = bin_name,
        app_name = cfg.app_name
    );

    if !run_ssh(&configure_cmd, ssh_args)? {
        println!(
            "{}",
            "⚠️  Service configuration had warnings. Verify on the server.".yellow()
        );
    } else {
        println!("{}", "  ✅ Services configured and started.".green());
    }
    Ok(())
}

fn print_deployment_summary(cfg: &FoundryConfig) {
    let app_port = if cfg.port.is_empty() {
        "3000"
    } else {
        &cfg.port
    };
    println!(
        "\n{}",
        "┌────────────────────────────────────────────────────────────┐"
            .cyan()
            .bold()
    );
    println!(
        "{}",
        format!(
            "│  🏭  Rullst Foundry — Deploying to {:>24} │",
            cfg.provider.to_uppercase()
        )
        .cyan()
        .bold()
    );
    println!(
        "{}",
        "└────────────────────────────────────────────────────────────┘"
            .cyan()
            .bold()
    );
    println!("\n  {} {}", "→ App:".bold(), cfg.app_name.cyan());
    println!("  {} {}", "→ Domain:".bold(), cfg.domain.cyan());
    println!(
        "  {} {}",
        "→ Server:".bold(),
        format!("{}@{}", cfg.user, cfg.host).cyan()
    );
    println!("  {} {}", "→ Port:".bold(), app_port.cyan());
    println!("  {} {}", "→ DB:".bold(), cfg.db_type.cyan());
    println!(
        "  {} {}",
        "→ Profile:".bold(),
        if cfg.profile.is_empty() {
            "release"
        } else {
            &cfg.profile
        }
        .cyan()
    );
    println!();
}

fn print_deployment_success(cfg: &FoundryConfig) {
    println!(
        "\n{}",
        "┌────────────────────────────────────────────────────────────┐"
            .green()
            .bold()
    );
    println!(
        "{}",
        "│  🎉  Rullst Foundry — Deployment Complete!                  │"
            .green()
            .bold()
    );
    println!(
        "{}",
        "└────────────────────────────────────────────────────────────┘"
            .green()
            .bold()
    );
    println!();

    let url_protocol = if cfg.auto_https == "true" || cfg.auto_https.is_empty() {
        "https"
    } else {
        "http"
    };
    println!(
        "  {} {}://{}",
        "🌐 Your app is live at:".bold(),
        url_protocol,
        cfg.domain.cyan().bold()
    );
    println!(
        "  {}",
        "📋 To check logs: ssh into your server and run:".bold()
    );
    println!(
        "     {}",
        format!("journalctl -u rullst_{} -f", cfg.app_name).magenta()
    );
    println!();
}

pub fn run_foundry_deploy() -> Result<(), Box<dyn std::error::Error>> {
    ensure_is_rullst_project();

    let foundry_path = std::path::Path::new("Foundry.toml");
    if !foundry_path.exists() {
        println!(
            "{}",
            "❌ Foundry.toml not found. Run 'cargo rullst foundry:init' first."
                .red()
                .bold()
        );
        std::process::exit(1);
    }

    let content = fs::read_to_string(foundry_path)?;
    let cfg = parse_foundry_config(&content);
    validate_foundry_config(&cfg);

    print_deployment_summary(&cfg);

    let ssh_base_args = get_ssh_base_args(&cfg);

    let local_bin = execute_build_step(&cfg)?;
    execute_provision_step(&ssh_base_args)?;

    let bin_name = std::path::Path::new(&local_bin)
        .file_name()
        .unwrap()
        .to_string_lossy();
    execute_upload_step(&cfg, &local_bin, &ssh_base_args)?;
    execute_configure_step(&cfg, &bin_name, &ssh_base_args)?;

    println!(
        "{}",
        "🩺 [5/5] Running deployment health check..."
            .bold()
            .yellow()
    );
    let app_port = if cfg.port.is_empty() {
        "3000"
    } else {
        &cfg.port
    };
    let health_cmd = format!(
        "sleep 3 && curl -sf http://localhost:{app_port} > /dev/null && echo '✅ App is responding!' || echo '⚠️  App may still be starting...'"
    );
    let _ = run_ssh(&health_cmd, &ssh_base_args);

    print_deployment_success(&cfg);
    Ok(())
}
