// src/generators/foundry.rs — Cloud deployment and server provisioning.

use crate::generators::is_rullst_project;
use colored::*;
use std::fs;
use std::process::Command;

pub fn scaffold_foundry_config() -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        println!(
            "{}{}",
            "❌ Error: This command must be executed in the root of a valid Rullst project."
                .red()
                .bold(),
            "\nMake sure the current folder contains a 'Cargo.toml' file with a 'rullst' dependency."
                .yellow()
        );
        std::process::exit(1);
    }

    let foundry_path = std::path::Path::new("Foundry.toml");
    if foundry_path.exists() {
        println!(
            "{}",
            "⚠️  Foundry.toml already exists. Delete it first to re-initialize."
                .yellow()
                .bold()
        );
        std::process::exit(0);
    }

    println!(
        "{}",
        "🏭 Initializing Rullst Foundry deployment manifest (Foundry.toml)..."
            .cyan()
            .bold()
    );

    // Read project name from Cargo.toml
    let cargo_content = fs::read_to_string("Cargo.toml").unwrap_or_default();
    let project_name = cargo_content
        .lines()
        .find(|l| l.trim_start().starts_with("name"))
        .and_then(|l| l.split('=').nth(1))
        .map(|s| s.trim().trim_matches('"').to_string())
        .unwrap_or_else(|| "my-rullst-app".to_string());

    let foundry_toml = format!(
        r#"# ┌──────────────────────────────────────────────────────────────┐
# │           Rullst Foundry - Deployment Manifest               │
# │  Generated by `cargo rullst foundry:init`                    │
# │  Edit this file and run `cargo rullst foundry:deploy`        │
# └──────────────────────────────────────────────────────────────┘

[app]
# The name of your application (used for container and systemd service naming)
name = "{project_name}"
# The public domain that will serve your app (Caddy will get SSL automatically)
domain = "yourdomain.com"
# The internal port your Rullst server binds to
port = 3000

[deploy]
# Cloud provider: "hetzner" | "aws" | "gcp" | "azure" | "oci" | "digitalocean"
provider = "hetzner"

[server]
# Public IP or hostname of the target server
host = "1.2.3.4"
# SSH login user (typically root for fresh VPS, or a sudo user for managed VMs)
user = "root"
# Path to your SSH private key (leave empty to use SSH agent)
ssh_key = "~/.ssh/id_rsa"
# SSH port (default: 22)
ssh_port = 22

[build]
# Build profile: "release" | "debug"
profile = "release"
# Target triple (leave empty to use the local default)
# For cross-compilation from macOS/Windows to Linux: "x86_64-unknown-linux-musl"
target = ""

[database]
# Database type: "sqlite" | "postgres" | "mysql"
type = "sqlite"
# SQLite: path relative to the deployed binary  |  Postgres/MySQL: full connection URL
url = "sqlite:///app/data/db.sqlite"

[caddy]
# Enable automatic HTTPS via Caddy (strongly recommended for production)
auto_https = true
# Optional: add extra Caddyfile directives (e.g., rate_limit, header, etc.)
extra_directives = ""

[env]
# Environment variables injected into the container at runtime.
# Add your application secrets here (they will NOT be committed if you gitignore Foundry.toml).
APP_ENV = "production"
APP_KEY = "CHANGE_ME_TO_A_SECURE_RANDOM_KEY"
DATABASE_URL = "sqlite:///app/data/db.sqlite"
# STRIPE_SECRET_KEY = ""
# AWS_ACCESS_KEY_ID = ""
"#,
        project_name = project_name
    );

    fs::write(foundry_path, &foundry_toml)?;

    println!(
        "{}",
        "✅ Foundry.toml generated successfully!".green().bold()
    );
    println!();
    println!("{}", "📋 Next steps:".bold());
    println!(
        "  1. Edit {} with your server IP, domain, and secrets.",
        "Foundry.toml".cyan()
    );
    println!(
        "  2. Add {} to your {} to keep secrets safe.",
        "Foundry.toml".cyan(),
        ".gitignore".yellow()
    );
    println!(
        "  3. Run {} to deploy to your cloud provider.",
        "cargo rullst foundry:deploy".magenta().bold()
    );
    println!();

    // Suggest adding to .gitignore
    let gitignore_path = std::path::Path::new(".gitignore");
    if gitignore_path.exists() {
        let content = fs::read_to_string(gitignore_path).unwrap_or_default();
        if !content.contains("Foundry.toml") {
            let mut new_content = content;
            if !new_content.ends_with('\n') {
                new_content.push('\n');
            }
            new_content.push_str("# Rullst Foundry (contains server secrets)\nFoundry.toml\n");
            fs::write(gitignore_path, new_content)?;
            println!(
                "{}",
                "🔒 Automatically added Foundry.toml to .gitignore to protect your secrets."
                    .green()
            );
        }
    }

    Ok(())
}

pub fn run_foundry_deploy() -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        println!(
            "{}{}",
            "❌ Error: This command must be executed in the root of a valid Rullst project."
                .red()
                .bold(),
            "\nMake sure the current folder contains a 'Cargo.toml' file with a 'rullst' dependency."
                .yellow()
        );
        std::process::exit(1);
    }

    let foundry_path = std::path::Path::new("Foundry.toml");
    if !foundry_path.exists() {
        println!(
            "{}",
            "❌ Foundry.toml not found. Run 'cargo rullst foundry:init' first."
                .red()
                .bold()
        );
        std::process::exit(1);
    }

    // --- Parse Foundry.toml ---
    let content = fs::read_to_string(foundry_path)?;

    let get_value = |key: &str| -> String {
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with(key) && trimmed.contains('=') {
                let val = trimmed
                    .split_once('=')
                    .map(|x| x.1)
                    .unwrap_or("")
                    .trim()
                    .trim_matches('"')
                    .to_string();
                return val;
            }
        }
        String::new()
    };

    let app_name = get_value("name");
    let domain = get_value("domain");
    let port = get_value("port");
    let host = get_value("host");
    let user = get_value("user");
    let ssh_key = get_value("ssh_key");
    let ssh_port = get_value("ssh_port");
    let provider = get_value("provider");
    let db_type = get_value("type");
    let _db_url = get_value("url");
    let profile = get_value("profile");
    let target_triple = get_value("target");
    let auto_https = get_value("auto_https");

    // Collect [env] block
    let mut env_vars: Vec<(String, String)> = Vec::new();
    let mut in_env = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[env]" {
            in_env = true;
            continue;
        }
        if trimmed.starts_with('[') && trimmed != "[env]" {
            in_env = false;
        }
        if in_env && trimmed.contains('=') && !trimmed.starts_with('#') {
            let mut parts = trimmed.splitn(2, '=');
            if let (Some(k), Some(v)) = (parts.next(), parts.next()) {
                env_vars.push((k.trim().to_string(), v.trim().trim_matches('"').to_string()));
            }
        }
    }

    let ssh_key_expanded = ssh_key.replace(
        "~",
        &std::env::var("HOME").unwrap_or_else(|_| std::env::var("USERPROFILE").unwrap_or_default()),
    );
    let ssh_port_num = if ssh_port.is_empty() {
        "22".to_string()
    } else {
        ssh_port
    };
    let app_port = if port.is_empty() {
        "3000".to_string()
    } else {
        port
    };

    let ssh_base_args: Vec<String> = {
        let mut args = Vec::new();
        args.push("-p".to_string());
        args.push(ssh_port_num.clone());
        if !ssh_key_expanded.is_empty() {
            args.push("-i".to_string());
            args.push(ssh_key_expanded.clone());
        }
        args.push("-o".to_string());
        args.push("StrictHostKeyChecking=no".to_string());
        args.push(format!("{}@{}", user, host));
        args
    };

    let run_ssh = |cmd: &str| -> Result<bool, Box<dyn std::error::Error>> {
        let mut full_args = ssh_base_args.clone();
        full_args.push(cmd.to_string());
        let status = Command::new("ssh").args(&full_args).status()?;
        Ok(status.success())
    };

    println!();
    println!(
        "{}",
        "┌────────────────────────────────────────────────────────────┐"
            .cyan()
            .bold()
    );
    println!(
        "{}",
        format!(
            "│  🏭  Rullst Foundry — Deploying to {:>24} │",
            provider.to_uppercase()
        )
        .cyan()
        .bold()
    );
    println!(
        "{}",
        "└────────────────────────────────────────────────────────────┘"
            .cyan()
            .bold()
    );
    println!();
    println!("  {} {}", "→ App:".bold(), app_name.cyan());
    println!("  {} {}", "→ Domain:".bold(), domain.cyan());
    println!(
        "  {} {}",
        "→ Server:".bold(),
        format!("{}@{}", user, host).cyan()
    );
    println!("  {} {}", "→ Port:".bold(), app_port.cyan());
    println!("  {} {}", "→ DB:".bold(), db_type.cyan());
    println!(
        "  {} {}",
        "→ Profile:".bold(),
        if profile.is_empty() {
            "release".to_string()
        } else {
            profile.clone()
        }
        .cyan()
    );
    println!();

    // ── Step 1: Build ────────────────────────────────────────────────
    println!(
        "{}",
        "📦 [1/5] Building production binary...".bold().yellow()
    );
    let mut build_args = vec!["build".to_string()];
    if profile != "debug" {
        build_args.push("--release".to_string());
    }
    if !target_triple.is_empty() {
        build_args.push("--target".to_string());
        build_args.push(target_triple.clone());
    }
    let build_status = Command::new("cargo").args(&build_args).status()?;
    if !build_status.success() {
        println!("{}", "❌ Build failed. Aborting deployment.".red().bold());
        std::process::exit(1);
    }
    println!("{}", "  ✅ Build successful.".green());

    // Determine binary path
    let bin_subdir = if target_triple.is_empty() {
        if profile == "debug" {
            "debug".to_string()
        } else {
            "release".to_string()
        }
    } else {
        format!(
            "{}/{}",
            target_triple,
            if profile == "debug" {
                "debug"
            } else {
                "release"
            }
        )
    };
    let cargo_toml_content = fs::read_to_string("Cargo.toml").unwrap_or_default();
    let bin_name = cargo_toml_content
        .lines()
        .find(|l| l.trim_start().starts_with("name"))
        .and_then(|l| l.split('=').nth(1))
        .map(|s| s.trim().trim_matches('"').to_string())
        .unwrap_or_else(|| app_name.clone());
    let local_bin = format!("target/{}/{}", bin_subdir, bin_name);

    // ── Step 2: Provision server ─────────────────────────────────────
    println!(
        "{}",
        "🖥️  [2/5] Provisioning server environment..."
            .bold()
            .yellow()
    );
    let provision_cmd = r#"set -e
apt-get update -qq
apt-get install -y -qq docker.io curl wget || yum install -y docker curl wget || true
systemctl enable docker --now || true
mkdir -p /app/data /app/bin /app/config
echo "✅ Server environment ready.""#
        .to_string();
    if !run_ssh(&provision_cmd)? {
        println!(
            "{}",
            "⚠️  Server provisioning had warnings (continuing anyway)...".yellow()
        );
    } else {
        println!("{}", "  ✅ Server provisioned.".green());
    }

    // ── Step 3: Upload binary ─────────────────────────────────────────
    println!(
        "{}",
        "📤 [3/5] Uploading application binary...".bold().yellow()
    );
    let mut scp_args = Vec::new();
    scp_args.push("-P".to_string());
    scp_args.push(ssh_port_num.clone());
    if !ssh_key_expanded.is_empty() {
        scp_args.push("-i".to_string());
        scp_args.push(ssh_key_expanded.clone());
    }
    scp_args.push("-o".to_string());
    scp_args.push("StrictHostKeyChecking=no".to_string());
    scp_args.push(local_bin.clone());
    scp_args.push(format!("{}@{}:/app/bin/{}", user, host, bin_name));

    let scp_status = Command::new("scp").args(&scp_args).status()?;
    if !scp_status.success() {
        println!(
            "{}",
            "❌ Failed to upload binary via SCP. Check SSH access and try again."
                .red()
                .bold()
        );
        std::process::exit(1);
    }
    println!("{}", "  ✅ Binary uploaded to /app/bin/.".green());

    // ── Step 4: Write env + Caddyfile + start container ──────────────
    println!(
        "{}",
        "⚙️  [4/5] Configuring services (env, Caddy, container)..."
            .bold()
            .yellow()
    );

    let caddy_site = if auto_https == "true" || auto_https.is_empty() {
        format!(
            r#"{domain} {{
    reverse_proxy localhost:{app_port}
    encode gzip zstd
    header {{
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Frame-Options DENY
        X-Content-Type-Options nosniff
        Referrer-Policy strict-origin-when-cross-origin
    }}
    log {{
        output file /var/log/caddy/{app_name}.log
    }}
}}"#,
            domain = domain,
            app_port = app_port,
            app_name = app_name
        )
    } else {
        format!(
            r#":{app_port} {{
    reverse_proxy localhost:{app_port}
}}"#,
            app_port = app_port
        )
    };

    let configure_cmd = format!(
        r#"set -e
# Write env file
cat > /app/config/.env << 'ENVEOF'
{env_lines}
ENVEOF

# Write Caddyfile
cat > /etc/caddy/Caddyfile << 'CADDYEOF'
{caddy_site}
CADDYEOF

# Install Caddy if not present
if ! command -v caddy &> /dev/null; then
    curl -fsSL https://caddyserver.com/install.sh | bash -s -- --
fi

# Make binary executable
chmod +x /app/bin/{bin_name}

# Stop old service if running
docker rm -f rullst_{app_name} 2>/dev/null || true
pkill -f "/app/bin/{bin_name}" 2>/dev/null || true

# Start app as background systemd service
cat > /etc/systemd/system/rullst_{app_name}.service << 'SVCEOF'
[Unit]
Description=Rullst App: {app_name}
After=network.target

[Service]
Type=simple
ExecStart=/app/bin/{bin_name}
WorkingDirectory=/app/data
EnvironmentFile=/app/config/.env
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable rullst_{app_name}
systemctl restart rullst_{app_name}

# Reload Caddy
systemctl enable caddy 2>/dev/null || true
systemctl reload caddy 2>/dev/null || systemctl restart caddy 2>/dev/null || caddy reload 2>/dev/null || true

echo "✅ Services configured and started."
"#,
        env_lines = env_vars
            .iter()
            .map(|(k, v)| format!("{}={}", k, v))
            .collect::<Vec<_>>()
            .join("\n"),
        caddy_site = caddy_site,
        bin_name = bin_name,
        app_name = app_name,
    );

    if !run_ssh(&configure_cmd)? {
        println!(
            "{}",
            "⚠️  Service configuration had warnings. Verify on the server.".yellow()
        );
    } else {
        println!("{}", "  ✅ Services configured and started.".green());
    }

    // ── Step 5: Health check ──────────────────────────────────────────
    println!(
        "{}",
        "🩺 [5/5] Running deployment health check..."
            .bold()
            .yellow()
    );
    let health_cmd = format!(
        "sleep 3 && curl -sf http://localhost:{app_port} > /dev/null && echo '✅ App is responding!' || echo '⚠️  App may still be starting...'",
        app_port = app_port
    );
    let _ = run_ssh(&health_cmd);

    println!();
    println!(
        "{}",
        "┌────────────────────────────────────────────────────────────┐"
            .green()
            .bold()
    );
    println!(
        "{}",
        "│  🎉  Rullst Foundry — Deployment Complete!                  │"
            .green()
            .bold()
    );
    println!(
        "{}",
        "└────────────────────────────────────────────────────────────┘"
            .green()
            .bold()
    );
    println!();
    let url_protocol = if auto_https == "true" || auto_https.is_empty() {
        "https"
    } else {
        "http"
    };
    println!(
        "  {} {}://{}",
        "🌐 Your app is live at:".bold(),
        url_protocol,
        domain.cyan().bold()
    );
    println!(
        "  {}",
        "📋 To check logs: ssh into your server and run:".bold()
    );
    println!(
        "     {}",
        format!("journalctl -u rullst_{} -f", app_name).magenta()
    );
    println!();

    Ok(())
}
