use colored::*;
use std::fs;
use std::path::Path;

pub fn create_new_grpc_service(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    let service_name = to_camel_case(name);
    let file_name = to_snake_case(name);

    // 1. Create proto directory and proto file
    let proto_dir = Path::new("proto");
    if !proto_dir.exists() {
        fs::create_dir_all(proto_dir)?;
    }

    let proto_path = proto_dir.join(format!("{}.proto", file_name));
    if !proto_path.exists() {
        let proto_code = format!(
            r#"syntax = "proto3";

package {};

service {}Service {{
    rpc SayHello (HelloRequest) returns (HelloResponse);
}}

message HelloRequest {{
    string name = 1;
}}

message HelloResponse {{
    string message = 1;
}}
"#,
            file_name, service_name
        );
        fs::write(&proto_path, proto_code)?;
        println!(
            "{}",
            format!("✨ Created Protobuf definition at {}", proto_path.display())
                .bold()
                .green()
        );
    }

    // 2. Create src/grpc directory and service handler
    let grpc_dir = Path::new("src/grpc");
    if !grpc_dir.exists() {
        fs::create_dir_all(grpc_dir)?;
    }

    let file_path = grpc_dir.join(format!("{}.rs", file_name));
    if file_path.exists() {
        return Err(format!(
            "gRPC service file '{}' already exists!",
            file_path.display()
        )
        .into());
    }

    let mut code = String::new();
    code.push_str("// gRPC Service Implementation generated by Rullst Framework\n");
    code.push_str("use tonic::{Request, Response, Status};\n\n");
    code.push_str(&format!(
        "// Make sure tonic-build compiles proto/{}.proto in build.rs\n",
        file_name
    ));
    code.push_str("pub mod proto {\n");
    code.push_str(&format!("    tonic::include_proto!(\"{}\");\n", file_name));
    code.push_str("}\n\n");
    code.push_str(
        &format!(
            "use proto::{}____service_server::{}____service;\n",
            file_name, service_name
        )
        .replace("____", ""),
    );
    code.push_str("use proto::{HelloRequest, HelloResponse};\n\n");
    code.push_str("#[derive(Debug, Default)]\n");
    code.push_str(&format!("pub struct {}ServiceImpl;\n\n", service_name));
    code.push_str("#[tonic::async_trait]\n");
    code.push_str(&format!(
        "impl {}Service for {}ServiceImpl {{\n",
        service_name, service_name
    ));
    code.push_str("    async fn say_hello(\n");
    code.push_str("        &self,\n");
    code.push_str("        request: Request<HelloRequest>,\n");
    code.push_str("    ) -> Result<Response<HelloResponse>, Status> {\n");
    code.push_str("        let reply = HelloResponse {\n");
    code.push_str("            message: format!(\"Hello {} from Rullst gRPC!\", request.into_inner().name),\n");
    code.push_str("        };\n");
    code.push_str("        Ok(Response::new(reply))\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    fs::write(&file_path, code)?;

    // Register module in src/grpc/mod.rs
    let mod_path = grpc_dir.join("mod.rs");
    let mod_entry = format!("pub mod {};\n", file_name);
    if mod_path.exists() {
        let mut content = fs::read_to_string(&mod_path)?;
        if !content.contains(&mod_entry) {
            content.push_str(&mod_entry);
            fs::write(&mod_path, content)?;
        }
    } else {
        fs::write(&mod_path, format!("pub mod {};\n", file_name))?;
    }

    println!(
        "{}",
        format!(
            "✨ Created gRPC Service handler '{}' at {}",
            service_name,
            file_path.display()
        )
        .bold()
        .green()
    );
    println!("  To mount gRPC server alongside Axum HTTP in main.rs:");
    println!("   {}", "use tonic::transport::Server;".to_string().cyan());
    println!("   {}", format!("// Server::builder().add_service({}ServiceServer::new({}ServiceImpl::default())).serve(addr).await?;", service_name, service_name).cyan());

    Ok(())
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else if c == '-' || c == ' ' {
            result.push('_');
        } else {
            result.push(c);
        }
    }
    result
}
