use crate::generators::{is_rullst_project, is_valid_rust_identifier};
use colored::*;
use std::fs;
use std::io::{Error as IoError, ErrorKind, Write};
use std::path::Path;

fn write_new(path: &Path, contents: &[u8]) -> Result<(), IoError> {
    let mut output = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| {
            if error.kind() == ErrorKind::AlreadyExists {
                IoError::new(
                    ErrorKind::AlreadyExists,
                    format!(
                        "refusing to overwrite existing gRPC output '{}'",
                        path.display()
                    ),
                )
            } else {
                error
            }
        })?;
    if let Err(error) = output.write_all(contents) {
        drop(output);
        let _ = fs::remove_file(path);
        return Err(error);
    }
    Ok(())
}

pub fn create_new_grpc_service(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        return Err(IoError::new(
            ErrorKind::InvalidInput,
            "make:grpc must run in a Rullst project root",
        )
        .into());
    }

    let base_name = to_camel_case(name);
    let file_name = to_snake_case(name);
    if base_name.is_empty() || !is_valid_rust_identifier(&file_name) {
        return Err(IoError::new(
            ErrorKind::InvalidInput,
            "gRPC service name must produce a valid non-keyword Rust identifier",
        )
        .into());
    }
    let service_name = if base_name.ends_with("Service") {
        base_name
    } else {
        format!("{base_name}Service")
    };
    let service_module = to_snake_case(&service_name);
    let implementation_name = format!("{service_name}Impl");

    let proto_dir = Path::new("proto");
    let proto_path = proto_dir.join(format!("{}.proto", file_name));
    let grpc_dir = Path::new("src/grpc");
    let file_path = grpc_dir.join(format!("{}.rs", file_name));
    if proto_path.exists() || file_path.exists() {
        return Err(IoError::new(
            ErrorKind::AlreadyExists,
            format!(
                "refusing to overwrite existing gRPC output '{}' or '{}'",
                proto_path.display(),
                file_path.display()
            ),
        )
        .into());
    }

    fs::create_dir_all(proto_dir)?;
    fs::create_dir_all(grpc_dir)?;

    let proto_code = format!(
        r#"syntax = "proto3";

package {};

service {} {{
    rpc SayHello (HelloRequest) returns (HelloResponse);
}}

message HelloRequest {{
    string name = 1;
}}

message HelloResponse {{
    string message = 1;
}}
"#,
        file_name, service_name
    );
    write_new(&proto_path, proto_code.as_bytes())?;
    println!(
        "{}",
        format!("✨ Created Protobuf definition at {}", proto_path.display())
            .bold()
            .green()
    );

    let mut code = String::new();
    code.push_str("// gRPC Service Implementation generated by Rullst Framework\n");
    code.push_str("use tonic::{Request, Response, Status};\n\n");
    code.push_str(&format!(
        "// Make sure tonic-build compiles proto/{}.proto in build.rs\n",
        file_name
    ));
    code.push_str("pub mod proto {\n");
    code.push_str(&format!("    tonic::include_proto!(\"{}\");\n", file_name));
    code.push_str("}\n\n");
    code.push_str(&format!(
        "use proto::{}_server::{};\n",
        service_module, service_name
    ));
    code.push_str("use proto::{HelloRequest, HelloResponse};\n\n");
    code.push_str("#[derive(Debug, Default)]\n");
    code.push_str(&format!("pub struct {};\n\n", implementation_name));
    code.push_str("#[tonic::async_trait]\n");
    code.push_str(&format!(
        "impl {} for {} {{\n",
        service_name, implementation_name
    ));
    code.push_str("    async fn say_hello(\n");
    code.push_str("        &self,\n");
    code.push_str("        request: Request<HelloRequest>,\n");
    code.push_str("    ) -> Result<Response<HelloResponse>, Status> {\n");
    code.push_str("        let reply = HelloResponse {\n");
    code.push_str("            message: format!(\"Hello {} from Rullst gRPC!\", request.into_inner().name),\n");
    code.push_str("        };\n");
    code.push_str("        Ok(Response::new(reply))\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    if let Err(error) = write_new(&file_path, code.as_bytes()) {
        let _ = fs::remove_file(&proto_path);
        return Err(error.into());
    }

    // Register module in src/grpc/mod.rs
    let mod_path = grpc_dir.join("mod.rs");
    let mod_entry = format!("pub mod {};\n", file_name);
    if mod_path.exists() {
        let mut content = fs::read_to_string(&mod_path)?;
        if !content.contains(&mod_entry) {
            content.push_str(&mod_entry);
            fs::write(&mod_path, content)?;
        }
    } else {
        fs::write(&mod_path, format!("pub mod {};\n", file_name))?;
    }

    println!(
        "{}",
        format!(
            "✨ Created gRPC Service handler '{}' at {}",
            service_name,
            file_path.display()
        )
        .bold()
        .green()
    );
    println!("  To mount the gRPC server alongside Axum HTTP in main.rs:");
    println!("   {}", "use tonic::transport::Server;".to_string().cyan());
    println!(
        "   {}",
        format!(
            "// Server::builder().add_service({}Server::new({}::default())).serve(addr).await?;",
            service_name, implementation_name
        )
        .cyan()
    );

    Ok(())
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else if c == '-' || c == ' ' {
            result.push('_');
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn service_suffix_is_not_duplicated() {
        for (input, expected) in [("User", "UserService"), ("UserService", "UserService")] {
            let base = to_camel_case(input);
            let service = if base.ends_with("Service") {
                base
            } else {
                format!("{base}Service")
            };
            assert_eq!(service, expected);
            assert_eq!(to_snake_case(&service), "user_service");
        }
    }

    #[test]
    fn generated_files_are_create_new_and_preserve_the_first_contents() {
        let directory = tempdir().expect("temporary directory");
        let path = directory.path().join("service.proto");
        write_new(&path, b"first").expect("first write");
        assert_eq!(
            write_new(&path, b"second")
                .expect_err("second write must fail")
                .kind(),
            ErrorKind::AlreadyExists
        );
        assert_eq!(fs::read(path).expect("generated file"), b"first");
    }
}
