// src/generators/ts.rs — TypeScript SDK Generator

use crate::generators::is_rullst_project;
use colored::*;
use std::fs;
use std::path::Path;

pub fn generate_ts_sdk() -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        println!(
            "{}",
            "❌ Error: This command must be executed in the root of a valid Rullst project."
                .red()
                .bold()
        );
        std::process::exit(1);
    }

    println!(
        "{}",
        "🔍 Scanning project to extract routes and generate TypeScript SDK..."
            .cyan()
            .bold()
    );

    let main_path = Path::new("src/main.rs");
    if !main_path.exists() {
        println!("{}", "❌ Error: File src/main.rs not found.".red());
        std::process::exit(1);
    }

    let main_content = fs::read_to_string(main_path)?;

    // Parses Axum get/post/put/delete routing patterns
    let route_regex = regex::Regex::new(
        r#"(get|post|put|delete|patch|options|head)\s*\(\s*"([^"]+)"\s*=>\s*([\w_:]+)\s*\)"#,
    )?;

    let mut ts_output = String::new();
    ts_output.push_str("// Auto-generated by Rullst v5.0.0 TS SDK Generator\n");
    ts_output.push_str("// Do not edit manually.\n\n");
    ts_output.push_str("export class RullstClient {\n");
    ts_output.push_str("    private baseUrl: string;\n\n");
    ts_output.push_str("    constructor(baseUrl: string = '') {\n");
    ts_output.push_str("        this.baseUrl = baseUrl;\n");
    ts_output.push_str("    }\n\n");
    ts_output.push_str("    private async request<T>(method: string, path: string, body?: any): Promise<T> {\n");
    ts_output.push_str("        const url = `${this.baseUrl}${path}`;\n");
    ts_output.push_str("        const options: RequestInit = { method };\n");
    ts_output.push_str("        if (body) {\n");
    ts_output.push_str("            options.headers = { 'Content-Type': 'application/json' };\n");
    ts_output.push_str("            options.body = JSON.stringify(body);\n");
    ts_output.push_str("        }\n");
    ts_output.push_str("        const res = await fetch(url, options);\n");
    ts_output.push_str("        if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);\n");
    ts_output.push_str("        return res.json() as Promise<T>;\n");
    ts_output.push_str("    }\n\n");

    for cap in route_regex.captures_iter(&main_content) {
        let method = cap[1].to_lowercase();
        let path = cap[2].to_string();
        let handler_path = cap[3].to_string();

        let mut method_name = handler_path.replace("::", "_");
        if method_name.starts_with("controllers_") {
            method_name = method_name["controllers_".len()..].to_string();
        }

        let mut path_args = Vec::new();
        let mut js_path = path.clone();

        for segment in path.split('/') {
            if segment.starts_with(':') {
                let arg_name = &segment[1..];
                path_args.push(format!("{}: string | number", arg_name));
                js_path = js_path.replace(segment, &format!("${{{}}}", arg_name));
            }
        }

        let has_body = method == "post" || method == "put" || method == "patch";
        if has_body {
            path_args.push("body: any".to_string());
        }

        ts_output.push_str(&format!("    public async {}({}) {{\n", method_name, path_args.join(", ")));
        if has_body {
            ts_output.push_str(&format!("        return this.request<any>('{}', `{}`, body);\n", method.to_uppercase(), js_path));
        } else {
            ts_output.push_str(&format!("        return this.request<any>('{}', `{}`);\n", method.to_uppercase(), js_path));
        }
        ts_output.push_str("    }\n\n");
    }

    ts_output.push_str("}\n");

    let output_path = Path::new("rullst-client.ts");
    fs::write(output_path, ts_output)?;

    println!(
        "{}",
        format!(
            "✨ TypeScript SDK successfully generated at '{}'!",
            output_path.display()
        )
        .green()
        .bold()
    );
    Ok(())
}
