// src/generators/ts.rs — TypeScript SDK Generator

use crate::generators::is_rullst_project;
use colored::*;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg_attr(mutants, mutants::skip)]
pub fn generate_ts_sdk() -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        return Err(crate::ui::error_report::ProjectRequired.into());
    }

    println!(
        "{}",
        "🔍 Scanning project to extract routes and generate TypeScript SDK..."
            .cyan()
            .bold()
    );

    let Some(route_sources) = route_sources(Path::new("."))? else {
        println!(
            "{}",
            "❌ Error: Neither src/main.rs nor src/lib.rs found.".red()
        );
        std::process::exit(1);
    };

    let ts_output = render_ts_sdk(&route_sources)?;

    let output_path = Path::new(SDK_FILE);
    fs::write(output_path, ts_output)?;

    println!(
        "{}",
        format!(
            "✨ TypeScript SDK successfully generated at '{}'!",
            output_path.display()
        )
        .green()
        .bold()
    );
    Ok(())
}

/// The generated client, at the project root.
const SDK_FILE: &str = "rullst-client.ts";

/// The concatenated route sources of the project at `root`, if any exist.
///
/// Hot-reload projects declare routes in src/lib.rs (as generate:openapi reads).
fn route_sources(root: &Path) -> std::io::Result<Option<String>> {
    let mut sources = String::new();
    for source in ["src/main.rs", "src/lib.rs"] {
        let path = root.join(source);
        if path.exists() {
            sources.push_str(&fs::read_to_string(path)?);
            sources.push('\n');
        }
    }
    Ok((!sources.is_empty()).then_some(sources))
}

/// Regenerates the client of the project at `root` for `dev --ts-sync`,
/// returning an error instead of printing or exiting the supervisor.
pub(crate) fn sync_ts_sdk(root: &Path) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let sources = route_sources(root)?.ok_or("neither src/main.rs nor src/lib.rs exists")?;
    let output = root.join(SDK_FILE);
    fs::write(&output, render_ts_sdk(&sources)?)?;
    Ok(output)
}

/// The client class up to its generated route methods. State-changing
/// requests follow `csrf_middleware`'s double-submit contract: the
/// `rullst_csrf` cookie value is echoed in the `X-CSRF-Token` header (a JSON
/// body cannot carry the `_token` form field), and cookies are sent with
/// `credentials: 'same-origin'` unless the caller chooses otherwise.
const CLIENT_PRELUDE: &str = r#"// Auto-generated by `cargo rullst generate:ts`
// Do not edit manually.

export interface RullstClientOptions {
    /** Supplies the CSRF token for POST/PUT/PATCH/DELETE; defaults to the `rullst_csrf` cookie. */
    csrfToken?: () => string | undefined;
    /** Fetch credentials mode; defaults to 'same-origin' so the CSRF and session cookies are sent. */
    credentials?: RequestCredentials;
}

/** Reads the double-submit `rullst_csrf` cookie that Rullst sets on GET and HEAD responses. */
function rullstCsrfCookie(): string | undefined {
    if (typeof document === 'undefined') return undefined;
    for (const entry of document.cookie.split(';')) {
        const separator = entry.indexOf('=');
        if (separator < 0 || entry.slice(0, separator).trim() !== 'rullst_csrf') continue;
        const token = entry.slice(separator + 1).trim();
        return /^[A-Za-z0-9_-]{1,128}$/.test(token) ? token : undefined;
    }
    return undefined;
}

export class RullstClient {
    private baseUrl: string;
    private options: RullstClientOptions;

    constructor(baseUrl: string = '', options: RullstClientOptions = {}) {
        this.baseUrl = baseUrl;
        this.options = options;
    }

    private async request<T>(method: string, path: string, body?: any): Promise<T> {
        const url = `${this.baseUrl}${path}`;
        const headers: Record<string, string> = {};
        const options: RequestInit = {
            method,
            headers,
            credentials: this.options.credentials ?? 'same-origin',
        };
        if (body) {
            headers['Content-Type'] = 'application/json';
            options.body = JSON.stringify(body);
        }
        if (!['GET', 'HEAD', 'OPTIONS', 'TRACE'].includes(method)) {
            const token = (this.options.csrfToken ?? rullstCsrfCookie)();
            if (token) headers['X-CSRF-Token'] = token;
        }
        const res = await fetch(url, options);
        if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);
        return res.json() as Promise<T>;
    }

"#;

/// Renders the TypeScript client for the `routes!` declarations in `source`.
fn render_ts_sdk(source: &str) -> Result<String, regex::Error> {
    // Parses Axum get/post/put/delete routing patterns
    let route_regex = regex::Regex::new(
        r#"(get|post|put|delete|patch|options|head)\s*\(\s*"([^"]+)"\s*=>\s*([\w_:]+)\s*\)"#,
    )?;

    let mut ts_output = String::from(CLIENT_PRELUDE);

    for cap in route_regex.captures_iter(source) {
        let method = cap[1].to_lowercase();
        let path = cap[2].to_string();
        let handler_path = cap[3].to_string();

        let mut method_name = handler_path.replace("::", "_");
        if method_name.starts_with("controllers_") {
            method_name = method_name["controllers_".len()..].to_string();
        }

        let mut path_args = Vec::new();
        let js_path = path
            .split('/')
            .map(|segment| match path_parameter(segment) {
                Some((name, wildcard)) => {
                    path_args.push(format!("{name}: string | number"));
                    if wildcard {
                        // Keep the separators of a `{*rest}` capture.
                        format!("${{String({name}).split('/').map(encodeURIComponent).join('/')}}")
                    } else {
                        format!("${{encodeURIComponent({name})}}")
                    }
                }
                None => segment.to_string(),
            })
            .collect::<Vec<_>>()
            .join("/");

        let has_body = method == "post" || method == "put" || method == "patch";
        if has_body {
            path_args.push("body: any".to_string());
        }

        ts_output.push_str(&format!(
            "    public async {}({}) {{\n",
            method_name,
            path_args.join(", ")
        ));
        if has_body {
            ts_output.push_str(&format!(
                "        return this.request<any>('{}', `{}`, body);\n",
                method.to_uppercase(),
                js_path
            ));
        } else {
            ts_output.push_str(&format!(
                "        return this.request<any>('{}', `{}`);\n",
                method.to_uppercase(),
                js_path
            ));
        }
        ts_output.push_str("    }\n\n");
    }

    ts_output.push_str("}\n");
    Ok(ts_output)
}

/// Returns the TypeScript argument name of an axum 0.8 `{name}`/`{*name}`
/// capture (or a legacy `:name` segment) and whether it is a wildcard.
fn path_parameter(segment: &str) -> Option<(String, bool)> {
    let (raw, wildcard) = if let Some(inner) = segment
        .strip_prefix('{')
        .and_then(|value| value.strip_suffix('}'))
    {
        match inner.strip_prefix('*') {
            Some(rest) => (rest, true),
            None => (inner, false),
        }
    } else {
        (segment.strip_prefix(':')?, false)
    };
    let mut name: String = raw
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if name.is_empty() {
        return None;
    }
    if name.starts_with(|c: char| c.is_ascii_digit()) {
        name.insert(0, '_');
    }
    Some((name, wildcard))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn braced_and_wildcard_captures_become_encoded_arguments() {
        let sdk = render_ts_sdk(
            r#"routes![
                get("/courses/{id}" => controllers::lms_controller::show_course),
                get("/files/{*path}" => controllers::files::download),
                put("/users/:id" => controllers::users::update),
            ]"#,
        )
        .unwrap();
        assert!(sdk.contains("public async lms_controller_show_course(id: string | number)"));
        assert!(sdk.contains("`/courses/${encodeURIComponent(id)}`"));
        assert!(!sdk.contains("/courses/{id}"));
        assert!(sdk.contains("public async files_download(path: string | number)"));
        assert!(
            sdk.contains("`/files/${String(path).split('/').map(encodeURIComponent).join('/')}`")
        );
        assert!(sdk.contains("public async users_update(id: string | number, body: any)"));
        assert!(sdk.contains("`/users/${encodeURIComponent(id)}`, body"));
    }

    #[test]
    fn state_changing_requests_echo_the_csrf_cookie_in_the_header() {
        let sdk = render_ts_sdk(
            r#"routes![
                post("/posts" => controllers::posts::store),
                delete("/posts/{id}" => controllers::posts::destroy),
            ]"#,
        )
        .unwrap();
        // The cookie and header names `csrf_middleware` matches.
        assert!(sdk.contains("'rullst_csrf'"));
        assert!(sdk.contains("headers['X-CSRF-Token'] = token;"));
        assert!(sdk.contains("!['GET', 'HEAD', 'OPTIONS', 'TRACE'].includes(method)"));
        assert!(sdk.contains("credentials: this.options.credentials ?? 'same-origin'"));
        assert!(
            sdk.contains("constructor(baseUrl: string = '', options: RullstClientOptions = {})")
        );
        assert!(sdk.contains("return this.request<any>('POST', `/posts`, body);"));
        assert!(
            sdk.contains("return this.request<any>('DELETE', `/posts/${encodeURIComponent(id)}`);")
        );
        assert!(sdk.ends_with("    }\n\n}\n"));
    }

    #[test]
    fn literal_segments_are_not_treated_as_parameters() {
        assert_eq!(path_parameter("courses"), None);
        assert_eq!(path_parameter("{}"), None);
        assert_eq!(
            path_parameter("{user-id}"),
            Some(("user_id".to_string(), false))
        );
        assert_eq!(path_parameter("{*rest}"), Some(("rest".to_string(), true)));
    }
}
