use crate::generators::is_rullst_project;
use colored::*;
use std::fs;
use std::path::Path;

pub fn scaffold_mfa_system() -> Result<(), Box<dyn std::error::Error>> {
    if !is_rullst_project() {
        println!(
            "{}",
            "❌ Error: This command must be executed in the root of a valid Rullst project."
                .red()
                .bold()
        );
        std::process::exit(1);
    }

    println!(
        "{}",
        "🔐 Scaffolding Rullst 2FA / MFA TOTP authentication controller..."
            .cyan()
            .bold()
    );

    let ctrl_dir = Path::new("src/controllers");
    if !ctrl_dir.exists() {
        fs::create_dir_all(ctrl_dir)?;
    }

    let mfa_ctrl_path = ctrl_dir.join("mfa.rs");
    let mfa_code = r#"// Generated by cargo rullst make:mfa — 2FA TOTP Controller
use axum::{extract::Form, response::{Html, IntoResponse, Redirect}, Json};
use rullst_security::{build_otpauth_uri, generate_mfa_secret, generate_totp_code, verify_totp_code};
use serde::{Deserialize, Serialize};

#[derive(Serialize)]
pub struct MfaSetupResponse {
    pub secret: String,
    pub otpauth_url: String,
}

#[derive(Deserialize)]
pub struct MfaVerifyForm {
    pub secret: String,
    pub code: String,
}

/// GET /auth/mfa/setup — Generates a new TOTP Base32 secret and QR code URI.
pub async fn mfa_setup() -> Json<MfaSetupResponse> {
    let secret = generate_mfa_secret();
    let otpauth_url = build_otpauth_uri("RullstApp", "user@example.com", &secret);
    Json(MfaSetupResponse { secret, otpauth_url })
}

/// POST /auth/mfa/verify — Validates a 6-digit 2FA TOTP code.
pub async fn mfa_verify(Form(form): Form<MfaVerifyForm>) -> impl IntoResponse {
    if verify_totp_code(&form.secret, &form.code) {
        Html("<div class=\"alert alert-success\">✅ 2FA Code Verified Successfully!</div>").into_response()
    } else {
        Html("<div class=\"alert alert-danger\">❌ Invalid 2FA Code. Please try again.</div>").into_response()
    }
}
"#;

    fs::write(&mfa_ctrl_path, mfa_code)?;
    println!(
        "  {} Scaffolded {}",
        "[CREATE]".green().bold(),
        mfa_ctrl_path.display()
    );

    println!(
        "{}",
        "✅ 2FA MFA TOTP controller scaffolded successfully!"
            .green()
            .bold()
    );

    Ok(())
}
