use crate::{LibraryId, MediaError as Error, ProviderMode, contracts::media_type_valid};
use reqwest::Url;
use zeroize::Zeroizing;

/// Signing credentials. Debug and errors never expose them.
///
/// Empty values or two `mock_*` values select the deterministic offline mock;
/// two `fixture_*` values select a loopback protocol fixture. Mixed or partial
/// credentials are rejected.
pub struct S3Credentials {
    pub(super) access_key: Zeroizing<String>,
    pub(super) secret_key: Zeroizing<String>,
    pub(super) session_token: Option<Zeroizing<String>>,
    pub(super) mode: ProviderMode,
}
impl S3Credentials {
    pub fn new(
        access_key: impl Into<String>,
        secret_key: impl Into<String>,
    ) -> Result<Self, Error> {
        let access_key = Zeroizing::new(access_key.into());
        let secret_key = Zeroizing::new(secret_key.into());
        let mode_of = |value: &str| {
            if value.is_empty() || value.starts_with("mock_") {
                ProviderMode::Offline
            } else if value.starts_with("fixture_") {
                ProviderMode::ProtocolFixture
            } else {
                ProviderMode::RemoteUnvalidated
            }
        };
        let mode = mode_of(&access_key);
        if mode != mode_of(&secret_key)
            || access_key.is_empty() != secret_key.is_empty()
            || access_key.len() > 128
            || secret_key.len() > 256
            || !access_key
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'_')
            || !secret_key.bytes().all(|b| b.is_ascii_graphic())
            || (mode != ProviderMode::Offline && (access_key.len() < 3 || secret_key.len() < 8))
        {
            return Err(Error::Configuration);
        }
        Ok(Self {
            access_key,
            secret_key,
            session_token: None,
            mode,
        })
    }

    /// Reads `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and the optional
    /// `AWS_SESSION_TOKEN`. When both keys are unset the offline mock is used,
    /// which the `sqlite` feature's `StoreConfig::production` rejects.
    pub fn from_env() -> Result<Self, Error> {
        let read = |name: &str| match std::env::var(name) {
            Ok(value) => Ok(Some(value)),
            Err(std::env::VarError::NotPresent) => Ok(None),
            Err(std::env::VarError::NotUnicode(_)) => Err(Error::Configuration),
        };
        let credentials = Self::new(
            read("AWS_ACCESS_KEY_ID")?.unwrap_or_default(),
            read("AWS_SECRET_ACCESS_KEY")?.unwrap_or_default(),
        )?;
        match read("AWS_SESSION_TOKEN")? {
            Some(token) if !token.is_empty() => credentials.with_session_token(token),
            _ => Ok(credentials),
        }
    }

    /// Temporary credentials. Their expiry is managed by the host, which must
    /// replace the adapter before the token expires.
    pub fn with_session_token(mut self, token: impl Into<String>) -> Result<Self, Error> {
        let token = Zeroizing::new(token.into());
        if self.mode == ProviderMode::Offline
            || token.is_empty()
            || token.len() > 8192
            || !token.bytes().all(|b| b.is_ascii_graphic())
        {
            return Err(Error::Configuration);
        }
        self.session_token = Some(token);
        Ok(self)
    }

    pub fn mode(&self) -> ProviderMode {
        self.mode
    }
}
impl std::fmt::Debug for S3Credentials {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("S3Credentials([REDACTED])")
    }
}

/// One private bucket and key prefix. Object keys are always generated by the
/// adapter: `{prefix}{video}/original` and `{prefix}{video}/metadata.json`.
#[derive(Debug)]
pub struct S3Config {
    pub(super) library: LibraryId,
    pub(super) endpoint: Url,
    pub(super) region: String,
    pub(super) bucket: String,
    pub(super) path_style: bool,
    pub(super) prefix: String,
    pub(super) content_types: Vec<String>,
    pub(super) max_object_bytes: u64,
    pub(super) credentials: S3Credentials,
}
impl S3Config {
    /// Default object size limit: 2 GiB.
    pub const DEFAULT_MAX_OBJECT_BYTES: u64 = 2 * 1024 * 1024 * 1024;

    /// AWS S3 at `https://s3.<region>.amazonaws.com`, virtual-hosted style.
    pub fn aws(
        library: LibraryId,
        region: impl Into<String>,
        bucket: impl Into<String>,
        credentials: S3Credentials,
    ) -> Result<Self, Error> {
        let region = region.into();
        if !region_valid(&region) || region == "auto" {
            return Err(Error::Configuration);
        }
        let endpoint = format!("https://s3.{region}.amazonaws.com");
        Self::custom(library, endpoint, region, bucket, credentials)?.with_path_style(false)
    }

    /// Cloudflare R2 at `https://<account>.r2.cloudflarestorage.com`, region
    /// `auto`, path style.
    pub fn r2(
        library: LibraryId,
        account_id: impl Into<String>,
        bucket: impl Into<String>,
        credentials: S3Credentials,
    ) -> Result<Self, Error> {
        let account = account_id.into();
        if account.is_empty()
            || account.len() > 64
            || !account
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
        {
            return Err(Error::Configuration);
        }
        let endpoint = format!("https://{account}.r2.cloudflarestorage.com");
        Self::custom(library, endpoint, "auto", bucket, credentials)
    }

    /// Any S3-compatible endpoint such as MinIO, path style. HTTPS is required
    /// except for a literal loopback address used in local development.
    pub fn custom(
        library: LibraryId,
        endpoint: impl Into<String>,
        region: impl Into<String>,
        bucket: impl Into<String>,
        credentials: S3Credentials,
    ) -> Result<Self, Error> {
        let endpoint = Url::parse(&endpoint.into()).map_err(|_| Error::Configuration)?;
        let region = region.into();
        let bucket = bucket.into();
        let loopback = endpoint_loopback(&endpoint);
        if !(endpoint.scheme() == "https" || (endpoint.scheme() == "http" && loopback))
            || endpoint.host_str().is_none()
            || !endpoint.username().is_empty()
            || endpoint.password().is_some()
            || endpoint.path() != "/"
            || endpoint.query().is_some()
            || endpoint.fragment().is_some()
            || endpoint.port() == Some(0)
            || !region_valid(&region)
            || !bucket_valid(&bucket)
        {
            return Err(Error::Configuration);
        }
        Ok(Self {
            library,
            endpoint,
            region,
            bucket,
            path_style: true,
            prefix: String::new(),
            content_types: ["video/mp4", "video/webm"].map(String::from).to_vec(),
            max_object_bytes: Self::DEFAULT_MAX_OBJECT_BYTES,
            credentials,
        })
    }

    /// Virtual-hosted style needs a DNS-safe bucket without dots.
    pub fn with_path_style(mut self, path_style: bool) -> Result<Self, Error> {
        if !path_style && (self.bucket.contains('.') || endpoint_loopback(&self.endpoint)) {
            return Err(Error::Configuration);
        }
        self.path_style = path_style;
        Ok(self)
    }

    /// Up to eight `/`-terminated segments of ASCII letters, digits, `-` and
    /// `_`, at most 256 bytes; for example `courses/videos/`.
    pub fn with_key_prefix(mut self, prefix: impl Into<String>) -> Result<Self, Error> {
        let prefix = prefix.into();
        let segments: Vec<&str> = prefix.split_terminator('/').collect();
        if prefix.len() > 256
            || (!prefix.is_empty() && !prefix.ends_with('/'))
            || segments.len() > 8
            || segments.iter().any(|segment| {
                segment.is_empty()
                    || segment.len() > 63
                    || !segment
                        .bytes()
                        .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
            })
        {
            return Err(Error::Configuration);
        }
        self.prefix = prefix;
        Ok(self)
    }

    /// Accepted upload types, 1 to 16 lower-case `type/subtype` values. The
    /// default is `video/mp4` and `video/webm`.
    pub fn with_content_types<T: Into<String>>(
        mut self,
        types: impl IntoIterator<Item = T>,
    ) -> Result<Self, Error> {
        let mut accepted: Vec<String> = types.into_iter().map(Into::into).collect();
        accepted.sort();
        accepted.dedup();
        if accepted.is_empty()
            || accepted.len() > 16
            || !accepted.iter().all(|value| media_type_valid(value))
        {
            return Err(Error::Configuration);
        }
        self.content_types = accepted;
        Ok(self)
    }

    /// Largest accepted object, from 1 byte to 5 GiB.
    pub fn with_max_object_bytes(mut self, maximum: u64) -> Result<Self, Error> {
        if maximum == 0 || maximum > crate::UploadDeclaration::MAX_LENGTH {
            return Err(Error::Configuration);
        }
        self.max_object_bytes = maximum;
        Ok(self)
    }
}

pub(super) fn endpoint_loopback(endpoint: &Url) -> bool {
    endpoint
        .host_str()
        .and_then(|host| {
            host.trim_start_matches('[')
                .trim_end_matches(']')
                .parse::<std::net::IpAddr>()
                .ok()
        })
        .is_some_and(|ip| ip.is_loopback())
}

fn region_valid(region: &str) -> bool {
    !region.is_empty()
        && region.len() <= 32
        && region
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

/// S3 bucket naming: 3 to 63 lower-case letters, digits, `-` and `.`,
/// starting and ending with a letter or digit, without `..`.
fn bucket_valid(bucket: &str) -> bool {
    let edge = |b: Option<u8>| b.is_some_and(|b| b.is_ascii_lowercase() || b.is_ascii_digit());
    (3..=63).contains(&bucket.len())
        && edge(bucket.bytes().next())
        && edge(bucket.bytes().last())
        && !bucket.contains("..")
        && bucket
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'.')
}
