homepage: "https://github.com/Rullst/Rullst"
language: rust
primary_contact: "officialrullst@gmail.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/Rullst/Rullst.git"
