pub(super) fn migration_files() -> Vec<(&'static str, String)> {
    let migration = r##"use rullst_orm::polyglot::{
    PolyglotError, TursoMigration, TursoStatement,
};

pub fn migration() -> Result<TursoMigration, PolyglotError> {
    TursoMigration::new(
        "m20260829000000_create_users_table",
        vec![TursoStatement::new(
            "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL)",
            vec![],
        )?],
    )?
    .with_down(vec![TursoStatement::new("DROP TABLE users", vec![])?])
}
"##;
    let migrations_mod = r##"// Generated by Rullst for the Turso-primary profile.
pub mod m20260829000000_create_users_table;

pub fn get_migrations() -> Result<
    Vec<rullst_orm::polyglot::TursoMigration>,
    rullst_orm::polyglot::PolyglotError,
> {
    Ok(vec![m20260829000000_create_users_table::migration()?])
}
"##;

    vec![
        (
            "src/migrations/m20260829000000_create_users_table.rs",
            migration.to_string(),
        ),
        ("src/migrations/mod.rs", migrations_mod.to_string()),
    ]
}
