spring.application.name=springboot

spring.datasource.url=jdbc:postgresql://db:5432/benchmarkdb
spring.datasource.username=benchmarkuser
spring.datasource.password=benchmarkpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Performance tuning
server.tomcat.threads.max=200
spring.thymeleaf.cache=true
logging.level.root=WARN
