name: Rust CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  CARGO_NET_RETRY: 10

defaults:
  run:
    working-directory: .

jobs:
  check:
    name: Code Quality & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Rust toolchain (with native cache)
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
        with:
          components: rustfmt, clippy

      - name: Check formatting (Workspace)
        run: cargo fmt --all -- --check

      - name: Run Clippy (Workspace)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run Clippy (Rullst optional features)
        run: cargo clippy -p rullst --all-targets --features cache-redis,queue-redis,mail-smtp -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Rust toolchain (with native cache)
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1

      - name: Run all workspace tests (Testcontainers DBs, Unit, Integration)
        run: cargo test --workspace --all-features
