name: Kani Verifier

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  kani:
    name: kani
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['rullst']

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Install Kani
        run: cargo install kani-verifier && cargo kani setup

      - name: Bypass MSRV globally in the Cargo Registry
        run: |
          cargo fetch
          find . -name Cargo.toml -exec sed -i 's/^rust-version.*//g' {} +
          find $HOME/.cargo/registry/src/ -name Cargo.toml -exec sed -i 's/^rust-version.*//g' {} +

      - name: Verify with Kani
        working-directory: ${{ matrix.package }}
        continue-on-error: true
        timeout-minutes: 300
        run: cargo kani
