name: SemVer Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # stable
        with:
          toolchain: stable
      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: cargo-semver-checks
      - name: Run SemVer checks
        run: cargo semver-checks check-release --exclude rullst-core --exclude rullst-ai --exclude rullst-capital --exclude rullst-mail --exclude rullst-auth --exclude rullst-nexus --exclude rullst-studio --exclude rullst-macros --exclude rullst-orm-macros --exclude cargo-rullst --exclude rullst-blog-example

