name: TruffleHog Secret Scanner

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  trufflehog:
    name: Scan for leaked secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.2.2
        with:
          fetch-depth: 0 # Required for TruffleHog to scan git history
          
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@d4d6275bc2738abc8091d4f25408f10dcc4b6cd0 # main @ 2026-07-30
        with:
          path: ./
          extra_args: --debug --only-verified
